### ISSUE TITLE
Address Schema Parameter

### ISSUE THREAD

**Issue by hkrishna** [pelias/api#100]
Let the user decide what version of output text they would like through the API. Perhaps an additional optional parameter lets say ```addressParts```. 

* ```&addressParts=all``` (by default): will return name, local, regional, national as defined in outputSchema.json Ex: ```Arbil, Lye, West Midlands, GBR```
* ```&addressParts=local,regional```: will return name, local, regional Ex: ```Arbil, Lye, West Midlands```

We can also push this one step further and define formats for mobile ```&addressParts=mobile``` in a config file which will cater to smaller screens. 

This issue is opened as a product of the ongoing discussions at #93

**Comment by dianashk** [comment]
Hold off until API-redesign

**Comment by dianashk** [comment]
Duped by pelias/pelias#125
