### ISSUE TITLE
Exception crashes the API service

### ISSUE THREAD

**Issue by gitsno** [pelias/api#1009]
I am seeing this exception in the API when making a reverse geocode request that causes PIP to be used - it only happens from time to time.

```
/api/node_modules/pelias-model/Document.js:44
  // that; for example; all 'address' data ends up in the same '_type', even
       ^
PeliasModelError: invalid document type, expecting: truthy, got:
    at Object.module.exports.truthy (/api/node_modules/pelias-model/util/valid.js:29:11)
    at Document.<anonymous> (/api/node_modules/pelias-model/Document.js:255:14)
    at Document.addParent (/api/node_modules/pelias-model/Document.js:291:5)
    at /api/controller/coarse_reverse.js:68:9
    at Array.forEach (native)
    at synthesizeDoc (/api/controller/coarse_reverse.js:67:19)
    at /api/controller/coarse_reverse.js:141:23
    at /api/node_modules/pelias-microservice-wrapper/service.js:110:18
    at Request.callback (/api/node_modules/superagent/lib/node/index.js:679:14)
    at /api/node_modules/superagent/lib/node/index.js:868:18
```

Here's an example of the PIP response when the exception occurs (request lat, long: 8.230468, 46.32497):

`{"county":[{"id":1108757843,"name":"Buuhoodle","centroid":{"lat":8.460155,"lon":46.661084},"bounding_box":"46.1913291522,8.001139,47.1004809601,8.82080317694"}],"region":[{"id":421194355,"name":"Togdheer","centroid":{"lat":9.109245,"lon":45.726861},"bounding_box":"44.6871075225,8.001139,47.1004809601,10.1717134889"}],"country":[{"id":85632733,"name":"Somaliland","abbr":"","centroid":{"lat":9.725679,"lon":46.275584},"bounding_box":"42.67008,8.001139,48.939110555,11.535471916"}]}`

The exception completely crashes the API so that it has to be restarted.

**Comment by orangejulius** [comment]
Hey @gitsno,
Thanks for writing in. I believe we just fixed this in https://github.com/pelias/api/pull/1003 and https://github.com/pelias/api/pull/1005. It should be fixed in both the `master` and `production` branches of API, and in the latest NPM module. Let us know if the latest code works for you, and if it doesn't, _definitely_ tell us :)

**Comment by gitsno** [comment]
Thanks @orangejulius - I have updated and can confirm that it is fixed in that it no longer crashes the API - it returns an empty features array, not sure if there should be a feature given that PIP does return a result?

Thanks!

**Comment by missinglink** [comment]
:+1: for a descriptive bug report, I was able to use your example responses to debug and fix the issue in https://github.com/pelias/api/pull/1010
