### ISSUE TITLE
Why interpolation service configuration not in "services" object?

### ISSUE THREAD

**Issue by tadjik1** [pelias/api#1025]
Hi there,
I've noticed that configuration for interpolation service is stored on top level of configuration object, but pip service and placeholder service configurations are in "services" object. Will it be more convenient way to always store configuration for services in "services" object?

**Comment by trescube** [comment]
Hi, the interpolation config is defined inside the services object like placeholder and pip. We might have missed a reference when we were updating documentation to reflect this. Where did you see interpolation defined at the top level?

**Comment by tadjik1** [comment]
@trescube in this repo, in config example

**Comment by trescube** [comment]
Ah! The most obvious place and we missed it! We'll get that patched up shortly.

**Comment by tadjik1** [comment]
@trescube hi! 
regarding `services` object. do you think that it should store inside `api` key, or it could be a top-level field? I mean there is no relation (or I don't see it) between `services` and `api`. What if I want to use services in importers, should I place this configuration inside `imports`?

**Comment by trescube** [comment]
Since the services are primarily related to and called by the API, we'd like to keep them as a child of api.  Notably, routes/v1.js uses this section for configuring the services to call: https://github.com/pelias/api/blob/master/routes/v1.js#L109

**Comment by tadjik1** [comment]
@trescube ok, thanks for explanation
