### ISSUE TITLE
microserviceify libpostal

### ISSUE THREAD

**Issue by trescube** [pelias/api#1030]
Currently the API communicates with libpostal locally which presents 3 issues:

- the API takes extra time to start
- the API cannot be run in clustered mode as each would require its own libpostal expensive instance
- treats libpostal as a special case whereas PiP, interpolation, and placeholder are configured and called as microservices

The ideal scenario would be to move libpostal to an HTTP interface elsewhere and treat it as a microservice call.

**Comment by missinglink** [comment]
see existing solutions:

- https://github.com/johnlonganecker/libpostal-rest
- https://github.com/johnlonganecker/libpostal-rest-docker
- https://hub.docker.com/r/pasupulaphani/libpostal-zeromq/

**Comment by orangejulius** [comment]
Also https://github.com/whosonfirst/go-whosonfirst-libpostal
