### ISSUE TITLE
HOST environment variable must now be set for any network-exposed API

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#1037]
Thanks to https://github.com/pelias/api/pull/1031, we now have the ability to configure the listen address for the API. However, the old default was actually to [listen on all interfaces](https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback), whereas the new default is to listen only on localhost.

This isn't a bad thing, in fact it's probably very good that by default anyone experimenting with Pelias on say, a shared wireless network, will not be exposing the API to the world.

However, it does mean that **every instance of Pelias** that wishes to serve requests over the network will need to override the HOST environment variable with a value of `0.0.0.0` or an IP address to listen on. This includes **all instances for Mapzen search, the Docker images, and anyone else using Pelias except for local development**.

This is a big breaking change and we should ensure everyone is made aware of it. At the very least we should make a big mention of this in the code changes section of the release notes. We might want to consider adding a short set of instructions to the output when the API server starts if it's listening on localhost only. Something like:

```
The API is currently listening only on the localhost interface. To accept requests from the network set the HOST environment variable, for example `HOST=0.0.0.0`
```

**Comment by trescube** [comment]
Instead of going thru all that, couldn't we just modify the conditional to, instead of:

```
const app = require('./app'),
    port = ( process.env.PORT || 3100 ),
    host = ( process.env.HOST || 'localhost' );

/** run server on the default setup (single core) **/
console.log( `pelias is now running on ${host}:${port}` );
app.listen( port, host );
```

be:

```
const app = require('./app'),
    port = ( process.env.PORT || 3100 );

/** run server on the default setup (single core) **/
if (process.env.HOST) {
    console.log( `pelias is now running on ${host}:${port}` );
    app.listen( port, process.env.HOST );
} else {
    console.log( `pelias is now running on ${port}` );
    app.listen( port );
}
```

**Comment by missinglink** [comment]
I think a nice clean option would be:

```javascript
host = ( process.env.HOST || undefined );

...

app.listen( port, host );
```

**Comment by trescube** [comment]
That would work, too.

**Comment by orangejulius** [comment]
I submitted #1043 to do basically what @missinglink suggested. Take a look!
