### ISSUE TITLE
Search/Filter by Category

### ISSUE THREAD

**Issue by hkrishna** [pelias/api#104]
Related to pelias/openstreetmap#33 and pelias/pelias#50

This issue deals with using the category mapped on a document. Here are a few use cases: 
* find all airports in a bbox
* search for a transit station
* find the 10 nearest mexican restaurants

The API should be able to take a parameter lets say ```category``` and based on its value - use it in the queries as a filter. For example: 

```
localhost:3100/search?input=maysville&category=restaurant
```
should return restaurants that are named maysville

```
localhost:3100/reverse?lat=0&lon=0&category=restaurant:mexican
```
should return the nearest mexican restaurants to lat/lon 0,0

**Comment by missinglink** [comment]
this is the query I used in dev: https://gist.github.com/missinglink/dd1dcdb377a0ff271890

**Comment by dianashk** [comment]
duplicates api#56
