### ISSUE TITLE
What to use for microservicify libpostal?

### ISSUE THREAD

**Issue by tadjik1** [pelias/api#1072]
Hi there, some time ago you've merged PR with some critical changes - now libpostal is a microservice, which is really, really great!
But now it's not clear how to setup this service. Which repo contains libpostal microservice itself?

Connects https://github.com/pelias/api/pull/1060

**Comment by orangejulius** [comment]
Good question! For now the service comes from https://github.com/whosonfirst/go-whosonfirst-libpostal, which has a dockerfile that we built and pushed to https://hub.docker.com/r/pelias/go-whosonfirst-libpostal/.

There is a [libpostal-service](https://github.com/pelias/dockerfiles/tree/libpostal-service) branch in the dockerfiles repo which may work. If you want to test it out, that would be super helpful. Let us know how it goes!

**Comment by orangejulius** [comment]
For future googlers:

```
2018-02-06T14:52:31.187Z - warn: [libpostal] libpostal service disabled
2018-02-06T14:52:31.187Z - warn: [libpostal] libpostal service disabled
```
Is the error you'll see with this issue.

Before we merge this to staging (https://github.com/pelias/api/pull/1089), we should work on updated documentation.

**Comment by orangejulius** [comment]
We've had the changes to use the libpostal service live on the production branches for a while now. It's much much better. If anyone is having issues or has questions, feel free to reply here or open a new issue.

But for now, I think we've taken care of everything.
