### ISSUE TITLE
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.transport.TransportService

### ISSUE THREAD

**Issue by reeenz20** [pelias/api#1083]
Hi guys, I have this error on elasticsearch. The logs keeps on increasing. Urgently needed help here. Thank you! :)

org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.transport.TransportService$7@52bbdff1 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@49c9d421[Running, pool size = 7, active threads = 7, queued tasks = 1000, completed tasks = 7265472

**Comment by orangejulius** [comment]
hey @reeenz20,
What did the issue turn out to be?
