### ISSUE TITLE
Bounding box support for /suggest

### ISSUE THREAD

**Issue by hkrishna** [pelias/api#110]
```/suggest``` should be able to take in a ```bbox``` parameter and return suggestions that are contained within the given bounding box. 

Here is a use-case provided by @mattkrick in https://github.com/pelias/pelias/issues/81

"_For my app, I'd like to autocomplete from a list of schools in a given town. If I use the suggest endpoint, I get suggestions from the other side of the country, but if I use the search endpoint with a bbox, it can't predict things mid-word. I think this could be best solved with a bbox on the suggest endpoint._"

resolves: https://github.com/pelias/pelias/issues/81

**Comment by dianashk** [comment]
Update documentation to explain that /suggest doesn't support bbox.

**Comment by orangejulius** [comment]
We do have focus.point.lat and focus.point.lon for `/v1/autocomplete` but we decided not to support a bounding box to make the requests more cacheable.
