### ISSUE TITLE
Cannot find libpostal installed into non-standard location

### ISSUE THREAD

**Issue by kylebarron** [pelias/api#1101]
I installed libpostal into `~/local/lib` instead of `/usr/local/lib` since I don't have sudo privileges on the server I'm using. Is there a way to tell the API what directory to look at for libpostal? 

When I run `npm start` I get the error:
```
> npm start  

> pelias-api@0.0.0-semantic-release start /disk/agedisk1/medicare.work/doyle-DUA18266/barronk/npi-geocode/lib/api
> node index.js

loading libpostal data, this may take a few seconds...
ERR   Error loading transliteration module, dir=(null)
   at libpostal_setup_datadir (libpostal.c:266) errno: No such file or directory
/disk/agedisk1/medicare.work/doyle-DUA18266/barronk/npi-geocode/lib/api/node_modules/node-postal/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: Could not load libpostal
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/disk/agedisk1/medicare.work/doyle-DUA18266/barronk/npi-geocode/lib/api/node_modules/node-postal/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/disk/agedisk1/medicare.work/doyle-DUA18266/barronk/npi-geocode/lib/api/node_modules/node-postal/index.js:3:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pelias-api@0.0.0-semantic-release start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pelias-api@0.0.0-semantic-release start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /homes/nber/barronk/.npm/_logs/2018-03-21T20_52_06_820Z-debug.log
```

**Comment by kylebarron** [comment]
This is a node-postal issue since I can't run its tests; creating issue there.

**Comment by orangejulius** [comment]
Thanks, I was just going to point you there :P 

also consider using the master branch with the libpostal docker image (https://github.com/pelias/api/issues/1072). Then you avoid all the node-postal issues and are future-proof since it's coming to the production branch soon

**Comment by kylebarron** [comment]
I don't really understand microservices or docker well. On switching to the master branch, `npm install` and `npm start` worked, but it seems to not be using libpostal at all.
```
> npm start

> pelias-api@0.0.0-semantic-release start /disk/agedisk1/medicare.work/doyle-DUA18266/barronk/npi-geocode/lib/api
> ./bin/start

2018-03-21T21:17:43.898Z - warn: [pip] pip service disabled
2018-03-21T21:17:43.901Z - warn: [placeholder] placeholder service disabled
2018-03-21T21:17:43.902Z - warn: [language] language service disabled
2018-03-21T21:17:43.902Z - warn: [interpolation] interpolation service disabled
2018-03-21T21:17:43.902Z - warn: [libpostal] libpostal service disabled
2018-03-21T21:17:43.903Z - warn: [libpostal] libpostal service disabled
pelias is now running on 10.200.0.51:3100
```

I haven't tried to set up any of the pip, placeholder, language, or interpolation services, but I'm supposing that libpostal should be reported as enabled if it's running using the docker image.

**Comment by orangejulius** [comment]
To be clear, you don't _have_ to use Docker. But at this point running only the api-service will not get you most of the functionality Pelias offers. You can set up the services individually by telling the services how to talk to each other in `pelias.json` (see the one in our [dockerfiles setup](https://github.com/pelias/dockerfiles/blob/master/pelias.json#L23-L31) for an example).

The libpostal service comes from https://github.com/whosonfirst/go-whosonfirst-libpostal so you can see the instructions on setting it up there.

Docker is just a way to run those services that also provides a lot of protection against variations in your local setup that can cause issues. And docker-compose (separate tool, a little confusing), is a really nice way to run multiple docker containers in concert. I would definitely advise trying it out.

**Comment by kylebarron** [comment]
I think I misunderstood and expected that `npm install` on the master branch would automatically set up a libpostal docker container for me.

Thanks a ton for your help. I got Pelias working _with_ libpostal on my personal computer when I was able to install libpostal into `/usr/local/lib`, so it might just be easiest for me to ask my sysadmin to install libpostal there.
