### ISSUE TITLE
Wrong data returned?

### ISSUE THREAD

**Issue by Binternet** [pelias/api#1103]
I'm sending a query to `http://my-ip-here:9200/pelias?text=query_here`

And i'm getting a long response which looks like a schema description:

```
{
    "pelias": {
        "aliases": {},
        "mappings": {
            "macrohood": {
                "dynamic": "true",
                "_all": {
                    "enabled": false
                },
                "_source": {
                    "excludes": [
                        "shape",
                        "phrase"
                    ]
                },
   ...
}
```

**Comment by missinglink** [comment]
Hey @Binternet you might be getting confused between the elasticsearch service which runs on port `9200` and [pelias/api](https://github.com/pelias/api) which usually runs on port `3100`.

For queries directly to elasticsearch on port `9200` you'll need to consult the [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/index.html) for a list of available functions.

You are probably looking to do a query such as `http://localhost:9200/pelias/_search?q=query_here` which uses the [URI search](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-uri-request.html) API from elasticsearch.

Querying via the querystring is pretty limiting and I'd suggest using the json query syntax for complex queries, there's also a great plugin called 'sense' that makes querying elasticsearch easier.

If you're running the `pelias/api` code on port `3100` then we have an API called 'search' which can be queried with a similar syntax to what you described: `/v1/search?text=`

**Comment by Binternet** [comment]
Oh right, I was querying elasticsearch and not the API, thank you for clarifying!
