### ISSUE TITLE
Missing pelias.json?

### ISSUE THREAD

**Issue by Binternet** [pelias/api#1118]
I'm trying to run the `api` as a container but when I use the container's bash to view pelias.json its empty, should I `ADD` the file via `Dockerfile` ?

**Comment by Joxit** [comment]
Yes, or mount a volume (with docker run -v or in docker-compose like [pelias/dockerfiles/docker-compose.yml#L28](https://github.com/pelias/dockerfiles/blob/f6aa6beef1cb6f5e11544c66e754b79169bacf04/docker-compose.yml#L28))

**Comment by Binternet** [comment]
Thanks
