### ISSUE TITLE
Structured api shouldn't parse "region" into "state"

### ISSUE THREAD

**Issue by thucnc** [pelias/api#1119]
Given the structured geocoding request, such as `http://pelias.github.io/compare/#/v1/search/structured%3Faddress=460%2520D%25C6%25B0%25E1%25BB%259Dng%2520Kim%2520Giang&county=Thanh%2520Tri&region=Ha%2520Noi` where 'HaNoi' is specified as a region.
However, the api returns the result where 'HaNoi' is parsed into a state.
```
{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://pelias.mapzen.com/v1/attribution",
    "query": {
      "parsed_text": {
        "county": "Thanh Tri",
        "state": "Ha Noi",
        "number": "460",
        "street": "Dường Kim Giang"
      },
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": true
      },
      "querySize": 20
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1523262219266
  },
```

**Comment by Joxit** [comment]
In fact, here, regions and states are synonyms.
> Regions are normally the first-level administrative divisions within countries, analogous to states and provinces in the United States and Canada, respectively, though most other countries contain regions as well.

From this [link](https://github.com/pelias/documentation/blob/master/structured-geocoding.md#region)

**Comment by orangejulius** [comment]
That's correct. I believe we use `state` because that's what libpostal uses. Libpostal should probably be updated to use a more generic term.

**Comment by thucnc** [comment]
Thanks for your clarification. Because all results only list out region, not state, hence confused me.
