### ISSUE TITLE
Add boundary.country parameter to /search and /reverse endpoints

### ISSUE THREAD

**Issue by missinglink** [pelias/api#112]
The geometry of some country polygons makes it difficult to use bbox filtering to exclude neighbouring nations.

It would be nice to have an API param called `alpha3` or similar which excluded results from outside that country.

When used in combination with a coarse geocoder it would be very easy to create a coarse search for a single country using the mapzen service.

**Comment by missinglink** [comment]
oh my bad, this is a dupe of https://github.com/pelias/api/issues/44 and so we could only do this for `/search` endpoints until `es@2.0`

**Comment by dianashk** [comment]
+1 for filtering by country name or code from a potential pelias partner

let's try to get this on-deck in the near future

**Comment by missinglink** [comment]
It would be interesting to expand this out to become a more generic strict (boolean MUST, exact matching) filter.

example: something like `/endpoint?filter=alpha3:GBR&filter=admin1:Hackney`

**Comment by dianashk** [comment]
On hold until after API-redesign discussion.
