### ISSUE TITLE
API (possibly express) swallows runtime exceptions

### ISSUE THREAD

**Issue by sevko** [pelias/api#114]
The API appears to silently swallow runtime exceptions that would otherwise cause it to print a stack trace and crash. For instance, I've changed [query/search.js:17] (https://github.com/pelias/api/blob/master/query/search.js#L17) from:

```javascript
var query = queries.distance( centroid, { size: params.size } );
```

to

```javascript
var query = queries.distance( centroid, { size: param.size } );
```

Note that `params.size` became `param.size`, and, because `param` doesn't exist, you'd expect the process to crash with `ReferenceError: param is not defined`. When running the API via `node index.js`, however:

```
$ curl localhost:3100/search?input=foobar
{"error":{}}
```

The request obviously errored and the status code is 500, yet the API keeps running without any output besides `listening on 3100`. If you try to use the `query/search` module *directly*, on the other hand, it errors as expected:

```javascript
$ node -e 'console.log(require("./query/search")({}));'
/home/sevko/src/mapzen/api/query/search.js:17
  var query = queries.distance( centroid, { size: param.size } );
                                                  ^
ReferenceError: param is not defined
    at generate (/home/sevko/src/mapzen/api/query/search.js:17:51)
    at [eval]:1:38
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
```

**Comment by missinglink** [comment]
Not crashing is certainly the desired behaviour, :+1: for adding some terminal logging. 

There are a couple of error middlewares set up already:
https://github.com/pelias/api/blob/master/app.js#L56
https://github.com/pelias/api/blob/master/middleware/500.js

@sevko would you like to have a crack at this ticket in the API? it would simply require adding a new [error middleware](http://expressjs.com/guide/error-handling.html) (a function with 4 arguments not 3 args like the controller middleware) which logs the error, it should be inserted [before the other error middleware](https://github.com/pelias/api/blob/master/app.js#L54) and **must** call `next()` else the 500 middleware will no longer get a chance to run.
