### ISSUE TITLE
Add timestamp of last update to POIs

### ISSUE THREAD

**Issue by dianashk** [pelias/api#120]
It would be helpful to send back last update timestamps where available from source data.

**Comment by missinglink** [comment]
would this be `last import time of the record`, `last import job end time for the layer` or when you say `'source data'` do you mean like `last edited in osm datestamp`?

we don't currently update records, so the `created` date will always equal the `last_updated` date in elasticsearch.

see this issue for a discussion on reverse-proxy caching https://github.com/pelias/api/issues/23
