### ISSUE TITLE
libpostal parsing issue

### ISSUE THREAD

**Issue by missinglink** [pelias/api#1210]
/v1/search?text=1800 SE MLK Bldv, OR

```
      "parsed_text": {
        "number": "1800",
        "street": "se mlk",
        "city": "bldv",
        "state": "or"
      }
```

**Comment by missinglink** [comment]
Actually on closer inspection, the abbreviation should be `Blvd` not `Bldv`

**Comment by orangejulius** [comment]
It's another mark against libpostal that any spelling error leads to an invalid parse :(
