### ISSUE TITLE
API not calling Interpolation service

### ISSUE THREAD

**Issue by jenPlusPlus** [pelias/api#1241]
I have [installed Pelias from scratch](https://github.com/pelias/documentation/blob/master/pelias_from_scratch.md) (NOT using Docker). When using the API, I'm getting results using Placeholder and Libpostal, but not Interpolation. I'm not using PIP. I'm also not using TIGER data in Interpolation, so I skipped all the TIGER instructions. 

I've downloaded & imported data and installed and started all the services. When I start the Pelias API with `npm start`, my terminal indicates Interpolation has started on localhost:3000, which is correct for my configuration.

<img width="946" alt="screen shot 2018-11-16 at 1 56 15 pm" src="https://user-images.githubusercontent.com/6845268/48646902-736af600-e9a7-11e8-9921-72d3c5094ab2.png">

I can use the Interpolation command line tool to get results.
<img width="1262" alt="screen shot 2018-11-16 at 2 20 32 pm" src="https://user-images.githubusercontent.com/6845268/48647994-f17ccc00-e9aa-11e8-9d0a-9167ce12fb01.png">

I can use Interpolation in the browser at localhost:3000 to get results.
<img width="813" alt="screen shot 2018-11-16 at 2 19 14 pm" src="https://user-images.githubusercontent.com/6845268/48648159-97c8d180-e9ab-11e8-9b0a-08b66aebc517.png">

I see feedback in the terminal when I do so. 
<img width="1259" alt="screen shot 2018-11-16 at 2 19 43 pm" src="https://user-images.githubusercontent.com/6845268/48648029-140ee500-e9ab-11e8-84f8-1b0dfe9283e4.png">

So, I feel like the Interpolation service is set up correctly. Pelias just isn't finding it. 

In my terminal, I have tabs running Placeholder, Libpostal, Interpolation, and the API (and also ElasticSearch). When I go to localhost:3100 (Pelias API) and submit a query, I do get results, and I see feedback in the tabs for Placeholder, Libpostal, and the API, but not for Interpolation. It's as if the service isn't hit at all.

Why doesn't the Pelias API recognize the Interpolation service?

Below is my pelias.json:

```
{
    "esclient": {
      "apiVersion": "2.4",
      "keepAlive": true,
      "requestTimeout": "120000",
      "hosts": [{
        "env": "development",
        "protocol": "http",
        "host": "localhost",
        "port": 9200
      }],
      "log": [{
        "type": "stdio",
        "json": false,
        "level": [ "error", "warning" ]
      }]
    },
    "elasticsearch": {
      "settings": {
        "index": {
          "number_of_replicas": "0",
          "number_of_shards": "5",
          "refresh_interval": "1m"
        }
      }
    },
    "dbclient": {
      "statFrequency": 10000
    },
    "api": {
      "accessLog": "common",
      "textAnalyzer": "libpostal",
      "host": "http://pelias.mapzen.com/",
      "indexName": "pelias",
      "version": "1.0",
      "services": {
        "placeholder": {
          "url": "http://localhost:4100"
        },
        "libpostal": {
          "url": "http://localhost:8080"
        },
        "interpolation": {
          "url": "http://localhost:3000"
        }
      },
      "targets": {
        "auto_discover": false,
        "canonical_sources": ["whosonfirst", "openstreetmap", "openaddresses", "geonames"],
        "layers_by_source": {
          "openstreetmap": [ "address", "venue", "street" ],
          "openaddresses": [ "address" ],
          "geonames": [
            "country", "macroregion", "region", "county", "localadmin", "locality", "borough",
            "neighbourhood", "venue"
          ],
          "whosonfirst": [
            "continent", "empire", "country", "dependency", "macroregion", "region", "locality",
            "localadmin", "macrocounty", "county", "macrohood", "borough", "neighbourhood",
            "microhood", "disputed", "venue", "postalcode", "continent", "ocean", "marinearea"
          ]
        },
        "source_aliases": {
          "osm": [ "openstreetmap" ],
          "oa":  [ "openaddresses" ],
          "gn":  [ "geonames" ],
          "wof": [ "whosonfirst" ]
        },
        "layer_aliases": {
          "coarse": [
            "continent", "empire", "country", "dependency", "macroregion", "region", "locality",
            "localadmin", "macrocounty", "county", "macrohood", "borough", "neighbourhood",
            "microhood", "disputed", "postalcode", "continent", "ocean", "marinearea"
          ]
        }
      }
    },
    "schema": {
      "indexName": "pelias"
    },
    "logger": {
      "level": "debug",
      "timestamp": true,
      "colorize": true
    },
    "acceptance-tests": {
      "endpoints": {
        "local": "http://localhost:3100/v1/",
        "dev-cached": "http://pelias.dev.mapzen.com.global.prod.fastly.net/v1/",
        "dev": "http://pelias.dev.mapzen.com/v1/",
        "prod": "http://search.mapzen.com/v1/",
        "prod-uncached": "http://pelias.mapzen.com/v1/",
        "prodbuild": "http://pelias.prodbuild.mapzen.com/v1/"
      }
    },
    "imports": {
      "adminLookup": {
        "enabled": true,
        "maxConcurrentRequests": 100,
        "usePostalCities": false
      },
      "blacklist": {
        "files": []
      },
      "geonames": {
        "datapath": "/Users/jenwoodson/repos/dps-geocoder/data/mnt/pelias/geonames/data",
        "countryCode": "US"
      },
      "openstreetmap": {
        "datapath": "/Users/jenwoodson/repos/dps-geocoder/data/mnt/pelias/openstreetmap",
        "leveldbpath": "/tmp",
        "import": [{
          "filename": "colorado-latest.osm.pbf"
        }]
      },
      "openaddresses": {
        "datapath": "/Users/jenwoodson/repos/dps-geocoder/data/mnt/pelias/openaddresses/us/co",
        "files": ["denver.csv"]
      },
      "polyline": {
        "datapath": "/Users/jenwoodson/repos/dps-geocoder/data/mnt/pelias/polyline",
        "files": ["co.polylines"]
      },
      "whosonfirst": {
        "datapath": "/Users/jenwoodson/repos/dps-geocoder/data/mnt/pelias/whosonfirst",
        "importVenues": false,
        "importPostalcodes": false,
        "importPlace": 102086135
      }
    }
  }
```

Beginning of Output from Pelias API:
<img width="540" alt="screen shot 2018-11-16 at 2 34 55 pm" src="https://user-images.githubusercontent.com/6845268/48648605-44f01980-e9ad-11e8-991d-bba8c6d8bede.png">

**Comment by missinglink** [comment]
We currently duplicate all openstreetmap and openaddresses addresses in both the interpolation service and in elasticsearch.

The interpolation service is currently only set up for a scenario where you are using the `/v1/search` endpoint and you search for an address by inputting both a house number and a street name.

If the address is found in elasticsearch then it's simply returned, otherwise, the main search query 'falls back' to returning the street centroid from the 'streets' layer, then we also query the interpolation service for a better match on that street.

I suspect your issue is because you are not importing the street centroids using the `pelias/polylines` importer?

**Comment by missinglink** [comment]
The reason I suspect that's the case is because your query is falling all the way back to the locality.

Can you please confirm that you h

**Comment by orangejulius** [comment]
Hey @jenPlusPlus,
Just wanted to say Peter is probably right. It looks like the street records from the polyline importer aren't there, although I see from your `pelias.json` it looks set up correctly.

The only other thing I can think of is that there's an issue in the street from OSM itself, but looking at [1540 Yates St](http://pelias.github.io/compare/#/v1/search%3Ftext=1540%20yates%20street,%20denver,%20co) in one of our full planet builds, all looks well. So hopefully you can get it working.

By the way if you're working with Matt B over at DPS, tell him I said hi!

**Comment by jenPlusPlus** [comment]
@missinglink I'm not using the Docker set up simply because I'm not familiar with Docker. I had set up Pelias without it previously, but I had omitted the Interpolation service in that set up. 

You and @orangejulius were correct. The polylines were not imported. I did run the importer during initial set up, but it must have failed without my noticing. I ran it successfully this morning, and all is well! Thank you both for your help. 

As a side note, while trying to debug this, I found that [./service/configurations/Interpolation.js](https://github.com/pelias/api/blob/master/service/configurations/Interpolation.js#L8) is defining the class as Language, not Interpolation. If it should actually be Interpolation, I'm happy to submit a quick PR. Thank you again!

**Comment by missinglink** [comment]
Glad you got it working.

Good catch, that's a copy pasta typo. We'd be happy to merge a PR to fix it.

**Comment by srflaxu40** [comment]
I'm getting the same issue.  Do I have to import all data at the same time? It seems no polyline features are being returned for us:

```
  1 {
  2   "esclient": {
  3     "apiVersion": "5.6",
  4     "keepAlive": false,
  5     "requestTimeout": "120000",
  6     "hosts": [{
  7       "host": "127.0.0.1",
  8       "port": 9200
  9     }]
 10   },
 11   "schema": {
 12     "indexName": "pelias"
 13   },
 14   "imports": {
 15     "polyline": {
 16       "datapath": "/Users/jknepper/polylines/",
 17       "files": [ "new-york-latest.osm.polylines" ]
 18     }
 19   }
 20 }
 21 
 22 
```
Data gets imported but then nothing is returned from openstreetmap or interpolation.  It seems interpolation service isn't hit?
