### ISSUE TITLE
Add a switch to always return categories

### ISSUE THREAD

**Issue by NickStallman** [pelias/api#1271]
It would be useful in some cases to be able to return the categories in the results.
For example an autocomplete that shows a little icon or label next to each result to visually show the category.

The category is currently being returned but only if the category is being filtered.
E.g. adding ?category=transport to the query returns all the categories, but it appears to be impossible to access them otherwise.

This is handled by helper/geojsonify_place_details.js
```
function checkCategoryParam(params) {
  return _.isObject(params) && params.hasOwnProperty('categories');
}
```

I did find a very old ticket #118 which mentions returning the category if the details flag is true, however this flag doesn't seem to exist anymore?

Was that flag deliberately removed? Is there any specific reason why a similar flag couldn't be added to request all information to be in the results?

**Comment by missinglink** [comment]
I did a bunch of work on this back in 2015 and the idea was that the taxonomy would be independently reviewed because it would end up becoming part of our public API, meaning that removing categories would break integrations.

That review never happened and so the feature was kind of 'dark launched', it's there but it's not really apparent that it's there.

Here's my evaluation from that time of other taxonomies which led to the structure we have now.

https://github.com/pelias/pelias/wiki/Taxonomy-v1

What are your thoughts on this? How would you feel about this being potentially unstable of we decided to remove a category?

**Comment by orangejulius** [comment]
We have https://github.com/pelias/api/pull/1068 from a while back that proposes to fix this same thing.

I agree with @missinglink that at the current moment this is at best an alpha or beta feature, and we need to be careful to avoid committing to response content that we aren't sure we want permanent. 

On the other hand with that attitude we will likely never make progress unless there is a massive change in the prioritization of more work on categories. I would support updating the PR above to use a `pelias.json` config flag to enable category output. That would actually set us up for being able to disable categories at the schema level as well, saving space in Elasticsearch for those who aren't yet using it.

**Comment by NickStallman** [comment]
I think the feature won't get much love while it's in this sort if 'there but not there' state.
As-is I think it's reasonably useful, in the context I'm looking at as an enhancement for an autocomplete that includes venues.

I think anyone seriously wanting to use the categories in production will likely maintain their own mapping file, possibly with some tweaks.
E.g. you can find my tweaks here: https://github.com/NickStallman/openstreetmap/blob/master/config/category_map.js
For my purposes I expanded upon education to separate actual schools/universities from libraries and museums and I've done some refinements to public transport which was a bit inconsistent with many things just being stuck with 'transport'. It's a work in progress of course.

As long as the categories API doesn't change significantly without warning it looks good for production use. The mapping can be changed reasonably freely and I'll just keep my own copy for example.

The main constraints with the current categories code are:
- Can't match multiple tags, I hit this issue with my venue name normalisation code. It's not such a big issue with the categories but it could be slightly limiting.
- No multi-pass categorisation. E.g. in the Taxonomy v1 doc it mentions prioritisation of "Central Station". You could do that easily and reliably by counting the number of platforms in a station but that would require multiple passes.
But in general I think it works perfectly well for a v1.

A flag either in the query string, or in pelias.json would be great for this. Technically not all queries would want category data in the output but since it's 'free' with no extra processing required a few bytes extra in the output isn't a big deal.
If the flag (or another flag) turns off processing entirely that would also be fine although I'm not sure of a use case where you'd have venues on but not want categories at all to save a few MB of space. :)

**Comment by missinglink** [comment]
I would be fine with introducing a query parameter which enabled/disabled the categories in the response geojson independently of whether the `?categories=` flag is being used to filter.

For the sake of simplicity, I'd suggest `?categories=true` being a special value which enables this functionality, thoughts?

**Comment by NickStallman** [comment]
Yeah ?categories or ?categories= or ?categories=true would all be great.
I did actually try that but currently a blank value just throws an error. :)

**Comment by NickStallman** [comment]
Hey presto. https://github.com/pelias/api/issues/1271
