### ISSUE TITLE
Two-letter country codes in the output

### ISSUE THREAD

**Issue by clupasq** [pelias/api#1275]
The output of `/v1/reverse` and `/v1/autocomplete` contains country codes.
These are present in the `country_a` field and are three-letter codes.

Is it possible to return two-letter country codes instead?

**Comment by orangejulius** [comment]
Hi @clupasq,
Pelias can only return three-letter country codes. There are tools for converting between two and three letter codes in many programming languages, let us know if you need some recommendations.
