### ISSUE TITLE
filter /search by categories

### ISSUE THREAD

**Issue by sevko** [pelias/api#128]
Extend the search logic added in #115 , which added support for filtering `/reverse` results by record category, to `/search` and `/suggest`.

**Comment by missinglink** [comment]
adding the categories to `/search` is difficult yet possible, have a read of this comment https://github.com/elastic/elasticsearch/issues/6444#issuecomment-64408912

**Comment by missinglink** [comment]
this is quite interesting as a opportunity to refactor the 'admin' (coarse) and 'address' query aliases to use categories, meaning we would no longer have to hard-code which datasets contained which data

**Comment by riordan** [comment]
A category may be combined with a `/search?text` so a user could search for `category=bank` and `text=wells fargo`.

**Comment by orangejulius** [comment]
Updating the title as we only want /search to accept the categories parameter (extra parameters on /suggest reduces the effectiveness of caching).

**Comment by riordan** [comment]
Hold for epic: pelias/pelias#150
