### ISSUE TITLE
Categories feature broken for autocomplete

### ISSUE THREAD

**Issue by missinglink** [pelias/api#1282]
It appears that the categories feature isn't working quite right for autocomplete.

We've been getting more requests related to categories recently so it might pay to investigate and fix the bugs.

Eg: `/v1/autocomplete?categories=transport&text=good` returns `admin` places which do not have the `transport` category associated.

I also noticed that the PR I merged recently to always show categories in the geojson when the param is specified doesn't seem to be consistent between search and autocomplete

**Comment by missinglink** [comment]
Related https://github.com/pelias/api/pull/1273

**Comment by orangejulius** [comment]
This turned out to be because we hadn't deployed #1273 to geocode.earth yet. It all looks good now.
