### ISSUE TITLE
Search: confidence is 0.6 although data resides in elasticsearch; "layers" and "sources" ignored

### ISSUE THREAD

**Issue by dr0i** [pelias/api#1309]
I've set up pelias/docker. When searching addresses many results in inaccurate results (confidence 0.6). Like:
`curl -G 0.0.0.0:4000/v1/search --data-urlencode "layers=venue,street,address"  --data-urlencode "sources=osm" --data-urlencode "text=Zentralplatz 2, 56068 Koblenz,  DE"`

where the parsing is very good:

    "query": {                                                                                            
      "parsed_text": {                                                                                    
        "country": "DEU",                                                                                 
        "county": "koblenz",                                                                              
        "city": "koblenz",                                                                                
        "postalcode": "56068",                                                                            
        "number": "2",                                                                                    
        "street": "zentralplatz"
     "layers": [
        "venue",
        "street",
        "address"
      ],
      "sources": [
        "openstreetmap"
      ],
the first result is way too broad

    "properties" : {
        "label": "Koblenz, Germany"` 
        "source": "whosonfirst",                                                                          
        "layer": "locality", 
        "confidence": 0.6,
        "accuracy": "centroid"

Strange is
1. although the `layer=locality` is explicitly _not_ set , it _is_ used.
2. same for `sources`
3. the data _exists_ more accurate in elasticsearch:

`curl 0.0.0.0:9200/pelias/_search?q=Zentralplatz%201%2056068%20Koblenz `
=>

    "center_point": {
         "lon": 7.595598,
         "lat": 50.358227
       },
          "name": {
           "default": "2 Zentralplatz"
          },
          "address_parts": {
            "number": "2",
            "street": "Zentralplatz",
            "zip": "56068"
          },
          "source": "openstreetmap",
          "source_id": "way/90135666",
          "layer": "address"
        }

I  don't think this is docker-specific,  though here is some `docker` output:
>    $ pelias compose ps
        Name                     Command              State               Ports           
------------------------------------------------------------------------------------------
> pelias_api             ./bin/start                    Up       0.0.0.0:4000->4000/tcp     
pelias_csv_importer    /bin/bash                      Exit 0                              
pelias_elasticsearch   /bin/bash bin/es-docker        Up       0.0.0.0:9200->9200/tcp,    
                                                               0.0.0.0:9300->9300/tcp     
pelias_fuzzy_tester    ./bin/fuzzy-tester --help      Exit 0                              
pelias_geonames        /bin/bash                      Exit 0                              
pelias_interpolation   ./interpolate server /data     Up       0.0.0.0:4300->4300/tcp     
                       ...                                                                
pelias_libpostal       ./bin/wof-libpostal-server     Up       0.0.0.0:4400->4400/tcp     
                       ...                                                                
pelias_openaddresses   /bin/bash                      Exit 0                              
pelias_openstreetmap   /bin/bash                      Exit 0                              
pelias_pip-service     ./bin/start                    Up       0.0.0.0:4200->4200/tcp     
pelias_placeholder     ./cmd/server.sh                Up       0.0.0.0:4100->4100/tcp`

and my [pelias.json](https://github.com/hbz/pelias-docker/blob/lobid-organisations/projects/lobid_DACH/pelias.json)

**Comment by orangejulius** [comment]
Hi @dr0i,
Thanks for the interesting report with lots of good data.

Did you disable `adminLookup` when running your build? I'm not sure if you posted the full output from querying elasticsearch directly, but there should be some `parent` fields with text for the city, country, etc.

This query works in our compare app, so it could be a data issue, a config issue, or possibly an issue with the API version you're using, so please share that as well:

[/v1/search?layers=venue,street,address&sources=osm&text=Zentralplatz 2, 56068 Koblenz, DE](https://pelias.github.io/compare/#/v1/search%3Flayers=venue,street,address&sources=osm&text=Zentralplatz%202,%2056068%20Koblenz,%20DE)
![Screenshot_2019-06-04_10-19-35](https://user-images.githubusercontent.com/111716/58886637-43b8dc80-86b2-11e9-92b6-e49766917e65.png)

**Comment by dr0i** [comment]
Indeed, the`parent` field is missing for type `venue` and `address`. So this should be the root of the problem I guess - thx for pinning that!
The `parent` exists for broader areas like `locality`, though.

In `pelias.json` the `admin-lookup` is configured like this:

> imports.adminLookup.enabled: true

At [wof-admin-lookup](https://github.com/pelias/wof-admin-lookup#configuration) it's said to configure `imports.services.pip` where I only configured `api.services.pip` (as it's done in the [docker examples](https://github.com/pelias/docker/blob/master/projects)).
If this is the dichotomy between in-memory (wof importing files) and service-lookup (using import.service.pip) and since it's recommended to use the service, why not:

- [ ] update the docker-examples to use the recommended way of lookup admin data ?

However, should I do this:

- [ ] should `pip` also be configured at the import-level?

Also, like in the examples I configured:

> whosonfirst.importVenues:false

- [ ] should `importVenues` be set to `true`?

If I get this right, `wof` uses `pip`, and the latter gives good results when lookup the geo data in question like:

> curl "0.0.0.0:4200/7.595598/50.358227"

while the `interpolation` service doesn't know of `Zentralplatz`:
> curl "0.0.0.0:4300/street/near/geojson?lon=7.595598&lat=50.358227"

`interpolation` knows surrounding streets but not the "Zentralplatz" itself. However I don't think this is important because `pip` is doing well when querying the same lon/lat, right?

Also, I may have done this wrong: pelias/interpolations says to configure it like:

> imports.interpolation.download.tiger.datapath:$path

and I did:

> interpolation.datapath:$path

to use whatever `street.db` or `address.db` (tiger not needed. See also this [question on SO](https://stackoverflow.com/questions/49070979/how-can-i-configure-the-interpolation-for-a-self-hosted-instance-of-pelias).

Just discovered that my `wof`-data is more then a year old, but then this data worked for me back then, (using pelias without docker). You haven't changed anything considering that *csv structure, I guess. May  be worth looking into that sqlite thing, too.

Re version:
Querying the api results in

> geocoding.version:0.2

using pelias/docker:master from mid of May.

**Comment by dr0i** [comment]
After getting some more data (surely not the crucial point here), renaming some filenames of the old data (because pelias changed the file-pattern for some sources last year or so), tweaking `pelias.json` a bit (e.g. configuring `pip` also be  at the import-level) and reindexing everything anew, the `parent` field is in elasticsearch, thus the "Zentralplatz"-query yields an `"match_type": "exact"`. Don't know what the _exact_ problem was, but now: Yeah!
@orangejulius thx again for the very nice support and a great product!
