### ISSUE TITLE
search only street name from extract.0sv without housenumber

### ISSUE THREAD

**Issue by stefanocudini** [pelias/api#1310]
After the import of my road network, a file generated by pelias / polylines I can't find the name of the street without housenumber.

I did not understand how names are treated and where are these street names stored?

Can I filter only by street name?
is it possible to do a limited search for street names imported from file extract.0sv ??
I noticed that after importing openaddresses they are not used in search results only street column from openaddresses source if indexed

**Comment by missinglink** [comment]
Streets imported from the polyline format (.0sv) are stored in the `street` layer in Pelias.

If you add `?layers=street` to your query you should be able to find them. Eg `/v1/search?layers=street&text=main street`

**Comment by stefanocudini** [comment]
I was trying to get the name of a street without a house number in the `api?autocomplete` but it only returns address .. even if I just modified the customBoosts ptutting priority to _street_ layer.
Is this behavior normal?

**Comment by missinglink** [comment]
You can inspect elasticsearch directly to see which documents have been imported, it is running on port `9200`.

> http://localhost:9200/pelias/street/_search

The url above should return all `street` documents in your elasticsearch index, the `hits.total` number reflects the total number of streets.
