### ISSUE TITLE
[question] tokens being stripped from input

### ISSUE THREAD

**Issue by missinglink** [pelias/api#132]
It seems like the token `street` is being stripped from the input text, or the inverse document frequency is playing some part in the following 2 queries returning the same results:

http://pelias.mapzen.com/search?input=church&lat=-40&lon=175
http://pelias.mapzen.com/search?input=church%20street&lat=-40&lon=175

ref: http://pelias.mapzen.com/search?input=church%20street&lat=-40.95&lon=175.66
(lat/lon closer to the actual street returns the records I was expecting)

**Comment by missinglink** [comment]
The issue here is not that the `street` token is being stripped but that the `lat/lon` bias being used is sorting results by their geographic distance from the centroid rather than their linguistic similarity.

simply put `8 Churchill Crescent` is closer to `175,-40` than `2 Church Street`

**Comment by dianashk** [comment]
Please add acceptance-tests to verify it being fixed.
