### ISSUE TITLE
Flip street name and number for Hungarian addresses

### ISSUE THREAD

**Issue by laszbalo** [pelias/api#1343]
Hi,

just reading through the source code for some post-processor and found [here](https://github.com/pelias/api/blob/master/middleware/localNamingConventions.js#L5) that you flip the street number and address for some country.

FYI, Hungary should be on that list as well.

The first line of my address is:  `István király utca 14` (King Stephan street 14)

Also, would it not be possible to just get the list of those countries from some data source?

**Comment by missinglink** [comment]
We could probably use this config file from the 'ID Editor' https://github.com/openstreetmap/iD/blob/master/data/address-formats.json

**Comment by missinglink** [comment]
That config doesn't actually have Hungary listed, any idea why that might be @laszbalo ?

**Comment by missinglink** [comment]
resolved in https://github.com/pelias/api/pull/1344
