### ISSUE TITLE
details param not working as expected

### ISSUE THREAD

**Issue by missinglink** [pelias/api#135]
There seems to be an issue with how the details param is currently being handle in production.

My understanding is that `details` should be **off** by default and the additional fields can be enabled by passing either `?details=1` or `?details=true` in the query string.

what's currently happening in production is:

| Expected        | Actual           | Url  |
|:-------------:|:-------------:|:-----|
| off | on | http://pelias.mapzen.com/search?input=a |
| on | off | http://pelias.mapzen.com/search?input=a&details=1 |
| on | on | http://pelias.mapzen.com/search?input=a&details=true |
| off | off | http://pelias.mapzen.com/search?input=a&details=false |

The last url `details=false` is also confusing it that it disables all the `admin`/`alpha3` fields as well as those that are added when using `details=true`.

**Comment by dianashk** [comment]
We agreed on the default being set to `details`=`true`. There is a but however when using 1 instead of true. Will fix.
