### ISSUE TITLE
template query

### ISSUE THREAD

**Issue by missinglink** [pelias/api#136]
consider using https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-template-query.html to move the query templates from `elasticsearch-backend` in to `scripts`.

**Comment by orangejulius** [comment]
Now that we have the [query module](https://github.com/pelias/query), I doubt we'll move to this soon. But if it ever is helpful for say, performance, to move the templating into Elasticsearch, we can look into it again. Elasticsearch 2.3 still has [templates](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-template.html#pre-registered-templates)
