### ISSUE TITLE
/search doesn't return name fields that may have been matched by query

### ISSUE THREAD

**Issue by dianashk** [pelias/api#137]
Although we match on all name.\* fields only name.default is returned to the user and displayed in the front-end.

in effect this means that a record like [1] which has the following tags will be searchable via the russian name but will return the english name to the user:

{
  'name': 'Trafalgar Square',
  'name:ru': 'Трафальгарская площадь'
}
the above is not too big a deal as we are providing an english-only service at the moment; there are also examples like the mayor's office in london [2] with the following tags:

{
  'name': '30 St Mary Axe',
  'loc_name': 'The Gherkin'
}
the building itself it called '30 St Mary Axe' but absolutely everyone affectionately refers to it as 'The Gherkin' [3], so if you searched for 'The Gherkin', your result would match and return '30 St Mary Axe'.

/suggest already has the same behaviour here: https://pelias.mapzen.com/suggest?input=The%20Gherkin&lat=51.53177&lon=-0.06672&size=10&zoom=18

[1] https://www.openstreetmap.org/relation/3962877
[2] https://www.openstreetmap.org/way/4959489
[3] gherkin

**Comment by vesameskanen** [comment]
This problem is addresses by PR https://github.com/pelias/api/pull/501. There is a new module ''middleware/matchLanguage', which checks which 'language' was matched best.
