### ISSUE TITLE
unicode normalisation form

### ISSUE THREAD

**Issue by missinglink** [pelias/api#1375]
Following on from https://github.com/pelias/api/pull/1373 I noticed that elasticsearch uses the `NFKC` mode whereas we use the `NFC`mode.

I'm not sure if this is a big deal in practice but I'm curious if we should follow suit, or adversely if we should reconfigure our character filters in `pelias/schema` to use `NFC`.

If anyone out there has more experience I'd be interested to hear from you!

```js
'o\uFB03ce'.normalize('NFC').split('')
(4) ["o", "ﬃ", "c", "e"]

'o\uFB03ce'.normalize('NFKC').split('')
(6) ["o", "f", "f", "i", "c", "e"]
```

> Normalization Form KC does not attempt to map character sequences to compatibility composites. For example, a compatibility composition of “office” does not produce “o\uFB03ce”, even though “\uFB03” is a character that is the compatibility equivalent of the sequence of three characters “ffi”. In other words, the composition phase of NFC and NFKC are the same—only their decomposition phase differs, with NFKC applying compatibility decompositions.

- https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-normalization-charfilter.html
- http://userguide.icu-project.org/transforms/normalization
- https://unicode.org/reports/tr15/

**Comment by Joxit** [comment]
If I'm understanding right,`ﬃ` is a [Stylistic ligatures](https://en.wikipedia.org/wiki/Orthographic_ligature#Stylistic_ligatures) and are often used to solve some style issue.
That means if we have in our data a use of Stylistic ligatures like ﬃ, we should found it with and without the use of the ﬃ character in our ES query.
So I think we should also use NFKC. :thinking:

**Comment by missinglink** [comment]
Interesting, I don't know anything about ligatures, they seem to be relics from the days of printing presses, I guess some are still in use today?

The Wikipedia article you linked is particularly relevant because it has a photo of two street signs with interesting ligature:

```
'straſʒe'.normalize('NFC').split('')
(7) ["s", "t", "r", "a", "ſ", "ʒ", "e"]

'straſʒe'.normalize('NFKC').split('')
(7) ["s", "t", "r", "a", "s", "ʒ", "e"]

'platʒ'.normalize('NFC').split('')
(5) ["p", "l", "a", "t", "ʒ"]

'platʒ'.normalize('NFKC').split('')
(5) ["p", "l", "a", "t", "ʒ"]
```

The "Straße" example is slightly different between normalization forms but the "Platz" one is the same, either way this normalization would be insufficient to allow matching between terms such as "platʒ" and "platz".

**Comment by Joxit** [comment]
Hum, I don't know if it's still used, we can check if defaults keyboards have these letters? This will be fastidious 😅

Yes, and that means also that straſʒe will not match strasse 😕

We should add this normalisation in the parser repository?

**Comment by missinglink** [comment]
So.. regarding the ligatures specifically, I don't think it's a big deal for us.

Walking the streets of Berlin I can confirm that they are indeed very commonly used on street signs.
But! I've never seen them used in electronic data, and I doubt anyone has ever typed them in expecting them to work 🤷‍♂ 

I tried them out in other geocoders and they don't support ligatures, at least not at index-time.
If someone wants to pursue a PR and it's tested I'd be happy to merge it but I think it's as a low priority.

Regarding `NFKC` there must be more to it than just ligatures? I wonder what else is affected?

**Comment by Joxit** [comment]
Ok, you're right, this isn't a big deal.

`NFKC` will also transform exponent to the numeric character.

```js
 '²'.normalize('NFKC').split('')
[ '2' ]

'²'.normalize('NFC').split('')
[ '²' ]
```

**Comment by missinglink** [comment]
Yeah that's nice, so considering that:
1. it doesn't seem to break anything
2. it's what Elasicsearch is doing

... I agree we should change it to 'NFKC'

**Comment by missinglink** [comment]
![IMG_20191106_143846](https://user-images.githubusercontent.com/738069/68303446-301c0280-00a4-11ea-9303-dde26ee58f70.jpg)
