### ISSUE TITLE
logging bug

### ISSUE THREAD

**Issue by missinglink** [pelias/api#1386]
I believe there is a minor bug in our logging code here:
https://github.com/pelias/api/blob/3712ca0198feab93c5ecd96f6f8502e0dfa0da23/controller/search.js#L67

This might have been caused when the log lines were moved higher up in the file above `res.data = docs`.
So the `_.get(res, 'data', []).length` metric likely always returns 0 and should be something like `(res.data||[]).length`

**Comment by orangejulius** [comment]
Yes indeed! Fixed in https://github.com/pelias/api/pull/1388
