### ISSUE TITLE
autocomplete: incorrect terms queries

### ISSUE THREAD

**Issue by missinglink** [pelias/api#1399]
A query such as `/v1/autocomplete?debug=true&layers=country&focus.point.lat=1&focus.point.lon=1&text=a` results in three `terms` queries targeting the `layers`.

As the query was only requesting the `country` layer I would expect that this is the only layer present in the terms queries, but this isn't the case:

```js
{
  "filter": [
    {
      "terms": {
        "layer": [
          "venue",
          "street",
          "country",
          "macroregion",
          "region",
          "county",
          "localadmin",
          "locality",
          "borough",
          "neighbourhood",
          "continent",
          "empire",
          "dependency",
          "macrocounty",
          "macrohood",
          "microhood",
          "disputed",
          "postalcode",
          "ocean",
          "marinearea"
        ]
      }
    },
    {
      "terms": {
        "layer": [
          "country"
        ]
      }
    },
    {
      "bool": {
        "minimum_should_match": 1,
        "should": [
          {
            "terms": {
              "layer": [
                "venue",
                "country",
                "macroregion",
                "region",
                "county",
                "localadmin",
                "locality",
                "borough",
                "neighbourhood",
                "continent",
                "empire",
                "dependency",
                "macrocounty",
                "macrohood",
                "microhood",
                "disputed",
                "postalcode",
                "ocean",
                "marinearea"
              ]
            }
          },
          {
            "geo_distance": {
              "distance": "100km",
              "distance_type": "plane",
              "center_point": {
                "lat": 1,
                "lon": 1
              }
            }
          }
        ]
      }
    }
  ]
}
```

in `/v1/search` equivalent works as expected:

```js
{
  "filter": [
    {
      "terms": {
        "layer": [
          "country"
        ]
      }
    }
  ]
}
```

**Comment by orangejulius** [comment]
This is expected, if a bit confusing and possibly redundant.

The other two filters are coming from the [address layer filter](https://github.com/pelias/api/blob/master/sanitizer/_address_layer_filter.js) and the other from the [focus point distance filter](https://github.com/pelias/api/blob/master/query/view/focus_point_distance_filter.js).

Elasticsearch should be reasonably efficient at managing these 3 filters, and we risk changing the behavior of queries if we try too hard to combine them as one. So I think this is working how we want.

**Comment by missinglink** [comment]
Hmm yeah I agree combining them in to one would be difficult but I don't think the geo_distance query is working as expected?

My request only asked for the country layer.

My understanding is that the filter conditions are computed *independently* before being combined via set intersection, so the geo_distance query is doing a lot more work than required only to be discarded once intersected with the filter above?

**Comment by missinglink** [comment]
I'm going to close this, it looks bad but on reflection, it's probably ok how it is.
