### ISSUE TITLE
libpostal parser on autocomplete?

### ISSUE THREAD

**Issue by kmadenski** [pelias/api#1413]
Hey team! 

Thanks to @missinglink i get amazing [example](https://pelias.github.io/compare/#/v1/search%3Ftext=Kaschk,%20Berlin) of pelias power. 

I play my pelias stack based on [https://github.com/pelias/docker](docker)

I have question about libpostal parser with autocomplete.

It is possible to use libpostal parser on **autocomplete**? I got always default "pelias" parser, but on **search** its work ok for same request.

**Comment by missinglink** [comment]
No, this is not possible, the `libpostal` parser is not capable of parsing incomplete input.

**Comment by missinglink** [comment]
Have a look at the 'debug' output for `/v1/search?debug=true&text=Kaschk, Berlin`

What you'll see is that `libpostal` parsed the query first:

```javascript
      {
        "controller:libpostal": {
          "parsed_text": {
            "query": "kaschk berlin"
          }
        }
      },
```

but the resulting parse wasn't able to produce a valid query:

```
      {
        "controller:search": "No query to call ES with. Skipping"
      },
```

and so we instead used the pelias parser to generate a query:

```js
      {
        "controller:search": {
          "queryType": {
            "search_pelias_parser": {
              "es_took": 44,
              "response_time": 48,
              "retries": 0,
              "es_hits": 8,
              "es_result_count": 8
            }
          }
        }
      },
```

**Comment by missinglink** [comment]
So `/v1/autocomplete` will always use the `pelias parser` whereas `/v1/search` will first attempt to use `libpostal` and if it's not able to identify that the input represents a fully-formed input then it will fall back to using the `pelias parser` which is much better at handling these sort of queries.

The `parsed_text` section of the response only contains information about the *last* parser solution:

```js
      "parser": "pelias",
      "parsed_text": {
        "subject": "Kaschk",
        "locality": "Berlin",
        "admin": "Berlin"
      }
```

**Comment by missinglink** [comment]
If you're running our docker projects then you'll find you already have a `libpostal` service running on port 4400.
https://github.com/pelias/docker/blob/master/projects/portland-metro/docker-compose.yml#L11

You can send it requests and see how it performs with incomplete input:
https://github.com/pelias/libpostal-service
