### ISSUE TITLE
Cannot parse input

### ISSUE THREAD

**Issue by franshua** [pelias/api#1414]
Hey team! 

After deploy Pelias, it is not able to parse some inputs. 

_For example_: 

**Working request**: http://url/-122.650095/45.533467

**Not working request:** http://url/v1/reverse?point.lat=-122.650095&point.lon=45.533467

The response is always: **Cannot parse input**.

It appears to be something related to paths and redirects.

Thanks in advance.

**Comment by Joxit** [comment]
It seems like you are using an endpoint from [pelias/pip-service](https://github.com/pelias/pip-service) and not [pelias/api](https://github.com/pelias/api/).

Is your pelias/api project running ?

**Comment by franshua** [comment]
Oh right @Joxit, it is working now! Thank you very much.
