### ISSUE TITLE
[ngram branch] query weighting

### ISSUE THREAD

**Issue by missinglink** [pelias/api#142]
@hkrishna I'm opening this ticket to track the admin weighting feature we discussed and so I have a place to put some test cases.

the gist of this is that on the *ngram* branch the part of the query which gave higher scores to queries which matched an admin value and scripts seem to have less effect than it used to.

**Comment by missinglink** [comment]
different results for these?

"new york, new york" http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/search%3Fsize=20&input=new%20york,%20new%20york
"new york, ny" http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/search%3Fsize=20&input=new%20york,%20new%20york

**Comment by missinglink** [comment]
"newark airport" http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/search%3Fsize=1000&input=newark%20airport

the `transport:air:aerodrome` entry should come higher than the other entries due to the category weighting script

**Comment by missinglink** [comment]
http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/search%3Fsize=20&input=40%20dean%20street,%20brooklyn,%20ny

**Comment by hkrishna** [comment]
yes! the script only acts like a score breaker.. 

Here's a query that uses functional_score and boosts ```_score``` value if the match happened to be a ```transport:air:aerodrome``` however, the side effect is that it always surfaces airports. We could use this query when we detect/determine that the user is searching for an airport - this needs to happen at the query_parsing stage in the API

```json
GET pelias/_search?search_type=dfs_query_then_fetch
{
   "query": {
      "function_score": {
         "query": {"bool": {
            "must": [
               {
                   "match": {
                      "name.default": "san francisco"
                   }
               }
            ], 
            "should": [
                { "match": {
                   "admin0": ""
                }},
                { "match": {
                   "admin1": ""
                }},
                { "match": {
                   "alpha3": "USA"
                }},
                {
                  "match": {
                    "admin1_abbr": ""
                  }
                }

            ]
          }
         },

         "boost": 1,
         "functions": [
            {
      "script_score": {
        "file": "category",
        "params": {
          "category_weights": {
            "transport:air": 2,
            "transport:air:aerodrome": 2,
            "transport:air:airport": 2
          }
        },
        "lang": "groovy"
      }
    }
        ]
      }
   },
   "size": 10,
   "sort": [
      "_score"
   ],
   "track_scores": true
}
```

**Comment by missinglink** [comment]
see: https://github.com/CanalTP/munin

**Comment by dianashk** [comment]
@missinglink, is this ticket still relevant or can it be closed?

**Comment by missinglink** [comment]
closing this ticket as it's old and no longer relevant.
