### ISSUE TITLE
Reverse geocoding don't work with layers parameter when we have custom layers

### ISSUE THREAD

**Issue by geostarters** [pelias/api#1455]
We are installing Pelias with docker inside our servers. We are working with custom layers (topo, pk, pois) . In search and autocomplete custom layers works fine:

But in reverse geocoding , the parameter layers don't work:

http://172.30.28.9:4000/v1/reverse?point.lon=1.812606&point.lat=41.246264&layers=pk -> NOT RESULTS
http://172.30.28.9:4000/v1/reverse?point.lon=1.812606&point.lat=41.246264 -> RESULTS WITH DIFFERENT LAYERS  (address,pk...)

We try to modifiy the api/query/reverse_defaults.js file

changed the following line:

      'layers': ['venue', 'address', 'street'],

to

      'layers': ['venue', 'address', 'street', 'topo','pk','pois','llogaret','mun','com'],

But don't work.

### References
https://github.com/pelias/api/issues/1342

**Comment by missinglink** [comment]
Hi @geostarters,

The links you posted are not publicly accessible, can you please copy->paste the pretty-printed response to a pastebin service (such as Github gist) so we can see what you're seeing?

Are you using the [auto_discover](https://github.com/pelias/api/issues/1342#issuecomment-524229791) feature?

**Comment by geostarters** [comment]
Hi @missinglink ,
we user auto_discover:true.

The response for http://172.30.28.9:4000/v1/reverse?point.lon=1.812606&point.lat=41.246264&layers=pk are:
https://gist.githubusercontent.com/geostarters/ac93e0738d32081861de9c906fd8dbd0/

And for http://172.30.28.9:4000/v1/reverse?point.lon=1.812606&point.lat=41.246264 are:
https://gist.github.com/geostarters/ff0d73a1aae2af6a65938f52edd39a40

**Comment by missinglink** [comment]
Your issue seems to be caused by this line https://github.com/pelias/api/blob/master/query/reverse.js#L43
That was written several years ago and pre-dates use of custom layers.

In order to support custom layers it will need to be updated.
So instead of only including `'address', 'street', 'venue'` it should instead disallow [all the administrative layers](https://github.com/pelias/config/blob/master/config/defaults.json#L64-L66).

**Comment by geostarters** [comment]
And we have to remove this line?
Because I modify this line to add all layers: "venue","address","street","topo","pk","pois","llogaret","mun","com"

**Comment by missinglink** [comment]
If you add `?debug=true` to the query you will be able to view the query, this should show you which layers are being targeted.

**Comment by geostarters** [comment]
The response is:

https://gist.githubusercontent.com/geostarters/c0929095fa2c3dbec9c5524d15375772/raw/48f62c27544a229785135ed19e931bf9974da461/results3.json

**Comment by missinglink** [comment]
There seems to be the same logic here which also needs to be changed:
https://github.com/pelias/api/blob/bf35084ffbd07eded85d7b964d709de27ad63525/controller/predicates/isOnlyNonAdminLayers.js#L9

**Comment by geostarters** [comment]
The response now is:
https://gist.githubusercontent.com/geostarters/125631937d41aa0129d5e31dc4e33c6e/raw/43d77d795d02fb03b075b0ee7d4765f874f80f69/results4.json

**Comment by missinglink** [comment]
There is another one here 🤦 
https://github.com/pelias/api/blob/bf35084ffbd07eded85d7b964d709de27ad63525/controller/predicates/isCoarseReverse.js#L9

**Comment by orangejulius** [comment]
I believe we've catalogued most cases like this in https://github.com/pelias/api/issues/1161

**Comment by geostarters** [comment]
We modified this files adding all layers we need ("venue", "address", "street", "topo", "pk", "pois", "llogaret", "mun", "com"):

- https://github.com/pelias/api/blob/master/controller/predicates/is_coarse_reverse.js
- https://github.com/pelias/api/blob/master/controller/predicates/is_only_non_admin_layers.js
 - https://github.com/pelias/api/blob/master/controller/coarse_reverse.js
- https://github.com/pelias/api/blob/master/helper/placeTypes.js
- https://github.com/pelias/api/blob/master/api/query/reverse.js
- https://github.com/pelias/api/blob/master/api/query/reverse_defaults.js

And also put in pelias.json this line of configuration:

"layers_by_source": {
		 "csv": ["venue", "address", "street", "topo", "pk", "pois", "llogaret", "mun", "com"]
 }

And is not working.

The response is: https://gist.githubusercontent.com/geostarters/22067139266b388c234361672f872ca0/raw/d20b9c570c4b1f5921f92632c79a030896efc90c/results5.json
