### ISSUE TITLE
Search Categories

### ISSUE THREAD

**Issue by hkrishna** [pelias/api#146]
This issue deals with using the category mapped on a document. Here are a few queries: 

* restaurants near me
* museums near me
* airports near me

This API endpoint should be able to take a the following parameters 
* ```category```
* ```lat/lon``` or ```bbox```

And return results that satisfy the condition

For example: 

```
localhost:3100/search?category=restaurant&lat=0&lon=0
```
or have a special endpoint?

```
localhost:3100/search/category?q=restaurant&lat=0&lon=0
```

should return restaurants that are near the given lat/lon

**Comment by riordan** [comment]
In addition to allowing users to search by categories, we're also going to want an endpoint where users can flat out list the categories themselves. That way we can continue to fiddle with the categories (adding more, finagling criteria), without needing to tie it to a full revamp of the API.

**Comment by dianashk** [comment]
Closing in favor of pelias/pelias#150
