### ISSUE TITLE
Ampersand oddities

### ISSUE THREAD

**Issue by missinglink** [pelias/api#147]
not sure what exactly is going on here but the API seems to be stripping text after an '&', possibly because it's a reserved symbol in the URL and not encoded properly, or maybe another reason?

this request `http://localhost:3100/search?input=a%20&%20b` results in the following query:

```bash
{
  "query": {
    "filtered": {
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "name.default": "a "
              }
            }
          ],
...
```

**Comment by hkrishna** [comment]
Thanks @missinglink for reporting this bug. This is a pretty annoying/ nasty one but is really important to squash. I'll get to it asap

**Comment by hkrishna** [comment]
Since this is something that needs to be handled by the client calling pelias API - I'm closing this issue.

**Comment by riordan** [comment]
When we get to writing user documentation, we should remember to call this one out (as well as other reserved tokens).

**Comment by missinglink** [comment]
right, so I monkey-patched the compare app, after a bit of digging there seems to be some confusion amongst the maintainers of http client libs as to the best way to handle this stuff.

works now, http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/search%3Fsize=20&input=4th%20&%20king%20caltrain,%20san

https://github.com/pelias/compare/blob/master/app/controllers/MainController.js#L19-L23

this is not very nice, maybe @hkrishna can fix it? I've had issues with both angular.$http and jquery http encoding when using GET params.
