### ISSUE TITLE
Results in autocomplete and search are not the same

### ISSUE THREAD

**Issue by geostarters** [pelias/api#1470]
We imported our data from Catalonia.
In Catalonia we have four cities that have the same name of the region(Barcelona, Girona, Tarragona, Lleida). This is a problem because when we make a query with one of these cities the results are from all the region. We make this steps in our installation of Pelias (docker):

#install sqlite3
sudo apt install sqlite3
#placeholder database
cd /data/placeholder
sudo  sqlite3 store.sqlite3
#delete regions of Catalunya (Barcelona,Girona,Tarragona,Lleida)
delete from docs where json like '%"placetype":"region"%';

In search it works:
http://18.184.108.113:4000/v1/search?text=carrer%20balmes%206,barcelona&layers=address&size=50 (one result of Barcelona city)

But in autocomplete don't work:
http://18.184.108.113:4000/v1/autocomplete?text=carrer%20balmes%206,barcelona&layers=address&size=50 (all results of the country)

**Comment by missinglink** [comment]
My understanding of this issue is that you would like to delete the `region:85682663`?

The `placeholder` database is only used by `/v1/search`, not by `/v1/autocomplete`.

I suggest you blacklist that record as per https://github.com/pelias/docker/blob/master/projects/portland-metro/blacklist/osm.txt and run `pelias import all` again.

**Comment by geostarters** [comment]
Ok, we'll try this option.
We have another problem.
https://aws.icgc.cat/cerca_pelias/autocomplete?text=Rambla%20De%20Felip%20Pedrell,3,Tortosa (no results)

https://aws.icgc.cat/cerca_pelias/cerca?text=Rambla%20De%20Felip%20Pedrell,3,Tortosa (one result)

**Comment by missinglink** [comment]
The issue tracker is not a right place to ask for free commercial support for your organization.

In general, the issues you report are not clear and do not follow the Bug Reporting template https://raw.githubusercontent.com/pelias/.github/master/.github/ISSUE_TEMPLATE/bug_report.md

I've feel that I've been generous in helping you find solutions to your problems but the cost of providing you assistance has become too high and I will no longer be able to provide you with assistance.

If you're able to start writing clearer bug reports (using the template provided) then we may be able to help you again in the future.

You can ask other members of the community for their help in our forum: https://gitter.im/pelias/pelias

**Comment by geostarters** [comment]
@missinglink I think your answer is not too appropriate. Is possible that my issue are no very clear because my english is not very good and I can't explain all correctly.
The thinks that we are reporting are behaviors that are not correct. I think that Pelias is a good tool but the documentation is not very good and not very clear and this is a problem for people that want to use. 
Otherwise thanks for replying.
