### ISSUE TITLE
Confidence seems to be calculated incorectly

### ISSUE THREAD

**Issue by hannojg** [pelias/api#1488]
**Describe the bug**
We are searching for a venue with a focus point. The focus point is the city. The venue is a restaurant chain, so it has branches in many cities. We expect, that the restaurant at the focus point is the first result with the confidence of one. However, the first result is of a venue in a completely different city with confidence being 1.

**Steps to Reproduce**
1. Run this query: https://pelias.github.io/compare/#/v1/search?layers=venue&focus.point.lat=53.867646&focus.point.lon=10.690266&text=Losteria
2. The focus point is the city "Lübeck"
3. You can see that the first result is the `Losteria, Mannheim` (very far away from the focused city "Lübeck") with a confidence of 1.

**Expected behaviour**
"Losteria, Lübeck" is the first entry with a confidence of 1 as the focal point is more close to this place than the other.

**Environment (please complete the following information):**
 - OS: Linux
 - Docker version 19.03.12, build 48a66213fe
 - docker-compose version 1.26.0, build d4451659
 - pelias api version: from git, commit 9c068de5d015267da4ec4e18b2b715de87e132c3
 - pelias 

**Pastebin/Screenshots**
<img width="1071" alt="Screenshot 2020-09-10 at 13 20 06" src="https://user-images.githubusercontent.com/16821682/92722762-5f586b80-f368-11ea-8ff2-1e35bfc26b43.png">

**Comment by missinglink** [comment]
Hmm.. this is working correctly for `autocomplete` but not for `search`, it seems the only real difference in the scoring algorithm is the `weight` which is substantially more for autocomplete.

<img width="1180" alt="Screenshot 2020-09-10 at 14 19 00" src="https://user-images.githubusercontent.com/738069/92728310-cb3ed200-f370-11ea-8c1d-1738595177c0.png">

cc/ @orangejulius should we consider increasing the `weight` for `/v1/search`?

thanks for the test case @hannojg

**Comment by missinglink** [comment]
This is the relevant config variable, you can change it and restart the server: https://github.com/pelias/api/blob/master/query/search_defaults.js#L34

If you're running inside Docker it's a little trickier, you'll need to copy the file to your local machine, make the change and then bind mount it over the copy inside the container.

An example of such a 'bind mount' can be found here: https://github.com/pelias/docker/blob/master/projects/portland-metro/docker-compose.yml#L17

The location of that file *inside* the container is `/home/pelias/query/search_defaults.js`
