### ISSUE TITLE
[admin weighting] double weighting

### ISSUE THREAD

**Issue by missinglink** [pelias/api#149]
the ordering for "new york, ny" differs from "new york, new york"

.. after some digging I figured out that it is because 'Yotel New York' has more matching admin fields than the geoname record for 'New York' (city)

```javascript
name: "Yotel New York",
admin1: "New York",
admin2: "New York County",
admin1_abbr: "NY",
locality: "New York",
```

```javascript
name: "New York",
admin1: "New York",
admin1_abbr: "NY",
```

what this basically means is that records with better admin info will return higher in the search results than those which do not.

@hkrishna thoughts?

related: https://github.com/pelias/api/issues/148

**Comment by missinglink** [comment]
this may/may not be related to https://github.com/pelias/api/issues/150

**Comment by orangejulius** [comment]
Looking at [Yotel New York, NY](http://pelias.github.io/compare/#/v1/search%3Ftext=yotel%20new%20york,%20ny) vs [Yotel New York, New York](http://pelias.github.io/compare/#/v1/search%3Ftext=yotel%20new%20york,%20new%20york), we aren't perfect, but have mostly fixed this.
