### ISSUE TITLE
Search queries don't use the `city` part of the parsed address

### ISSUE THREAD

**Issue by SilvrDuck** [pelias/api#1518]
Hi there,
I am running a custom pelias instance, containing only swiss data. I’m having trouble with addresses with street names that are present in multiple cities.

**Describe the bug**
When I run a query, for example for `Rue de Lausanne 21, Genève`, I get a lot of results for cities that are not Genève (Geneva) first.

**Steps to Reproduce**
```
req = "rue de lausanne 21, genève"
req = urllib.parse.quote(req)
r.get(f"{pelias}search?text={req}&debug=true").json()
```

**Expected behavior**
`Rue de Lausanne` is a very common street name in Switzerland, but as I specify `Genève` in the query, I expect to see it first. Currently, it's not even in the first ten reported results.

**Environment (please complete the following information):**
I deployed the official pelias docker images on a k8s cluster. The data comes from a custom csv imported using the [csv importer](https://github.com/pelias/csv-importer).

**Additional context**
Using the debug flag, I could see that the actual query that was made was:
```
{
   "ES_req":{
      "index":"pelias",
      "searchType":"dfs_query_then_fetch",
      "body":{
         "query":{
            "function_score":{
               "query":{
                  "bool":{
                     "minimum_should_match":1,
                     "should":[
                        {
                           "bool":{
                              "_name":"fallback.street",
                              "must":[
                                 {
                                    "match_phrase":{
                                       "address_parts.street":{
                                          "query":"rue de lausanne",
                                          "slop":4,
                                          "analyzer":"peliasQuery"
                                       }
                                    }
                                 }
                              ],
                              "filter":{
                                 "term":{
                                    "layer":"street"
                                 }
                              },
                              "boost":5
                           }
                        },
                        {
                           "bool":{
                              "_name":"fallback.address",
                              "must":[
                                 {
                                    "match_phrase":{
                                       "address_parts.number":{
                                          "query":"21"
                                       }
                                    }
                                 },
                                 {
                                    "match_phrase":{
                                       "address_parts.street":{
                                          "query":"rue de lausanne",
                                          "slop":4,
                                          "analyzer":"peliasQuery"
                                       }
                                    }
                                 }
                              ],
                              "filter":{
                                 "term":{
                                    "layer":"address"
                                 }
                              },
                              "boost":10
                           }
                        }
                     ],
                     "filter":{
                        "bool":{
                           "must":[
                              {
                                 "terms":{
                                    "layer":[
                                       "address"
                                    ]
                                 }
                              }
                           ]
                        }
                     }
                  }
               },
               "functions":[
                  
               ]
            }
         },
         "size":20,
         "track_scores":true
      }
   }
}
```
Yet, libpostal had correctly identified `genève` as the city:
```
{
   "controller:libpostal":{
      "parsed_text":{
         "street":"rue de lausanne",
         "housenumber":"21",
         "city":"genève"
      }
   }
}
```

Since the `query_using_ids` did returned elements, pelias just went on and didn't bother checking for the correct `localadmin`. Note as well that I manually searched for the address in elasticsearch, and the `parent.localadmin` field was correctly set to `Genève` as expected.

**Is there something I am missing or is this a bug?**

Thanks in advance.

**Comment by missinglink** [comment]
> Is there something I am missing or is this a bug?

I don't think it's a bug since the Geocode Earth servers don't exhibit the same behaviour:
- https://pelias.github.io/compare/#/v1/search?text=Rue+de+Lausanne+21%2C+Gen%C3%A8ve

I suspect there is something misconfigured in your environment.

My guess would be that the `placeholder` service is not working correctly, you should see a `controller:placeholder` section in your debug output similar to that being returned from the Geocode Earth servers.

<img width="454" alt="Screenshot 2021-03-15 at 11 38 51" src="https://user-images.githubusercontent.com/738069/111086789-15ed1100-8583-11eb-8737-630ea2862805.png">

If this is working as expected, you should see a `filter` section in the query which restricts the results to a subset of IDs:

<img width="468" alt="Screenshot 2021-03-15 at 11 39 09" src="https://user-images.githubusercontent.com/738069/111086791-184f6b00-8583-11eb-9276-eb8bbc251617.png">

**Comment by SilvrDuck** [comment]
Hey @missinglink, it turns out you are right! Thanks for [https://pelias.github.io/compare/](https://pelias.github.io/compare/), it is a great tool.

I was focused on `libpostal` and didn't see that every `placeholder` reply were blank. I was downloading the wrong data.

By the way, I am now using [https://data.geocode.earth/placeholder/store.sqlite3.gz](https://data.geocode.earth/placeholder/store.sqlite3.gz) for my data, which is worldwide. I would like to download only Switzerland only ideally, but when I go to the `ch` section of [geocode earth](https://geocode.earth/data/whosonfirst), the available dbs do not work with placeholder. Is there another place to find country specific data?


Best

**Comment by missinglink** [comment]
https://github.com/pelias/placeholder#building-the-database
