### ISSUE TITLE
Flip street name and number for Ukrainian addresses

### ISSUE THREAD

**Issue by ShoSashko** [pelias/api#1520]
Similar to #1343 

[Here](https://github.com/pelias/api/blob/master/middleware/localNamingConventions.js#L5) I can't see Ukraine in list
Please add UKR to a list of countries with supporting following street format: {{address}} {{number}}

**Comment by missinglink** [comment]
Hi @ShoSashko
Can you please provide 3 famous/popular example addresses for our test suite?

**Comment by ShoSashko** [comment]
Hello @missinglink  
Sure:
1. Svobody Ave, 28, L’viv, Lviv Oblast, Ukraine, 
2. Rynok Square, 1, L’viv, Lviv Oblast, Ukraine,
3. Stavropihiiska Street, 3, L’viv, Lviv Oblast, Ukraine

Let me know if that works for you

**Comment by ShoSashko** [comment]
@missinglink Hi, any updates here?

**Comment by loadit1** [comment]
Hi @missinglink ! It should be the same for  Russia, Uzbekistan, Tajikistan, Belarus, Azerbaijan, Georgia, Kyrgyzstan and Kazakhstan too.

**Comment by missinglink** [comment]
The original issue was resolved by https://github.com/pelias/api/pull/1523
