### ISSUE TITLE
Extremely slow query that generates an out of memory error

### ISSUE THREAD

**Issue by mihaicosareanu-bolt** [pelias/api#1530]
**Describe the bug**

I have found a query that brings pelias-api to its knees. I'm currently trying to understand the code behind the Tokenizer and ExclusiveCartesianSolver, but I thought I should give you a heads up as well, maybe you will understand much faster what happens. I've tried other queries with multiple tokens but none behave as bad as this one :).

**Steps to Reproduce**
https://pelias.github.io/compare/#/v1/autocomplete?text=Jos%C3%A9+Mart%C3%ADho+377%2F8%2C+PrahaVV+v%C5%A1e+bu+bu+bu+bu+thtf+mi+cc+SR+se+se+se+l+ji+bu+bu+bu+bu+bu+bu+bu+bu+bu+%C4%8CR+XXX+y+si+se+se+se+se+se&debug=1

What I've noticed is that in a previous pelias version (tried a commit from 29 Jun 2020) it works fast. So there were some changes in between that have affected this (on my machine the latest master returns in 22 seconds vs 800 ms in the 2020 June commit). 

**Expected behavior**
Should return as fast as other queries with multiple tokens do.

**Environment (please complete the following information):**
Linux & Mac

**Pastebin/Screenshots**

**Additional context**

**Comment by orangejulius** [comment]
Hi @mihaicosareanu-bolt,
Thanks for reporting this, it explains some slow queries we've been seeing lately :)

I do think this came in as part of https://github.com/pelias/api/pull/1452, where we upgraded the parser a bunch.

I'm also not super familiar with the parser code, and that pull request brought in quite a few changes, so it could be hard to figure out exactly what broke it or how to fix it. But we'll be looking as well, let us know if you find anything.

**Comment by mihaicosareanu-bolt** [comment]
Thanks for looking into it! I will spend more time on it next week :)

**Comment by mihaicosareanu-bolt** [comment]
Thanks a lot Julius! Indeed, tested on my machine and it works without that code. Do you plan on retiring this bit until we have proper support of unit numbers? What are your thoughts?

**Comment by mihaicosareanu-bolt** [comment]
Great! Looking forward to your conclusion :). Safe travels @missinglink :D

**Comment by orangejulius** [comment]
Okay, we've just put in a 'hotfix' for this issue, and it should be effectively resolved with no regressions in result quality.

After taling with @missinglink there are a bunch of different ways we can put in a long term fix, which we can discuss here.

For now though, anyone using the `master` branch of the Pelias API shouldn't see any slow parses or out of memory issues.
