### ISSUE TITLE
markdownToHtml controller doesn't render valid HTML

### ISSUE THREAD

**Issue by missinglink** [pelias/api#1597]
the [controller/markdownToHtml.js](https://github.com/pelias/api/blob/master/controller/markdownToHtml.js) module doesn't render valid HTML, it's missing the `<HTML>`, `<BODY>` tags.

this issue is to modify that behaviour so that requests to `/` and `/attribution` render valid HTML

<img width="785" alt="Screenshot 2022-02-01 at 09 27 50" src="https://user-images.githubusercontent.com/738069/151935302-6543e26c-f3b8-4f27-9abd-d7cba5f66b0f.png">

**Comment by RishiKumarRay** [comment]
in which file do we have to make changes?

**Comment by missinglink** [comment]
resolved via https://github.com/pelias/api/pull/1599
