### ISSUE TITLE
Pelias doesn't return the postcode when OSM appears to have it

### ISSUE THREAD

**Issue by stevevance** [pelias/api#162]
[My API call](http://pelias.mapzen.com/search?input=3509%20w%20fulton%20blvd&lat=41.809148&lon=-87.618538&bbox=-88.30,41.430,-87.47,42.198&layers=poi,address) is looking for a Chicago address, which OpenStreetMap Nominatim [says has a postcode](http://nominatim.openstreetmap.org/details.php?place_id=797771497) (it's inferred from the street way). 

Then a building I'm searching for, [3542 W Fulton Blvd](http://nominatim.openstreetmap.org/details.php?place_id=93231219), also has an inferred – it's not tagged – postcode. 

Can Pelias return the postcode?

**Comment by hkrishna** [comment]
Hey @stevevance thanks for opening this issue. 

Currently, we don't infer postcodes from the street way. If the OSM node has a postcode tagged, they show up in the pelias API results. Here's an [API result](http://pelias.mapzen.com/search?input=101%20saint%20marks%20pl%20new%20york) that contains this [OSM node](http://www.openstreetmap.org/way/248164780) - notice the tag ```addr:postcode```

However, there are plans on implementing a postcode lookup for every given point at the time of data import (essentially, inferring from the street way/ admin polygon). This is part of the pelias roadmap. If you have any thoughts/ questions/ comments please check out this [issue](https://github.com/pelias/pelias/issues/111). 

We could talk about the pros and cons both short term and long term with inferring postcodes from street ways vs doing a global postcode lookup for every node - and what this means in terms of data consistency and completeness.

**Comment by stevevance** [comment]
Thanks for the tip! I left a comment over on that issue. 

I figured that Pelias would return the postcode if the node was tagged with the postcode. I'll be more careful editing objects in Chicago and try to tag the postcode.
