### ISSUE TITLE
Search for federal states of Germany in German language

### ISSUE THREAD

**Issue by dawidl11** [pelias/api#1629]
Hi there,

I have encountered a problem when using Pelias Snapshot.

**What am I using?**

I have created a standard Pelias snapshot (data sources: OSM, Opensearch, Geonames, WhosOnFirst). 

**What is the problem?**
I want to specify now in my structured query (under the attribute "Region") the German federal state. In doing so, I enter the German name of the federal state (e.g. "Sachsen"). When I do this, no correct result is returned. 
However, if I enter the same query with the English name of the state ("Saxony"), a correct result is returned.

**My question:**
Is it possible to set Pelias to correctly identify German state names in the queries?

Many thanks in advance for the answers!

**Comment by dawidl11** [comment]
Hi @missinglink ,
The problem was actually with `Accept-Language`. Thanks for the hint.

**Comment by missinglink** [comment]
@dawidl11 please close the issue if it's resolved

**Comment by dawidl11** [comment]
At first we thought it was actually due to our "Accept-Language". But now we have also checked it with German as "Accept-Language" and unfortunately we get the same results. Also with the following Pelias API: https://api.geocode.earth .
Here is an example of a request: 

- https://api.geocode.earth/v1/search/structured?lang=de&size=10&api_key=<KEY>&address=Domkloster 4&locality=Köln&region=Nordrhein-Westfalen&debug=1 (Fallback)
- https://api.geocode.earth/v1/search/structured?lang=de&size=10&api_key=<KEY>&address=Domkloster 4&locality=Köln&region=North Rhine Westphalia&debug=1 (Exact)

So it looks like a general problem. Could this please be reviewed again?
Many thanks in advance!

**Comment by missinglink** [comment]
See this recently merged PR for more context, this is much closer to being resolved now.

https://github.com/pelias/wof-admin-lookup/pull/314

**Comment by dawidl11** [comment]
Thank you for the link. This looks interesting and is in line with what we have also been investigating. 
Is it also possible to estimate approximately when the adjustments will be made for German federal states, or is that rather difficult to say?

**Comment by missinglink** [comment]
The issue with German Federal States should now be resolved via https://github.com/pelias/wof-admin-lookup/pull/317

**Comment by missinglink** [comment]
https://github.com/pelias/acceptance-tests/pull/567

**Comment by dawidl11** [comment]
This is very good news. Thanks for the information @missinglink
