### ISSUE TITLE
Pelias: Updating the street data

### ISSUE THREAD

**Issue by dawidl11** [pelias/api#1634]
Hi there,

I have a question regarding searching with Pelias for specific streets.

**What am I using?**
I created a Pelias snapshot with the latest OSM data and searched for specific streets.

**What is the problem?**
Unfortunately, when searching for "Bolko-von-Hochberg-Straße Görlitz" I get no hit (the street is not found).
The street exists since 2020 and is already present in the OSM data.

**My question:**
That's why I have the question: which data sources would I still have to update so that the street I mentioned is also found with Pelias?

Many thanks in advance for the answers!

**Comment by missinglink** [comment]
Please provide the OSM ID of the expected way and post a copy of your `pelias.json` file with [appropriate formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

I suspect you're referring to the [this street](https://pelias.github.io/compare/#/v1/autocomplete?text=Bolko-von-Hochberg-Stra%C3%9Fe+G%C3%B6rlitz) but you've not provided enough information for another developer to reproduce your error, which makes it difficult for me to comment on why it's not working for you, but is working on Geocode Earth.

**Comment by dawidl11** [comment]
Thank you for this information. You are right. 
The street consists of several Ways. Whose OSM IDs are: _960782661_, _961087331_, _24416272_, _116345661_.
[pelias.zip](https://github.com/pelias/api/files/9451106/pelias.zip)

**Comment by missinglink** [comment]
Do you have *any* streets in your index? Try running `pelias elastic stats` to see.

I suspect that you've [triggered this error](https://github.com/pelias/polylines/blob/master/docker_extract.sh#L26-L35) and not noticed?

**Comment by dawidl11** [comment]
Now I have checked. Yes, we have polyline data that we download from the following website: https://geocode.earth/data (planet-latest-valhalla.polylines.0sv.gz). Our data have the date 2020-07-21.

Since there are no newer ones on the website, I wanted to ask if it is possible to update them myself?

**Comment by missinglink** [comment]
I've updated the polylines downloads at https://geocode.earth/data
The new download is https://data.geocode.earth/osm/2022-35/planet-latest-valhalla.polylines.0sv.gz

**Comment by dawidl11** [comment]
Great, thanks for the update! We will soon import the data into our new Pelias snapshot

**Comment by missinglink** [comment]
For future reference, these files are generated using [valhalla](https://github.com/valhalla/valhalla) as documented on the [polylines](https://github.com/pelias/polylines) repo.

- https://github.com/pelias/polylines
- https://github.com/pelias/polylines/wiki/Generating-polylines-from-Valhalla
- https://github.com/pelias/polylines/issues/268
