### ISSUE TITLE
Finland - Suomi

### ISSUE THREAD

**Issue by mleginus** [pelias/api#166]
Hi guys,

when trying to search for Finland or Sweden, the api returns incorrect matches e.g.,

http://pelias.mapzen.com/search?input=finland&layers=admin0

Finland is stored under Suomi name in the ES index (http://pelias.mapzen.com/search?input=suomi&layers=admin0) together with alternative names like: alt1: "Finland" and alt2:"suomi#Finland". 

Could you suggest how to incorporate alternative names into the search process such that correct match will be returned?

thanks,

martin

ps: I am new into Pelias but you are doing a great job, thanks for the great tool

**Comment by missinglink** [comment]
more info:
```javascript
/GET http://localhost:9200/pelias/admin0/_search?df=name.default&q=Suomi&size=1
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 71,
    "max_score": 24.952162,
    "hits": [
      {
        "_index": "pelias",
        "_type": "admin0",
        "_id": "290:adm0:fi:fin:_",
        "_score": 24.952162,
        "_source": {
          "center_point": {
            "lon": 25.899305834241,
            "lat": 64.253386064471
          },
          "popularity": 209160,
          "name": {
            "default": "Suomi",
            "alt2": "Suomi#finland",
            "alt1": "Finland"
          },
          "alpha3": "FIN",
          "admin0": "Finland"
        }
      }
    ]
  }
}
```

related: https://github.com/pelias/quattroshapes/issues/24
related: https://github.com/pelias/api/issues/127

**Comment by dianashk** [comment]
Resolved with WOF integration!
