### ISSUE TITLE
API - missing Elasticsearch plain text authentication

### ISSUE THREAD

**Issue by cozydvlpr** [pelias/api#1668]
Hi,

I want to install the Pelias project on my infrastructure. However, a full fledged Elasticsearch cluster is already available so I don't need to start a container for it. Looking at the documentation first and to the code afterwards, I did not see any option to specify the authentication. The cluster I use allows only authenticated requests. 
Is it possible to add authentication to the configuration of the ES client?

Ideally after the change, it should be possible to specify the configuration like this
```
"esclient": {
  "hosts":[{
       "host":"my cluster.mycompany.com",
       "user": "randomUser",
       "password": "password"
      }]
}
```

Another option would be to store the credentials in env variables and have the possibility of using a place holder in the config file.

Thanks!

**Comment by missinglink** [comment]
It should be possible using the syntax described here:
https://www.elastic.co/guide/en/elasticsearch/client/elasticsearch-js/16.x/_basic_auth.html

**Comment by cozydvlpr** [comment]
It worked as you described, thanks
