### ISSUE TITLE
Rename `/search?input`, replacing it with '/search?text' parameter instead

### ISSUE THREAD

**Issue by riordan** [pelias/api#172]
(Please rename this ticket if this is out of the style guide)

# High Level
Rename `/search` parameter `input` to `text` for clarity.

# Purpose
For all of our queries (and all endpoints), there are lots of *inputs*, making the original parameter `input` unclear about what its purpose way. By renaming this parameter to `text`, we're providing a clearer definition of what is being queried, in this case unstructured text to be geocoded.

**Comment by riordan** [comment]
Should we deprecate the `text` parameter, but still support it for the time being, letting existing clients continue to use the API?

Perhaps worth holding until we have the discussion about how we handle versioning.

**Comment by hkrishna** [comment]
why not ```query``` or even just ```q``` ?
