### ISSUE TITLE
`/search?categories` parameter incorporates hierarchy/layers

### ISSUE THREAD

**Issue by riordan** [pelias/api#174]
Extends pelias/api#128

The `categories` parameter enables an API user to search for particular types of places (when a scope is applied) or to filter a set of search results to limit to only matching types. Already this applies to POI-type amenities (pelias/api#128), but it should also apply to offering administrative hierarchy elements (currently handled as `layers=admin` and `/search/coarse`).

**Comment by riordan** [comment]
This should open the door to inclusion of more natural features (water, mountain ranges, etc.) through this same mechanism.

**Comment by orangejulius** [comment]
#186 is now ready, and adds categories to /search with the exact same behavior as we currently have for /reverse. Is there anything else required besides allowing categories to be specified without any input text?

**Comment by riordan** [comment]
Exactly.

Categories act like scope when there's input text, but are able to be used in lieu of input text when you apply a limiting geographic extent.

With text:  you can look for places with "Chipotle" in the name that are classified as `food:burrito`
`/v1/search?category=food:burrito&text=chipotle`

Without text, but with the inclusion of a bounding box, we can ensure burritos are found in The Mission (or at least mission-ish).
`/v1/search?category=food:burrito&extent.min_lat=37.746829&extent.min_lon=-122.419281&extent.max_lat=37.760211&extent.max_lon=-122.405548`

Admittedly, with just a lat/lon, it acts an awful lot like reverse geocoding for categories, so this is most effective when used with a bounding box. But it's possible
`/v1/search?category=food:burrito&extent.lat=37.758768&extent.lon=-122.413313`

**Comment by dianashk** [comment]
Closing in favor of pelias/pelias#150
