### ISSUE TITLE
`/search?categories` parameter accepts multiple categories

### ISSUE THREAD

**Issue by riordan** [pelias/api#175]
Using the `categories` parameter to search, an API user may pass along several categories.

Multiple categories may be passed along, separated by a comma, or a comma separated by whitespace. Invalid categories are ignored (and a notification is passed along in the Error block of the response).

Categories are additive (OR's rather than ANDs) in that a query with multiple categories should not disqualify results that don't map to all categories.

**Comment by riordan** [comment]
DUPE!

**Comment by orangejulius** [comment]
More specifically, it's a dupe of #128
