### ISSUE TITLE
`/search?layers` becomes Coarse

### ISSUE THREAD

**Issue by riordan** [pelias/api#176]
Search layers should be able offer mix & matched layers for different types of features (aliasing `admin0`, `admin1`, and `admin2` into `admin`, and aliasing `admin` into `coarse`).

New Aliases are created by the operator of the Pelias instance, not an API user nor an End User.

This is what lets us accomplish offering individual individual administrative layers as categories, while combining them to an `admin` option, as well as a `coarse` category replace /search/coarse.

**Comment by hkrishna** [comment]
Can this be extended to other category values as well? As in aliasing ```aeroway```, ```aerodrome```, ```transport:air``` into ```airport``` or something equivalent for example.. ? 

Furthermore with reference to this [doc](https://github.com/pelias/openstreetmap/blob/master/config/category_map.js), we could resolve all the keys to its values and additionally form other aliases for the keys themselves. 

Thoughts?

**Comment by riordan** [comment]
I rather like that approach.

On Tue, Jul 28, 2015 at 9:25 PM, Harish Krishna <notifications@github.com>
wrote:

> Can this be extended to other category values as well? As in aliasing
> aeroway, aerodrome, transport:air into airport or something equivalent
> for example.. ?
>
> Furthermore with reference to this doc
> <https://github.com/pelias/openstreetmap/blob/master/config/category_map.js>,
> we could resolve all the keys to its values and additionally form other
> aliases for the keys themselves.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/176#issuecomment-125797185>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by riordan** [comment]
This should apply to `layers` parameter, rather than `categories` at this time.

**Comment by riordan** [comment]
I've been having second thoughts about the elimination of `/coarse` options as independent endpoints. In the case of reverse coarse (point-in-polygon) it's a fundamentally different behavior from what we do with reverse POI geocoding.

`pelias.mapzen.com/v1/reverse?lat=x&lon=y&layers=coarse`
is a different kind of search, routed a totally different way from:
`pelias.mapzen.com/v1/reverse?lat=x&lon=y`

In the former we'd have to know the difference between if someone said `&layers=address,poi` vs `&layers=neighborhood,locality`. It offers us more flexibility in implementing what we support by separating them out.

We would also be able to only offer layers that could be coarsely reverse geocoded on `/reverse/coarse` (have boundaries/shapes), and could offer only point-based layers on `/reverse/`. This way we could ensure that there would never be colliding layer types in the same reverse query. (e.g. `layer=region&address`, which is possible in the current spec).

It also offers us a lot more flexibility in how we implement this. A reverse coarse geocoder needs a significantly smaller document set than a global geocoder and presumably could exist outside of Elasticsearch (like we already do with the import pipeline). Separating this out would let us easily start offering Point-in-Polygon lookup to our users and just route it at the API level, or to offer Pelias-Reverse-Coarse as a standalone module, capable of supporting high request volumes without t needing to stand up a complete Pelias instance.

If we were to do this, we'd likely want to preserver `/search/coarse` & `/suggest/coarse` for consistency. However this would let us offer additional functionality for coarse in the future (e.g. scoping of layers & countries on suggest), but ensure we don't have to support additional things that would clash with it now.

Thoughts?
