### ISSUE TITLE
Move back to upstream cluster2 package if our PR is merged

### ISSUE THREAD

**Issue by missinglink** [pelias/api#180]
Update package.json to remove the `git://` url used as an interim solution until the upstream PR is closed, see commit: https://github.com/pelias/api/commit/e3efeb66d18374524f89696754db0a024c27dc73

The version number targeted for `cluster2` MUST include this PR: https://github.com/cubejs/cluster2/pull/86

**Comment by missinglink** [comment]
the upstream developers havn't responded for several months, unfortunately we might have to fork this repo.

**Comment by orangejulius** [comment]
Fixed in #585
