### ISSUE TITLE
How to handle introduction of versioning and deprecation?

### ISSUE THREAD

**Issue by riordan** [pelias/api#182]
1.0 of our API is going to introduce a whole lot of changes to parameters and behaviors of our beloved Pelias. With that in mind, we need to figure out how and when these changes will impact our existing Pelias users (who have made ~500k calls/month for the past 2 months).

1 How will we handle the introduction of versioning to our system?
2 How will we deprecate the existing calls (made without a versioned namespace and may be renamed/remapped)?

**Comment by riordan** [comment]
I'd like to think we could deprecate the existing Pelias API over time, putting all the new calls into a new namespace (e.g. `/v1/search`), and have the calls to the root continue to work, for the time being.

Then (hat tip to @burritojustice for this one), we would replace the first (or second) result with a place at Null Island named "Upgrade To Pelias API 1.0" causing all kinds of chaos and confusion, but at least prompting our users that something significant has changed.

How feasible would something like this be?

**Comment by orangejulius** [comment]
+100000 to making sure v1 is in the url. Not so excited about creating chaos and confusion, although it's a cute idea :P

**Comment by hkrishna** [comment]
I was going to suggest just adding a key in ```properties``` called ```warning``` that says ```Upgrade to Pelias 1.0``` should work just fine.. making the response to look like this

```javascript
{  
   type:"FeatureCollection",
   features:[  
      {  
         type:"Feature",
         properties:{  
            warning: "Please upgrade to Pelias v1.0",
            id:"2885548500",
            layer:"osmnode",
            name:"McLaughlin & Stern LLP - New York, NY",
            alpha3:"USA",
            admin0:"United States",
            admin1:"New York",
            admin1_abbr:"NY",
            admin2:"New York County",
            local_admin:"Manhattan",
            locality:"New York",
            neighborhood:"Tenderloin",
            category:[  
               "professional"
            ],
            address:{  
               zip:"10016",
               number:"260",
               street:"Madison Avenue"
            },
            text:"McLaughlin & Stern LLP - New York, NY, Manhattan, NY"
         },
         geometry:{  
            type:"Point",
            coordinates:[  
               -73.981023,
               40.750739
            ]
         }
      },
     ...
}
```

Replacing one of the results might ensure faster adoption however, it might be too aggressive?? (I agree with @orangejulius with creating chaos and confusion)

If we do decide to go with the null island result idea - we could even randomize the occurrence of null island result (to ensure that the api consumers have to upgrade and cant add a line that skips the first result) :smiling_imp:  And probably even the number of occurrences per result set as we get ready to shut down support for pre-v1 service.

**Comment by orangejulius** [comment]
To be clear, I'm completely ok with aggressively pushing people onto the new API, as long as we've set an announced timetable. I don't think messing with the actual results from an API call in any way is a good idea. Finding "Please upgrade to Pelias v1.0" in data sets across the world for years because of what we did would really suck. 

Oddly there doesn't seem to be an [HTTP status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) appropriate for this. Maybe we could just intermittently return 403 with a big upgrade message when the time comes

**Comment by riordan** [comment]
With that in mind, what would it look like to continue supporting calls to
the root endpoints?

On Mon, Aug 3, 2015 at 4:42 PM, Julian Simioni <notifications@github.com>
wrote:

> To be clear, I'm completely ok with aggressively pushing people onto the
> new API, as long as we've set an announced timetable. I don't think messing
> with the actual results from an API call in any way is a good idea. Finding
> "Please upgrade to Pelias v1.0" in data sets across the world for years
> because of what we did would really suck.
>
> Oddly there doesn't seem to be an HTTP status code
> <https://en.wikipedia.org/wiki/List_of_HTTP_status_codes> appropriate for
> this. Maybe we could just intermittently return 403 with a big upgrade
> message when the time comes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/182#issuecomment-127401431>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by hkrishna** [comment]
there would be a few lines in the sanitizers that check for the older param names as a fallback option (this logic can be decoupled into its own module if needed ```DRY```) But roughly it would look something like this (this is just for the input text sanitizer)

:point_down: is how it looks currently

```javascript
  // input text
  if('string' !== typeof params.text || !params.text.length){
    return { 
      'error': true,
      'message': 'invalid param \'text\': text length, must be >0'
    };
  }
  
  req.clean.text = params.text;

  req.clean.parsed_text = query_parse(params.text);
```

:point_down: this is how it will have to look so that it supports both ```text``` & ```input``` as param names 

```javascript
  var is_invalid_input = function( text ) {
  	return 'string' !== typeof text || !text.length;
  };

  var input_text = params.text;
  var display_deprecation_message_in_the_result_set = false;

  if (is_invalid_input(input_text) && !is_invalid_input(params.input)) {
  	input_text = params.input;
  	display_deprecation_message_in_the_result_set = true;
  }

  // input text
  if( is_invalid_input(input_text) ){
    var msg = 'invalid param \'text\': text length, must be >0'
    if ( display_deprecation_message_in_the_result_set ){
      // deprecation message should be stored in one centralized place 
      // and re-used in all other sanitizers and geojsonify.js
      // var deprecation_msg = require('deprecation_msg')
      // this line shoud ideally be
      // msg += deprecation_msg
      msg += '\n Please upgrade to Pelias v1.0';
    }

    return { 
      'error': true,
      'message': msg
    };
  }
  
  req.clean.text = input_text;

  req.clean.parsed_text = query_parse(input_text);
  ```

**Comment by orangejulius** [comment]
:+1: on nicely supporting text and input. thanks harish

**Comment by dianashk** [comment]
For `text` and `input` this would work, because it's a relatively cosmetic change. For anything more involved, it will be hard to maintain backwards compatibility.

Maybe it would be possible to run the current version of the API on dedicated hardware for the next month or so, with warnings in the responses as well as all over our docs and twitter. Then start running the new version side-by-side with v1.0 in the url and continue to make changes there. Eventually run a countdown clock to when the old version will be taken offline. It would be exciting! We can pop bottles when the clock gets to 0:0:0. Also v1.0 url will be behind the developer keys right off the bat, and this will give us time to make sure that's all working smoothly.

**Comment by riordan** [comment]
:+1:

On 8/10/15 11:29, Diana Shkolnikov wrote:
>
> For |text| and |input| this would work, because it's a relatively
> cosmetic change. For anything more involved, it will be hard to
> maintain backwards compatibility.
>
> Maybe it would be possible to run the current version of the API on
> dedicated hardware for the next month or so, with warnings in the
> responses as well as all over our docs and twitter. Then start running
> the new version side-by-side with v1.0 in the url and continue to make
> changes there. Eventually run a countdown clock to when the old
> version will be taken offline. It would be exciting! We can pop
> bottles when the clock gets to 0:0:0. Also v1.0 url will be behind the
> developer keys right off the bat, and this will give us time to make
> sure that's all working smoothly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/182#issuecomment-129496848>.
>

-- 
-- 
David Riordan | Product Manager - Search | Mapzen
dave.riordan@mapzen.com | @riordan | gpg 235D 9DC9 5EF6 277C
https://mapzen.com | @mapzen

**Comment by riordan** [comment]
One last suggestion (via @missinglink):

In addition to `/v1`, we also introduce the ability to put out the equivelent of "point releases" (e.g. 1.1). The latest version (e.g. `/v1/3`) would then alias to the main version of the release. This allows us to test and verify API additions and changes, while letting users freeze at the version that works for them.

**Comment by riordan** [comment]
- [ ] Write versioning policy
