### ISSUE TITLE
Rename `/search` Lat/Lon to `focus.point.lat` and `focus.point.lon`

### ISSUE THREAD

**Issue by riordan** [pelias/api#183]
With many of these geographic parameters in other APIs, we have noticed the tendency to design API calls that encourage user error with non-explicit naming conventions (e.g. `latlon` or `bbox`). We want to do our best to prevent that.

With the introduction of [focus](https://docs.google.com/spreadsheets/d/1lwtHT0-l-0gzYKdTKx8cZysnEMZKq2vASf0buyieSaI/edit#gid=1064303532) we will explicitly scope and namespace `/search` queries that constrain the geographic focus of the search.

For `/search&lat=<x>&lon=<y>', we should rename:
- 'lat'-> 'focus.point.lat'
- 'lon' -> 'focus.point.lon'

It will continue to expect a valid WGS84 latitude and longitude and will incorporate the longitude wrapping as implemented by pelias/api#56

**Comment by orangejulius** [comment]
I've updated the title and issue body to reflect our new naming as of a few days ago: focus.point.lat and focus.point.lon
