### ISSUE TITLE
Order of `target_layers` significantly impacts results

### ISSUE THREAD

**Issue by dianashk** [pelias/api#191]
When investigating `new york, new york` test failure, I found that when running the same query we built directly through `sense` vs via API, the correct result was getting dropped. `sense` would return a result from the `admin2` layer as being the most relevant, however the API query would always come back with results exclusively from `osmnode` and `geonames`.

I noticed that the only difference is the `type` array we append to the API query which contains target_layers. We build that target_layers list [here](https://github.com/pelias/api/blob/master/helper/layers.js#L15). Curious thing is if we change the order to have `admin` first in the list, the correct result comes back. Should we look into changing that order or is there an underlying problem that this is simply a symptom of and should be addressed at the root?

Thoughts?

**Comment by orangejulius** [comment]
Do you happen to remember some example api queries that return different results?

**Comment by dianashk** [comment]
`New York, New York` is the only one i played around with

**Comment by orangejulius** [comment]
This tickets pretty old, and we've reworked most of the internals for filtering by layer, and it feels like this hasn't been an issue in a long time (although I'm not sure we ever figured out what was happening.)

At the moment, these two queries return the same results, so I think it's safe to close the issue.
http://pelias.github.io/compare/#/v1/search%3Flayers=region,localadmin,locality&text=New%20York,%20New%20York
http://pelias.github.io/compare/#/v1/search%3Flayers=region,locality,localadmin&text=New%20York,%20New%20York

![screenshot from 2016-07-05 15-14-49](https://cloud.githubusercontent.com/assets/111716/16596711/3af8e1f2-42c3-11e6-8811-ec45dd7162fc.png)
