### ISSUE TITLE
Query parser is too restrictive with certain languages

### ISSUE THREAD

**Issue by hannesj** [pelias/api#194]
Currently the search doesn't find any addresses in Finnish, if the user doesn't specify a street number, even if both the street name and city have been specified.

[Example](http://pelias.mapzen.com/search?input=Opastinsilta,%20Helsinki)

However, if you explicitly specify to include the address layer it works correctly [(example)](http://pelias.mapzen.com/search?input=Opastinsilta,%20Helsinki&layers=address).

This has to do with the fact that most of Finnish street names are compound words, and thus, "Opastinsilta, Helsinki" becomes only two tokens. It is also confusing to the users that it works some times, e.g. when the street name contains a personal name [(example)](http://pelias.mapzen.com/search?input=Urho%20Kekkosen%20katu,%20Helsinki).

**Comment by riordan** [comment]
Thanks for flagging, @hannesj. We think it may have something to do with our new address parser. We've been noticing something similar ourselves this week.

Luckily we have a possible target cause, which is that it's restricting the search to only certain layers, and without a numeral it's not looking at streets. We're on it!

**Comment by hkrishna** [comment]
@hannesj when we implemented the address parser as a first pass we implemented for US address (we use [addressIt](https://github.com/DamonOehlman/addressit) module and here is the [default fallback](https://github.com/DamonOehlman/addressit/blob/master/index.js#L55) to US)

As the next step - we want to add support for other country specific address formats and ideally the query parser should be able to detect addresses and apply the right parser (or at the very least - a param for example ```country=FR``` or ```country=US``` that lets the API know what address parser to use.. )

**Comment by hannesj** [comment]
Hi @hkrishna,

It seems [this](https://github.com/pelias/api/blob/master/helper/query_parser.js#L31) piece of code is responsible for the behaviour. The issue is that in Finnish, a street name can be only one token, and thus the address layer is not used in the query.

**Comment by dianashk** [comment]
This should be resolved once @orangejulius does away with the target_layers logic as part of the fix for pelias/api#181

**Comment by orangejulius** [comment]
Good catch. I just dove into the code responsible for this, so the fix was quite quick.

**Comment by hannesj** [comment]
Works now, thanks
