### ISSUE TITLE
v1 place endpoint should accommodate multiple places per request

### ISSUE THREAD

**Issue by riordan** [pelias/api#197]
`/v1/place?` endpoint (pelias/api#196) should be able to accommodate a single place ID request based on a document's ID or a list of places as a comma separated list.

In the current implementation `/doc` returns the GeoJSON document for for each place's document.

In our updated implementation, for a single place request, it should naively return the document as it does now.

For a multi-place request, it should combine all the requested features into a FeatureCollection, ordered by the order the documents were requested.

If a user requests a list of place ID's has one or more is invalid, but at least one place is valid, the response should return 200, but include an error block in the JSON noting the ID's that failed.

**Comment by riordan** [comment]
We may want to use [Elasticsearch Ids queries](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-ids-query.html) to enable this feature.

**Comment by orangejulius** [comment]
This was fixed a while back by #273 and #204
