### ISSUE TITLE
Unable to specify individual admin layers on coarse endpoint

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#203]
Say you want to search for documents only in specific layers, say admin1s (corresponding to states here in the...states). You can easily do a query like http://pelias.mapzen.com/search?input=michigan&layers=admin1 and everything works out.

However, the same query against the coarse endpoint will not limit to an individual admin layer. Instead it will search all admin layers: http://pelias.mapzen.com/search/coarse?input=michigan&layers=admin1

Searching all admin layers is, of course, the correct behavior for coarse, but it should still be possible to limit which admin layers are searched.

**Comment by riordan** [comment]
:+1: to this.

At the very least, we should get it out of the documentation, where it's implied that it is [exactly the same as non-coarse](https://github.com/pelias/api/blob/master/DOCS.md#searchcoarse)

**Comment by orangejulius** [comment]
We'll actually solve this with #176
