### ISSUE TITLE
Check if geonames import uses admin-lookup

### ISSUE THREAD

**Issue by dianashk** [pelias/api#216]
It should, or else we get strange results that don't match other things

example search for "hackney"

**Comment by missinglink** [comment]
this geonames record has admin info attached:

```bash
{
  "type": "Feature",
  "properties": {
    "id": "2647694",
    "gid": "gn:locality:2647694",
    "layer": "locality",
    "source": "gn",
    "name": "Hackney",
    "country_a": "GBR",
    "country": "United Kingdom",
    "region": "England",
    "county": "Greater London",
    "locality": "London",
    "confidence": 0.719,
    "label": "Hackney, Greater London, United Kingdom"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -0.05,
      51.55
    ]
  }
}
```

could you paste a copy of the record where you noticed the error?

**Comment by missinglink** [comment]
What exactly do you mean by "get strange results that don't match other things"?

**Comment by dianashk** [comment]
It currently doesn't use the admin lookup and will not in the future. It's also going away in favor of WOF.
