### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by isandeep41** [pelias/api#217]
Hi

I'm getting invalid path for all endpoints.
**Query:**
http://localhost:3100/search?lat=51.533&lon=-0.0652&input=museum&size=40
**Result:**
{"error":"not found: invalid path"}

**Comment by riordan** [comment]
I've got a few questions that might help us sort things out.

Are you running a self-hosted version of Pelias and not from [pelias.mapzen.com](https://pelias.mapzen.com)? (From the URL structure I'm going to guess "yes").

If you are self-hosting, are you using the [Vagrant image](https://github.com/pelias/vagrant) or your own custom install?

When you say "All endpoints", does this include [http://localhost:3100](http://localhost:3100)? If so for the latter, and you're running the vagrant image, you may want to ensure that port 3100 is being forwarded properly or that you're not already running something on port 3100 locally. In that case, you'll want to go into your [Vagrantimage](https://github.com/pelias/vagrant/blob/master/Vagrantfile#L74) file and change your host port to something other than 3100.

**Comment by isandeep41** [comment]
Hello David

Thanks for your quick response.

I've installed following pelias project on my local ubuntu machine as well as on one amazon EC2 instance:
1. **pelias/openstreetmap**
2. **pelias/schema**

I've already indexed center_point (lat, lon), admin0, admin1, locality etc from planet.pbf.
I am also able to do search query on elasticsearch server through curl and getting search results.

**Problem:**
A. I've installed another pelias project **pelias/api** and run **npm start**
Getting this message on console : **worker: listening on 310**, but not able to do search, reverse query.
Let me know if I missed any required pelias project.

B. On my amazon ec2 instance, I've cloned **pelias/api**, but when running **npm install**, I'm getting below errors
```ruby
npm http 304 https://registry.npmjs.org/precommit-hook
npm ERR! git clone git://github.com/missinglink/cluster2.git Cloning into bare repository '/home/user/.npm/_git-remotes/git-github-com-missinglink-cluster2-git-b979c135'...
npm ERR! git clone git://github.com/missinglink/cluster2.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/missinglink/cluster2.git github.com[0: 192.30.252.131]: errno=Connection timed out
npm ERR! Error: Command failed: Cloning into bare repository '/home/user/.npm/_git-remotes/git-github-com-missinglink-cluster2-git-b979c135'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=Connection timed out
```

**Comment by isandeep41** [comment]
Resolved.

**Comment by riordan** [comment]
Awesome. How'd you manage to resolve it?

**Comment by isandeep41** [comment]
In first issue, I was using wrong path.
In second issue, I had to open ports in ec2 security group.
