### ISSUE TITLE
Address parser doesn't detect region (US state) without spaces

### ISSUE THREAD

**Issue by dianashk** [pelias/api#218]
Example:

`http://localhost:3100/v1/search?input=30 warwickshire rd, pa`

will be parsed properly:

```
query: {
  input: "3437 warwickshire rd, pa",
  parsed_input: {
    name: "3437 warwickshire rd",
    number: 3437,
    street: "warwickshire rd",
    state: "PA",
    regions: [ ],
    admin_parts: "pa"
  }
}
```

however, if you remove the space between `pa` and the preceding comma, you get a result that looks like this:

```
  query: {
    input: "3437 warwickshire rd,pa",
    parsed_input: {
    name: "3437 warwickshire rd",
    regions: [
      "3437 warwickshire rd",
      "pa"
    ],
    admin_parts: "pa"
  }
}
```

**Comment by dianashk** [comment]
Get involved with libpostal to see how close we are to integrating with it.

**Comment by stephenkhess** [comment]
Another example:

http://search.mapzen.com/v1/search?api_key=search-xDYkNp8&text=14%203rd%20Avenue%20NW,Chisholm,MN,55719

vs

http://search.mapzen.com/v1/search?api_key=search-xDYkNp8&text=14%203rd%20Avenue%20NW,%20Chisholm,%20MN,%2055719
