### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by millenbop** [pelias/api#224]
Which character encoding us used? UTF-8?

Sometimes characters are shown correctly, sometimes not. Here's a screenshot from https://mapzen.com/pelias

![screen shot 2015-09-08 at 09 21 39](https://cloud.githubusercontent.com/assets/12835674/9728840/29787ad2-560b-11e5-9aa1-59a341c37659.png)

**Comment by missinglink** [comment]
thanks @millenbop we are in the process of fixing the encoding issues, I'm closing this ticket in favour of https://github.com/pelias/quattroshapes-patch/issues/9 as that issue has more detail.

thanks for the bug report, if you hit `subscribe` on that issue we will alert you once it's fixed.

we have also recently released a blog article which outlines our long-term plan for dealing with hierarchical geographic regions, translations of.. (and more!) https://mapzen.com/blog/who-s-on-first

**Comment by millenbop** [comment]
Thanks! I did a search but didn't find anything. Glad to hear you're on it!
