### ISSUE TITLE
Reverse geocoding should return distance from point

### ISSUE THREAD

**Issue by riordan** [pelias/api#225]
When a user reverse geocodes a point, one of the properties that should be returned back to the user should be the distance from the matching reverse point to the origin point of the query.

Should return in meters.

**Comment by riordan** [comment]
@dianashk points out: this is already part of the response from ES on reverse queries, so shouldn't be any more computationally expensive to add it to the response.

**Comment by dianashk** [comment]
I was wrong about it being part of the response in reverse queries. See attached PR for implementation details and workaround.
