### ISSUE TITLE
caching strategy / etags

### ISSUE THREAD

**Issue by missinglink** [pelias/api#23]
The API etags are messed up because of the `date` property in the body changing all the time.

The etag should be the same for the same content.

A few fixes come to mind:
1) move date to header, may be hard for ajax consumers to deal with
2) remove date, will be hard for frontends to handle stale `/suggest` requests
3) manually compute the etag then add the date
4) something else

Personally; I would prefer to completely drop etags in favour of `max-age` headers as they are more performant due to making far less network requests and they are well suited for content which doesn't change often.

With any solution there will be an issue with the `date` property; which exists to ensure that database & network congestion doesn't cause older requests to change the UI after a newer request has already been received and rendered.

Some serious thought needs to go in to ideal cache control strategies; which account for near-side and far-side caching, mobile experience and typeahead UI.

ref: http://vadmyst.blogspot.de/2005/09/server-side-etag-vs-cache-control-max.html

**Comment by orangejulius** [comment]
We have caching now, :tada:
