### ISSUE TITLE
Non-versioned health check endpoint

### ISSUE THREAD

**Issue by heffergm** [pelias/api#231]
The API should provide a request path that isn't versioned which can be used as a health check endpoint behind load balancing software/hardware (ELB, proxy, etc).

example: /status

In it's most basic form the uri should return a 200 status code for a GET request, and some body, e.g. 'status: ok'.

**Comment by riordan** [comment]
:thumbsup:

I imagine we'd want this to be a check into the whole system, both the
API and ES. So when something hits this endpoint, it would be:

- uncached
- excecuting on the API/node (a cursory health check in its own right)
- and asking Elasticsearch for its [cluster
health](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html)


On 9/10/15 10:42, Grant Heffernan wrote:
>
> The API should provide a request path that isn't versioned which can
> be used as a health check endpoint behind load balancing
> software/hardware (ELB, proxy, etc).
>
> example: /status
>
> In it's most basic form the uri should return a 200 status code for a
> GET request, and some body, e.g. 'status: ok'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/231>.
>

-- 
-- 
David Riordan | Product Manager - Search | Mapzen
dave.riordan@mapzen.com | @riordan | gpg 235D 9DC9 5EF6 277C
https://mapzen.com | @mapzen

**Comment by heffergm** [comment]
Checking the cluster health as a precursor to returning a successfully API status response is not a good idea. There are a variety of reasons the cluster could be in a non-green state, i.e. red or yellow, where the current live index is still perfectly functional.

Two examples would be:
- adding replicas (yellow)
- restoring a new index (red)

**Comment by riordan** [comment]
So you're thinking of keeping it just to the API?

On 9/10/15 11:28, Grant Heffernan wrote:
>
> Checking the cluster health as a precursor to returning a successfully
> API status response is not a good idea. There are a variety of reasons
> the cluster could be in a non-green state, i.e. red or yellow, where
> the current live index is still perfectly functional.
>
> Two examples would be:
>
>   * adding replicas (yellow)
>   * restoring a new index (red)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/231#issuecomment-139281431>.
>

-- 
-- 
David Riordan | Product Manager - Search | Mapzen
dave.riordan@mapzen.com | @riordan | gpg 235D 9DC9 5EF6 277C
https://mapzen.com | @mapzen

**Comment by heffergm** [comment]
If we want verify as part of the check that we're receiving data from the backend, we can do that with a requests, which is essentially what had been happening in the past. That was recently changed at other's behest to avoid the additional traffic and instead just use an URL that only impacts the API.

There are up and downsides either way, but given the existing setup and monitoring on the backend, I'm fine with just have the ELB status check endpoint only hit the API.

If we want to set up some other sort of health endpoint that returns a more in depth status that we want to use to set up checks against we can do that separately.
