### ISSUE TITLE
Inadequate data to construct request to /place endpoint with data from /search

### ISSUE THREAD

**Issue by riordan** [pelias/api#238]
We should normalize the way we mint our IDs (or at least display them to users) so that the `id` field of a geocode response can be used to retrieve a complete place record on the `/place` endpoint.

Steps to reproduce:
- Search for `http://pelias.bigdev.mapzen.com/v1/search?text=hackney&size=1'
 - get `id : '937569400"' as document ID. I know more than the average user, and know how we used to construct these. I get back `source : "osm"`.
- Try to retrieve document at: `http://pelias.bigdev.mapzen.com/v1/place?id=937569400`. Fails.
 - Gets non-GeocodeJSON error: ```{error: "invalid: must be of the format type:id for ex: 'geoname:4163334'"}'''
- Try to retrieve document at: `http://pelias.bigdev.mapzen.com/v1/place?id=osm:937569400`
 - Gets non-GeocodeJSON error: ```{error: "osm is invalid. It must be one of these values - [geoname, osmnode, osmway, admin0, admin1, admin2, neighborhood, locality, local_admin, osmaddress, openaddresses]"}```

**Comment by dianashk** [comment]
As part of this, can we change `id` to `ids` to match other parameters that accept arrays of values.

**Comment by orangejulius** [comment]
Yeah, this and #259 should be easy to tackle at once

**Comment by riordan** [comment]
:thumbsup:

On Tue, Sep 15, 2015 at 3:07 PM, Julian Simioni <notifications@github.com>
wrote:

> Yeah, this and #259 <https://github.com/pelias/api/issues/259> should be
> easy to tackle at once
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/238#issuecomment-140504268>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by dianashk** [comment]
One more thing on this: we need to change the ids by appending `source`:`layer`:`id`, not `index_name`:`id` because as far as the end user is concerned, they don't know anything about the index names, like `osmway` for example.

**Comment by dianashk** [comment]
Remove `id` and add `gid` with the new format.
