### ISSUE TITLE
Implement/rename boundary parameters for /search endpoint

### ISSUE THREAD

**Issue by riordan** [pelias/api#240]
Related to #198, which implements `focus`, `boundary`'s laid back cousin. Also related to #237, which sets the names & operations for scoping to datasets.

As per our [parameter design](https://docs.google.com/spreadsheets/d/1lwtHT0-l-0gzYKdTKx8cZysnEMZKq2vASf0buyieSaI/edit#gid=1064303532) implement and rename `boundary` elements of `/search`:

- [ ] `boundary.rect`
 - `boundary.rect.min_lon`
 - `boundary.rect.min_lat`
 - `boundary.rect.max_lon`
 - `boundary.rect.max_lat`
- [ ] `boundary.circle`
 - `boundary.circle.lon`
 - `boundary.circle.lat`
 - `boundary.circle.radius`
- [ ] `boundary.country`

**Comment by orangejulius** [comment]
@missinglink fixed this one in #280 :)
