### ISSUE TITLE
Fatal error if only part of a geo param is provided

### ISSUE THREAD

**Issue by dianashk** [pelias/api#258]
For example autocomplete allows only `focus.point.lat` to be specified and doesn't complain about missing `focus.point.lon`. This should be validated for all `focus` and `boundary` params.

**Comment by orangejulius** [comment]
This looks fixed, can anyone else confirm? 

    julian@julian-mapzen ~/repos/pelias/api $  curl "http://localhost:3100/v1/autocomplete?text=foo&focus.point.lat=50"
    {
    "geocoding": {
    "version": "0.1",
    "attribution": "http:\/\/pelias.mapzen.com\/v1\/attribution",
    "query": {
      "text": "foo",
      "parsed_text": {
        
      },
      "size": 10,
      "private": false
    },
    "errors": [
      "missing point param 'focus.point' requires all of: 'lat','lon' to be present"
    ],
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1443043989231
     },
    "type": "FeatureCollection",
    "features": [
    
      ]
    }

**Comment by missinglink** [comment]
confirmed it was fixed in https://github.com/pelias/api/commit/82ab899eccbcff1d6af7823eeee3076a29579b26#diff-0ff1e8ae717210a3c2a5e98c22935c76
