### ISSUE TITLE
accuracy of /search

### ISSUE THREAD

**Issue by missinglink** [pelias/api#26]
the weighting of `/search` still isn't quite right, see example below:

Search for `brooklyn bridge park` only seems to work when you are right on top of it; it should return as the top result even when you are a few degrees away.

http://pelias.mapzen.com/search?input=brooklyn%20bridge%20park&lat=40.70443425&lon=-73.9895280691551

vs.

http://pelias.mapzen.com/search?input=brooklyn%20bridge%20park&lat=40.830000000000005&lon=-73.63888890000001

**Comment by dianashk** [comment]
Seems to have been resolved. Both queries now return the same results.
