### ISSUE TITLE
`boundary.circle.lat` `boundary.circle.lon` for `/reverse` should be equal to `point.lat` and `point.lon`

### ISSUE THREAD

**Issue by dianashk** [pelias/api#261]
`boundary.circle.lat` `boundary.circle.lon` for `/reverse` should be equal to `point.lat` and `point.lon` Also always set `boundary.circle.radius` to the default if not provided.

**Comment by dianashk** [comment]
Add warning that boundary.circle is being ignored.

**Comment by stephenkhess** [comment]
code branched from master already sets `boundary.cirlce.lat`/`boundary.circle.lon` to `point.lat`/`point.lon`, so this task is now just to set `boundary.circle.radius` to value in `defaults.js` and warn that `boundary.circle` will be ignored.

**Comment by stephenkhess** [comment]
Only add warning if anything matching boundary.circle.(lat|lon|radius) is specified
