### ISSUE TITLE
Suggest name of cities/streets

### ISSUE THREAD

**Issue by TigranTsat** [pelias/api#264]
Hello,

What will be the best API and it's parameters to suggest cities and streets names, assuming that country is known (for street names, assuming that country and city is known).
I tried
http://pelias.mapzen.com/search/coarse?input=prague&layers=locality&size=40
or
http://pelias.mapzen.com/suggest/coarse?input=prague&layers=locality&size=40
but it gives not good results. For some cities [London, Paris, Tokyo] it gives first result. For some [Prague, Berlin] it gives result somewhere in the middle (like 17th position or so). For some [florence, Munich] it returns only locations in the usa or returns nothing. Am I missing something?

Thank you.

Update: I started using http://pelias.mapzen.com/suggest?input=munich&size=40 which looks like solved partly my issue, but how to specify country.
This one works not that well: http://pelias.mapzen.com/suggest?input=leon,France&size=40

P.S. If you have mailer, can ask question there.

**Comment by orangejulius** [comment]
Hi @TigranTsat,
Your queries are pretty close to what I think you want, but let me suggest some other options. 

Also, we've just launched an official first version of the Pelias API (the api calls you list will still be around for some time, but are part of our beta release), so I'm going to be using this new API. It requires an [API key](https://mapzen.com/developers) but they're free and always will be.

## Key differences in V1
A couple to note real quick that changed in V1.

We completely removed the `/search/coarse` endpoint, instead you can use `layers=coarse`. Alternatively you can pick layers individually. Locality is the right layer for cities

Second, all the URLs have /v1/ as a prefix. This lets us keep v1 stable even when we someday release v2 to improve the API further.

Finally, the `input` parameter is now `text`

## Finding cities
You'll be happy to know we added a way to filter by country, you can use the boundary.country parameter on `/v1/search` with an [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) country code. Either the 2 or 3 character variant is fine, and we'll let you know if you used an invalid one.

I got good results with queries like this:

 `/v1/search?boundary.country=CZE&text=prague`
`/v1/search?boundary.country=DEU&text=munich`


## Finding streets
Streets themselves are hard to find. We don't have line data for them at the moment (we plan to soon), so even if you do find a street, it will just be a single point, which may not be interesting. However you can find lots of addresses on a street. And while we don't have a way to filter by city, appending the city name after a comma should generally help.

`/v1/search?boundary.country=DEU&text=Torstraße, berlin`
`/v1/search?boundary.country=USA&text=Hollywood Blvd, Los Angeles`
`/v1/search?boundary.country=GB&text=Abbey Road, London`

If you have any other questions please reach out to us again or read the new [documentation](https://github.com/pelias/pelias-doc)

**Comment by riordan** [comment]
@TigranTsat Thanks for writing in. This is actually going to be a part of our upcoming knowledge base.

If you've got any further questions, let us know here, or drop us a line at [search@mapzen.com](mailto:search@mapzen.com).
