### ISSUE TITLE
Searching for a venue by address doesn't find the venue

### ISSUE THREAD

**Issue by dianashk** [pelias/api#283]
When we search for `Samsung Accelerator` we get back the venue with that name and the correct address. However, when we search for the address, we don't get back that particular result, with Samsung Accelerator as the name. We only see addresses. The addresses all match, but they are just addresses. This is problematic.

**Comment by dianashk** [comment]
Related to alt_names.

**Comment by riordan** [comment]
Should be fixed by:
pelias/schema#77
pelias/api#356

Also a fix for:
pelias/pelias#172

**Comment by riordan** [comment]
Needs acceptance tests:
- [ ] Acceptance tests

**Comment by dianashk** [comment]
Test added to acceptance tests. (see pelias/acceptance-tests#181)
Marked as failing for now, as this doesn't seem to be fixed. 
Leaving issue open until further prioritization.

**Comment by riordan** [comment]
I'm not sure this is a problem.

Searching for an address should ensure an address is returned, not necessarily to provide the _value add_ of telling you what the venue is. Venues are more prone to change and less comprehensively noted than addresses. Meanwhile addresses may be created in Openaddresses for venues created in OSM.

I propose we table this for the time being.

**Comment by trescube** [comment]
This won't be supported so remove acceptance test.

**Comment by missinglink** [comment]
closing: we removed the test in https://github.com/pelias/acceptance-tests/pull/287
