### ISSUE TITLE
Inconsistent prefixes for place ids, use source instead and/or return full id in search

### ISSUE THREAD

**Issue by jthi3rry** [pelias/api#284]
Hi there,

When making a call to the `place` endpoint with `ids`, it asks for all ids to be prefixed with a some kind of type and returns this error otherwise:

> [whatever id] is invalid. It must be one of these values - [geoname, osmnode, osmway, admin0, admin1, admin2, neighborhood, locality, local_admin, osmaddress, openaddresses]

The problem is that some of these values don't correspond to anything in the results from the `search` or `reverse` endpoints.

For the `country` layer, the place endpoint expects `admin0`, for `region`, it expects `admin1` and so on. Which can certainly be mapped by the client, be may as well be done by the server.

Also, the British spelling of `neighbourhood` is used by `search` vs. the American spelling (`neighborhood`) for `place`, and `localadmin` in the first becomes `local_admin` in the second. 

Here are a few example results for quattroshapes:

```
{
    "layer": "country",
    "name": "New Zealand",
    "country": "New Zealand",
    "label": "New Zealand",
    "source": "qs",
    "country_a": "NZL",
    "id": "315:adm0:nz:nzl:_"
}
```

```
{
    "layer": "neighbourhood",
    "name": "Parnell",
    "country": "New Zealand",
    "region": "Auckland Region",
    "label": "Parnell, Auckland, Auckland Region",
    "county": "Auckland",
    "source": "qs",
    "country_a": "NZL",
    "id": "2184:_:_:nzl:parnell"
}
```

The `place` endpoint expects these ids:
* `admin0:315:adm0:nz:nzl:_`
* `neighborhood:2184:_:_:nzl:parnell`

Assuming all ids are unique per source, could the source be used as a prefix instead? More generally, could the properties returned when searching or reverse geo-coding contain the exact id that's expected by the `place` endpoint?

Thanks,
Thierry

**Comment by orangejulius** [comment]
>could the properties returned when searching or reverse geo-coding contain the exact id that's expected by the `place` endpoint?

Funny you should ask about this just now, as I'm working on exactly this at the moment! There will be a `gid` property with a value that can be sent right to the place endpoint. Look for it in the next couple days.

Thanks for the feedback :)

**Comment by jthi3rry** [comment]
That's awesome! Thanks @orangejulius :-)

**Comment by missinglink** [comment]
hey @jthi3rry you might find the `boundary.country` param useful eg: `/v1/search?boundary.country=NZL&text=kia ora` on the `/search` endpoint.

**Comment by jthi3rry** [comment]
Hey @missinglink, thanks for that, it's really cool! :-)
