### ISSUE TITLE
Error responses are not CORS-enabled, so JavaScript cannot access error states

### ISSUE THREAD

**Issue by louh** [pelias/api#296]
If I do something that results in an error response, let's say, for the sake of argument, that I type really fast during autocomplete and it blows out the rate limit, it returns with HTTP status code 429. In the browser's console, it will show a message like this:

```
XMLHttpRequest cannot load https://search.mapzen.com/v1/autocomplete?text=iwish hi had asdkjllfl…0os kdu ualka%3Bskd laksd%3Blsakdl%3Bskd%3Blk&api_key=search-MKZrG6M. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 429.
```

Although the console is reporting it, the browser actually refuses to make any of this information available to the page's JavaScript, _because_ CORS is not enabled on this response. If I try to examine the status of the XMLHttpRequest, for example, `XMLHttpRequest.status` won't return 429 as I would expect, but rather `0`. 

Because there's no way for the application to know what the actual error was, I can't write any handlers to decide what to do when the request fails. It might be an API key problem (403) or a server failure (500) or rate limited (429) and my app will not be able to handle these cases differently.

According to @heffergm this is a problem on the proxy side, but I'm filing it here for reference.

**Comment by heffergm** [comment]
This is not entirely a proxy side concern. For response codes issued by the proxy that are not passed through to the origin, e.g. 429 rate limited responses, this is true. However, all other responses from the origin will need to include the relevant headers as well.

**Comment by heffergm** [comment]
If we enable cors support on the proxy layer we'll get headers for all responses. But we'd either need a means of disabling them in the API or making sure the response headers match what the proxy is returning to avoid duplicates due to differing case (as below). cc @baldur

```
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH, HEAD
< Access-Control-Allow-Headers: Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token
< Access-Control-Expose-Headers: content-type, content-length, X-ApiaxleProxy-Qps-Left, X-ApiaxleProxy-Qpd-Left
< X-ApiaxleProxy-Qps-Left: 0
< X-ApiaxleProxy-Qpd-Left: 27790
< access-control-allow-credentials: true
< access-control-allow-headers: X-Requested-With,content-type
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-origin: *
```

**Comment by missinglink** [comment]
The lowercase issue is weird, I've not seen that before...

here is the code for our [api headers](https://github.com/pelias/api/blob/master/middleware/cors.js) and
the [apiaxle headers(https://github.com/apiaxle/apiaxle/blob/413bf526daa8fc0741c763a0a40b56726a09f190/proxy/apiaxle-proxy.coffee#L374-L381)  which are both UpperCase, where are these lowercase headers coming from?

**Comment by heffergm** [comment]
:sigh: yeah, there seems to be some alteration going on somewhere along the way.

```
grant@api1:~$ curl -v "http://localhost:3000/v1/autocomplete?text=gas"

< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: X-Requested-With,content-type
< Access-Control-Allow-Credentials: true
```


```
grant: ~$ curl -v "https://search.mapzen.com/v1/autocomplete?text=gas&api_key=redacted

< HTTP/1.1 200 OK
< access-control-allow-credentials: true
< access-control-allow-headers: X-Requested-With,content-type
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-origin: *
```

**Comment by missinglink** [comment]
upstream PR opened https://github.com/apiaxle/apiaxle/pull/77

**Comment by missinglink** [comment]
@heffergm I'd prefer to fix the proxy implementation so that CORS works without configuration in both local and production environments, but if that fails I'll have to add a feature flag.

**Comment by heffergm** [comment]
This is currently 'fixed' in that you'll now be seeing CORS headers for all responses. This is due to modification at the new funnel point for all queries (edge cache):

```
sub vcl_deliver {
set resp.http.Access-Control-Allow-Origin = "*";
set resp.http.Access-Control-Allow-Credentials = "true";
set resp.http.Access-Control-Allow-Methods = "GET, HEAD";
set resp.http.Access-Control-Allow-Headers = "Authorization, Content-Type, Accept, Origin, User-Agent, Cache-Control, Keep-Alive, If-Modified-Since, If-None-Match";
set resp.http.Access-Control-Expose-Headers = "Content-Type, Cache-Control, ETag, Expires, Last-Modified, Content-Length";
set resp.http.Server = req.http.X-Fastly-Server;
```

Can leave this open or close as you like to wait for the upstream apiaxle fix or not, but functionally the behavior is as requested.

**Comment by louh** [comment]
:+1: I noticed this. Thank you!

I'll let Pelias team decide whether they still want to leave this open.
