### ISSUE TITLE
gid disappeared

### ISSUE THREAD

**Issue by jthi3rry** [pelias/api#298]
After 62315a1775ba655cf70222445aecf78b6ea42d03, it seems the `gid` introduced in #292 is no longer returned in the properties.

It is still there in the previous revision, 1c066b65e73c6f4a11722ae889f174f0b3b27291.

**Comment by jthi3rry** [comment]
Weird, latest revision (#299)  seems to have it again. Please ignore.

**Comment by orangejulius** [comment]
no worries. looks good on our end too. enjoy the gids :)
