### ISSUE TITLE
security: express middleware

### ISSUE THREAD

**Issue by missinglink** [pelias/api#3]
investigate https://github.com/evilpacket/helmet and possibly talk to adam.

this ticket is to review the `helmet` npm module and establish if including some of their functionality in our app will decrease the risk of malicious attack.

security is always important, we are only storing open data which is freely available anyway and no personal data so theft is not an issue but we have a responsibility to ensure security for our users as best we can.

"express is a very thin http framework, the heavy lifting is done by the middleware and their philosophy continues to be to have as little as possible enabled by default"

**Comment by sevko** [comment]
Is this still an issue?

**Comment by riordan** [comment]
@missinglink Necessary to support EraserMap?

**Comment by riordan** [comment]
Closing, given that the service is now behind many, many layers of API middleware.

@missinglink, if you think it's still an issue, open it back up.

**Comment by missinglink** [comment]
closing. there has been a [module audit](https://github.com/pelias/api/blob/master/package.json#L15) script in this repo for some time which will give an overview of security issues with 3rd party dependencies.
