### ISSUE TITLE
Reverse geocode doesn't honor layers=country correctly

### ISSUE THREAD

**Issue by stephenkhess** [pelias/api#315]
There's an issue with reverse geocoding and layers=country in that it's returning results in layers other than country.  Here's an example request:

http://search.mapzen.com/v1/reverse?api_key=search-Bc6zSak&point.lat=42.888663&point.lon=-0.609304&layers=country

That lat/lng is just inside the France in the France/Spain border.  Until about 2pm on 9/25/2015, it was returning 1) Andorra, 2) Spain, 3) France (then others), which is correct.  Now it's returning gn:venue results that are clearly incorrect.  It has been doing this on bigdev since at least Thursday, 9/24/2015 (when I first starting playing around with reverse).

**Comment by missinglink** [comment]
yea wow, this is nasty, nice catch! I'm keen to move on to updating the schema soon so we can get rid of this source/layer confusion.
