### ISSUE TITLE
return non 200 error codes

### ISSUE THREAD

**Issue by missinglink** [pelias/api#321]
at the moment we return `200` for all requests, even if errors and warnings occur. this needs to be changed to a more `HTTP` friendly solution, and that solution needs to take in to account upsteam proxies like fastly and browser agents.

**Comment by missinglink** [comment]
eg. `500`, `400` and `408`

**Comment by orangejulius** [comment]
Did this happen when we made the changes for sanitizerAll.js? We used to return all sorts of great error codes.

**Comment by missinglink** [comment]
we used to call `next(error)` in controllers which then forwarded on to the errorController, but since we now return geoJSON on errors we needed to get everything going through `middleware/geocodeJSON.js`. I'll have a look at it now and see what I can do.
