### ISSUE TITLE
Allow override of default Elasticsearch index name via pelias config file

### ISSUE THREAD

**Issue by riordan** [pelias/api#334]
_From @heffergm on September 22, 2015 10:54_

The solution to the schema change scenario that came up yesterday in chat: allow the ability to change the database name that the API uses to issue requests to the backend via the pelias config file (currently hardcoded(?) as ‘pelias’). 

This would allow a manually rollout when there’s a breaking schema change where the live API would continue to point at the correct index until everything is in place to move to the new one.

_Copied from original issue: pelias/schema#73_

**Comment by orangejulius** [comment]
This is all done and has been successfully used in production to do a migration that would otherwise have required at least a little downtime! :tada:
