### ISSUE TITLE
Dedupe results after elasticsearch and before responding

### ISSUE THREAD

**Issue by dianashk** [pelias/api#339]
We often see multiple results from various data sources. They should be deduped so the user isn't confused.

**Comment by missinglink** [comment]
whats the plan for this? sounds like a job for WOF?

**Comment by orangejulius** [comment]
WOF won't (I don't believe) support OSM or OA, since they don't really have that stable of ids. I imagine we could do something that compares results that are both linguistically similar and very nearby, and past a certain threshold combines them somehow.

**Comment by riordan** [comment]
Lets talk about an architecture that would support this. Also deduping is an incredibly difficult problem.

**Comment by riordan** [comment]
At bare minimum, we should discuss a plan for deduplication, be it client side or at import time.

**Comment by riordan** [comment]
@stephenkhess sez: this would be a great use for [libpostal](https://github.com/openvenues/libpostal).

**Comment by riordan** [comment]
From #362:
> Results frequently have duplicate locations with the same or almost same properties. This is a result of having various data sources and consciously not deduping data among them. If a user searches for only OSM data, they should still see all the things OSM has for the given query. However, when no data source is specified, we should do our best to filter out things that look similar. We'll probably be able to select the prefered result based on source trust-factor:

* WOF
* OA
* OSM

**Comment by dianashk** [comment]
Example: `lancanster strasburg highschool`
