### ISSUE TITLE
Restore balance between POI's and Region/Locality, especially when a focus is defined

### ISSUE THREAD

**Issue by riordan** [pelias/api#346]
Last week's major rebalancing (pelias/api#341) brought some great improvements for coarse search. Unfortunately, some of these scoring changes have had a dramatic impact on POI search.

See:
`/v1/search?api_key=search-XXXXXXX&focus.point.lat=40.743987&focus.point.lon=-73.990417&text=mcdonalds`

```
 1)	McDonald, Trumbull County, OH
 2)	McDonald, Washington County, PA
 3)	McDonald, Rocewood, KS
 4)	McDonald, Robeson County, NC
 5)	Mcdonald, Burlington County, NJ
 6)	McDonald County, MO
 7)	Mcdonald, Trumbull County, OH
 8)	Mcdonald, Barry County, MO
 9)	Mcdonald, Washington County, PA
10)	Mcdonald, Robeson County, NC
```

`/v1/autocomplete?api_key=search-XXXXXXX&point.lat=40.743987&point.lon=-73.990417&text=mcdonalds`

```
 1)	McDonald, Trumbull County, OH
 2)	McDonald, Washington County, PA
 3)	McDonald, Rocewood, KS
 4)	McDonald, Robeson County, NC
 5)	Mcdonald, Burlington County, NJ
 6)	McDonald County, MO
 7)	Mcdonald, Trumbull County, OH
 8)	Mcdonald, Barry County, MO
 9)	Mcdonald, Washington County, PA
10)	Mcdonald, Robeson County, NC
```

`/v1/search?api_key=search-XXXXXXX&focus.point.lat=40.743987&focus.point.lon=-73.990417&text=starbucks`

```
 1)	Starbuck, Pope County, MN
 2)	Starbuck, Columbia County, WA
 3)	Starbuck, Columbia County, WA
 4)	Starbuck, Bottineau County, ND
 5)	Starbuck, Pope County, MN
 6)	Starbuck, Pope County, MN
 7)	Starbucks, Manhattan, NY
 8)	Starbucks, Manhattan, NY
 9)	Starbucks, Manhattan, NY
10)	Starbucks, Manhattan, NY
```

`/v1/autocomplete?api_key=pelias-D7WkrQc&point.lat=40.743987&point.lon=-73.990417&text=starbucks`

```
 1)	Starbuck, Pope County, MN
 2)	Starbuck, Columbia County, WA
 3)	Starbuck, Columbia County, WA
 4)	Starbuck, Bottineau County, ND
 5)	Starbuck, Pope County, MN
 6)	Starbuck, Pope County, MN
 7)	Town of Starbuck, Starbuck, WA
 8)	Starbucks, Los Angeles, CA
 9)	Starbucks, Ebaiu, Philippines
10)	Starbucks, Fort Collins, CO
````

I get that balance is hard, but bringing POI's back into the result set is critical for app-focused end-users like we're about to have with Eraser Map.

**Comment by riordan** [comment]
Maybe we've over-boosted counties....

We should consider lowering the power of counties, since folks don't search for them frequently. Override for Maui.

**Comment by riordan** [comment]
Lets build tests for this that's a poi plus city+state

**Comment by missinglink** [comment]
related: https://github.com/pelias/api/pull/418
