### ISSUE TITLE
Street without house number returns house numbers anyway

### ISSUE THREAD

**Issue by trescube** [pelias/api#349]
Example request:  

http://search.mapzen.com/v1/search?api_key=search-xDYkNp8&text=south%20charles%20st%20red%20lion%20pa

First result is a POI on South Charles Street, the rest are houses.

**Comment by stephenkhess** [comment]
Traditionally, there are 2 ways to handle this:

1.  return a representative block, such as the block in the middle of entire street

or

2.  return all the block ranges, like "100-199 S Charles St", "200-299 S Charles St", etc

**Comment by riordan** [comment]
+1

Streets as first-class search results are a very good stopgap where we have gaps in address data for address geocoding + a useful standalone layer in its own right.

**Comment by vesameskanen** [comment]
It would indeed be great if a street name search would return a list of streets (without numbers)  in various cities, not multiple street name + number combos in a single city. Do you have any plans/instructions how to address this? Would a new 'streets' layer help? Or perhaps importing the plain street name as a venue?

**Comment by trescube** [comment]
With our upcoming release of libpostal support in combination with address interpolation, we're planning to support just returning the street instead of houses on that street (or venues on that street).  The libpostal integration also includes query modifications to search more intelligently with fallbacks to a city when a street can't be found.  We'll need the interpolation work, however, since all of our address data is currently points.  That is, we don't currently have a street centroid to return even if we had a `streets` layers.  The address interpolation work that @missinglink is currently engaged in will expose this information allowing us to search for just a street and return a centroid.

**Comment by dianashk** [comment]
Fixed

<img width="928" alt="screen shot 2016-10-19 at 11 04 43 am" src="https://cloud.githubusercontent.com/assets/5446511/19524501/f1fd47c8-95eb-11e6-8391-5ab6fbab9911.png">
