### ISSUE TITLE
parser: fails to parse apartment numbers

### ISSUE THREAD

**Issue by missinglink** [pelias/api#355]
the address parser is making a mistake parsing `1917/2 Pike Drive`, it ends up thinking that `2` is the housenumber.

``` javascript
"query": {
  "text": "1917/2 Pike Drive",
  "parsed_text": {
    "number": 2,
    "street": "Pike Drive",
    "regions": []
  }
}
```

**Comment by riordan** [comment]
This is similar to the structure of Canadian apartment/unit notation:

123-4 Fake Street is `housenum: 123`, `unit: 4` `street: fake street`

This is complex because in Queens, the address structure is 123-4 Fake Street, where 123-4 _is_ the complete address.

**Comment by missinglink** [comment]
see also: https://en.wikipedia.org/wiki/Address_(geography)#Mailing_address_format_by_country

**Comment by dianashk** [comment]
Al is currently working on updating the training model to support this. We'll check in soon for an update.

**Comment by trescube** [comment]
Revisit sources/us/wi/dane in OA to use separated fields.

**Comment by trescube** [comment]
Ask Al to see why `/2` isn't being parsed as apt/unit
