### ISSUE TITLE
parser: fails to categorise POI name

### ISSUE THREAD

**Issue by missinglink** [pelias/api#359]
for the input `whole foods NY`, the address parser should consider `whole foods` as the `name` since it's before the `state_abbr`.

I think generally if there is text _before_ the admin components it should be considered part of the `name` and if it appears _after_ and we can't match it completely, then it can go in `regions`.

``` javascript
"query": {
  "text": "whole foods NY",
  "parsed_text": {
    "state": "NY",
    "regions": [
      "whole foods"
    ]
  }
}
```

**Comment by trescube** [comment]
fixed by libpostal

**Comment by dianashk** [comment]
Works now!

<img width="383" alt="screen shot 2017-05-04 at 3 48 00 pm" src="https://cloud.githubusercontent.com/assets/5446511/25722162/1a3790e6-30e1-11e7-9086-8ef5e227a06b.png">
