### ISSUE TITLE
Autocomplete term expansion should expand entire path

### ISSUE THREAD

**Issue by riordan** [pelias/api#372]
Resolved by Autocomplete Omnibus (pelias/pelias#165)

- [x] Needs test case.

st -> street
str -> street
stre -> street
stree -> street

But also do a search for the exact token so if there's a place called "116 stre", it can still match.

**Comment by riordan** [comment]
We know Autocomplete is jumpy. Part of that is that once someone continues to type past the first occurrence of their place in their result list, it should continue to rise in the results. When that place disappears, it's jarring.

Term expansion is a part of this.

Today, if I type `rd`, it's treated as an abbreviation of `road`, but many of these are the first parts of that term. As such, these should be expanded so that continuing to type that refines (and adds to the score) of the match.

**Comment by dianashk** [comment]
Add acceptance tests
