### ISSUE TITLE
Small focus viewport results in a decay function radius of 1km

### ISSUE THREAD

**Issue by dianashk** [pelias/api#386]
We need to set the minimum decay function radius to at least 50km in order to avoid seeing only results from very far away.

example:

https://search.mapzen.com/v1/search?text=pizza&focus.viewport.min_lat=40.737021896579215&focus.viewport.min_lon=-73.9941623804208&focus.viewport.max_lat=40.746646382007874&focus.viewport.max_lon=-73.98643761957919

**Comment by missinglink** [comment]
https://github.com/pelias/api/blob/master/query/search.js#L77

In the case of driving directions it's quite common that the user will be zoomed in to the block-level of their departure point while expecting to apply a local boost to 'pizza' etc. within a large area around them (their whole city/region).

I'm still not sure its valid to reduce the `focus:scale` value below the default value of `50km` or `250km` (proposed new value).
ref: https://github.com/pelias/api/pull/304#issuecomment-146479213

**Comment by ecgreb** [comment]
Thanks for looking into this. Just to provide a little more context the viewport params sent in this request are at the default zoom level in EM so its probably the most common use case we will have.

**Comment by missinglink** [comment]
this issue was resolved in https://github.com/pelias/api/pull/388
