### ISSUE TITLE
API returns GeoJSON bounding boxes for individual features

### ISSUE THREAD

**Issue by riordan** [pelias/api#398]
Was talking this through with @orangejulius and we thought it'd benefit from a writeup to remember what we said:

### Background
Who's on First stores polygons for administrative areas. In addition to storing the points, we can store the bounding boxes to convey the extent of the place.

@trescube's been working on getting this data into ES in pelias/schema#97 and pelias/model#23.

### API Impact
[GeoJSON: Bounding Boxes](http://geojson.org/geojson-spec.html#bounding-boxes)

#### Today

Today, when we return a set of results as GeoJSON FeatureCollection (an array of Features), we pass back a single bounding box for all the documents in the set of results.

It's what lets us zoom a map to encompass the centroids of all the places in the results.

It's the difference between 2 results for `London, England` and `London`:

![pelias_github_io_compare___v1_search_3fsize_2_text_london__20england](https://cloud.githubusercontent.com/assets/227472/12517227/b7694038-c0ff-11e5-822e-011d9b3339eb.png)

![pelias_github_io_compare___v1_search_3fsize_2_text_london](https://cloud.githubusercontent.com/assets/227472/12517200/a164ac14-c0ff-11e5-9a95-f1db59fddc7b.png)

But what it doesn't let us do is zoom in on the extent of a SINGLE place (like this search for `Canada`, that is very, very accurate in its portrayal).
![pelias_github_io_compare___v1_search_3fsize_1_text_canada](https://cloud.githubusercontent.com/assets/227472/12517269/eb8af35c-c0ff-11e5-8a64-660e76806329.png)

#### WoF-enabled API
The GeoJSON spec allows [2 kinds of bounding boxes](http://geojson.org/geojson-spec.html#bounding-boxes):
- bounding boxes describing the extent of an entire FeatureCollection (what we do today)
- bounding boxes for an individual Feature

These can be mixed together in a single document, so an API consumer can know that if they're referencing just a single result or all the results.

**Individual Matches**

We should pass along the BBOX being stored in ES so it's a part of the match for each place. This lets us convey the shape without needing to pass along the entire geometry. Yay efficiency!

** FeatureCollection Result Set **
@orangejulius points out that the current approach provides a bounding box for all centroids, and if we were to continue doing so, it could clip the outer extent of those matches. So instead we should figure out the BBOX of all the BBOXes.

This will require re-serializing the strings to ints in the API (which we'll have to do coming back from ES anyway), then calculating the outermost extents of all those bboxes.

Then the FeatureCollection BBox is the BBOX of all the BBOXes.

**Comment by riordan** [comment]
:+1:  from Mapillary's @millenbop in pelias/pelias#264

**Comment by millenbop** [comment]
Awesome stuff, thanks!

**Comment by amnesia7** [comment]
@dianashk now that this has been merged do you know how long it will be before it is available via https://search.mapzen.com/v1/autocomplete ?

**Comment by riordan** [comment]
@amnesia7 We'll be rolling this out with the rest of our [Who's on First milestone](https://waffle.io/pelias/pelias?milestone=Who%27s%20on%20First). We suspect this'll be about 2 weeks or so.

**Comment by amnesia7** [comment]
Great, thanks @riordan
