### ISSUE TITLE
Label Generation - County Parentage

### ISSUE THREAD

**Issue by trescube** [pelias/api#416]
### changed parentage

In some cases the parent name has changed, these cases need to be reviewed on a case-by-case basis and only if the change is valid then the test case should be updated.

```
# prod
  1) Portland, Multnomah County, OR

# dev
 1) Portland, Multnomah, OR
```

```
# prod
 1) Philadelphia, Philadelphia County, PA

# dev
 1) Philadelphia, PA
```

### What to do

With the exception of Louisiana and Alaska, all state counties should have 'County' appended.  Louisiana counties should have 'Parish' appended.  I'll leave it up to product decisions whether to appended Borough or Census Area to administrative areas in [Alaska](https://en.wikipedia.org/wiki/List_of_boroughs_and_census_areas_in_Alaska).

**Comment by riordan** [comment]
:+1: 

Is there an efficient way to restrict this to the US only?

**Comment by trescube** [comment]
Yes.

**Comment by trescube** [comment]
According to https://en.wikipedia.org/wiki/County#Canada, some provinces use counties as regional subdivisions, though WOF does not appear to contain that data.

**Comment by dianashk** [comment]
Spoke with @trescube and decided to try to fix this at the data source (WOF). Will be opening an issue there soon to track progress.

**Comment by trescube** [comment]
https://github.com/whosonfirst/whosonfirst-data/issues/217
