### ISSUE TITLE
Label generation does not handle duplicate heirarchy components

### ISSUE THREAD

**Issue by trescube** [pelias/api#429]
Anytime the components of the label are duplicates, the label schema we use will break.  In the example, "Luxembourg, Luxembourg" (the city in the country), the generated label is "Luxembourg".  This happens because the list of label parts is de-duped which can result in inadvertently leaving out pertinent information.  For example:

http://pelias.github.io/compare/#/v1/search%3Ftext=luxembourg,%20luxembourg

There are all sorts of bad labels in the results.  

1.  "Luxembourg, Canton de Luxembourg" - this is a city/county label where the label schema calls for country at the end, so it should be "Luxembourg, Canton de Luxembourg, Luxembourg"
2.  "Luxembourg" - this is a city label, but the label schema calls for "Luxembourg, Luxembourg"
3.  "Grand Duchy of Luxembourg, Luxembourg" - this is a name/locality label, where as the label schema says it should be "Grand Duchy of Luxembourg, Luxembourg, Luxembourg"

It appears that the schema doesn't take into account cases where a lower administrative area or venue name can have the same name as the country.  Or a venue name having the same name as any other administrative area.  

@riordan directed me to this the other day:  

https://i18napis.appspot.com/address

It contains the addressing schemes for most (if not all) of the countries.  We should probably go with that.

**Comment by trescube** [comment]
This also creates inconsistent formatting where `localadmin` and `locality` are sometimes important and sometimes not.  For example, "Manhattan, NY" gets the label:

'Manhattan, New York, NY'

whereas "Gracie Mansion, New York, NY" gets the label:

'Gracie Mansion, Manhattan, NY'

and "30 W 26th St, New York, NY" gets the label:

'30 W 26th St, Manhattan, NY'

**Comment by orangejulius** [comment]
Is there anything in this ticket that isn't solved by #497, #507, and #517? I think we can close this!

**Comment by orangejulius** [comment]
Short of the issues still a part of pelias/wof-admin-lookup#49 (country records get an extra `, Country Name` at the end), I think we've solved all these issues.

@trescube, how do the results below look?

http://pelias.github.io/compare/#/v1/search%3Ftext=Gracie%20Mansion,%20New%20York,%20NY
![screenshot from 2016-07-05 15-29-34](https://cloud.githubusercontent.com/assets/111716/16597126/5115a09a-42c5-11e6-9a46-06219ab0a581.png)

http://pelias.github.io/compare/#/v1/search%3Ftext=luxembourg,%20luxembourg
![screenshot from 2016-07-05 15-29-21](https://cloud.githubusercontent.com/assets/111716/16597139/60833d12-42c5-11e6-9342-274596af1cad.png)

**Comment by trescube** [comment]
LGTM
