### ISSUE TITLE
bulk geocoding proposal

### ISSUE THREAD

**Issue by dimfeld** [pelias/api#432]
I'm starting to implement a "bulk geocoder" feature for the Pelias API. My current design doesn't make any major changes to the API, except that it allows you to POST a JSON array to the `/v1/search` endpoint, where each item in the array is a single request. The API will then run the middleware over each item in the array and use the Elasticsearch `msearch` endpoint to quickly perform all the searches at once. There will also be some way to configure a maximum amount of searches that can be submitted in one request.

I'll be glad to submit a PR for this once I have it working; are you interested in integrating such a feature into Pelias? And if so, do you have any feedback on how you'd like it to look?

**Comment by riordan** [comment]
@dimfeld this is really awesome and actually something we've been thinking a bit about ourselves. It'd be great to hear a bit more about your perspective on this. Is there any chance we could chat next week? I think our team could really benefit.

**Comment by dimfeld** [comment]
Sure, sounds good. I think Monday or Tuesday will work best; send me an email at my username at gmail.com and we can set up a time. Also I have my WIP code at github.com/Carevoyance/pelias-api, if you care to check it out.

**Comment by orangejulius** [comment]
Closing this, we have https://github.com/pelias/scripts-batch-search which uses existing Pelias APIs in a convenient package. I don't believe Pelias needs a dedicated batch endpoint, as the main determinant of performance will be the hardware given to Pelias, rather than the way queries are sent to Pelias.
