### ISSUE TITLE
Problem with precommit hooks

### ISSUE THREAD

**Issue by vesameskanen** [pelias/api#433]
Precommit hooks fail here in a brand new clone of the pelias api master branch:

npm ERR! extraneous: ecc-jsbn@0.1.1 /home/meskave/digitransit/hsl-api/node_modules/ecc-jsbn
npm ERR! extraneous: jodid25519@1.0.2 /home/meskave/digitransit/hsl-api/node_modules/jodid25519
npm ERR! extraneous: npmlog@2.0.2 /home/meskave/digitransit/hsl-api/node_modules/npmlog
npm ERR! extraneous: source-map@0.1.43 /home/meskave/digitransit/hsl-api/node_modules/source-map
npm ERR! extraneous: tweetnacl@0.14.1 /home/meskave/digitransit/hsl-api/node_modules/tweetnacl
npm ERR! extraneous: brfs@1.4.1 /home/meskave/digitransit/hsl-api/node_modules/brfs
npm ERR! extraneous: browserify@12.0.1 /home/meskave/digitransit/hsl-api/node_modules/browserify
npm ERR! extraneous: uglifyjs@2.4.10 /home/meskave/digitransit/hsl-api/node_modules/uglifyjs
npm ERR! extraneous: zlib-browserify@0.0.3 /home/meskave/digitransit/hsl-api/node_modules/zlib-browserify
npm ERR! extraneous: source-map@0.2.0 /home/meskave/digitransit/hsl-api/node_modules/istanbul/node_modules/source-map

These are not listed as direct dependencies in package.json, but get installed anyway. Any thoughts what could cause this?

**Comment by missinglink** [comment]
this happens to me sometimes when I have extra dependencies in `./node_modules` that are not listed in the `package.json`. 

I can't reproduce on a fresh clone on my end, I suspect you may have executed `npm install xxx` a few times in that directory.

```bash
peter: ~$ cd /tmp && git clone git@github.com:pelias/api.git && cd api
Cloning into 'api'...
remote: Counting objects: 7194, done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 7194 (delta 156), reused 0 (delta 0), pack-reused 6907
Receiving objects: 100% (7194/7194), 1.04 MiB | 430.00 KiB/s, done.
Resolving deltas: 100% (5049/5049), done.
Checking connectivity... done.
```

```bash
peter: /tmp/api (master)$ npm i
... lots of output here
```

```bash
peter: /tmp/api (master)$ git commit
running lint...passed!
running validate...passed!
running test...passed!
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

```bash
peter: /tmp/api (master)$ git log -1
commit 5419c8dfa7766ebeb34e8c0f73a5ef4dccf9cdd7
Merge: 70caa5b 0c3e4de
Author: Julian Simioni <julian@simioni.org>
Date:   Tue Mar 1 11:30:59 2016 -0800

    Merge pull request #427 from pelias/greenkeeper-pelias-schema-3.0.0
    
    Update pelias-schema to version 3.0.0 <U+1F680>
```

```
peter: /tmp/api (master)$ tree -d -L 1 node_modules/
node_modules/
├── addressit
├── async
├── check-types
├── ciao
├── cluster2
├── express
├── express-http-proxy
├── extend
├── geojson
├── geojson-extent
├── geolib
├── geopipes-elasticsearch-backend
├── iso3166-1
├── istanbul
├── jshint
├── lodash
├── markdown
├── morgan
├── nsp
├── pelias-config
├── pelias-esclient
├── pelias-logger
├── pelias-query
├── pelias-schema
├── pelias-suggester-pipeline
├── precommit-hook
├── proxyquire
├── stats-lite
├── tap-dot
├── tape
└── through2

31 directories
```

Hope that helps, I'm not sure why exactly that counts as a precommit error, I'll have a look at getting rid of that check.

**Comment by orangejulius** [comment]
There's also a command `npm prune`, that will clear out packages that are in `node_modules` but not `package.json`. That said I still often have to resort to `rm -rf node_modules && npm install` anyways, but sometimes `npm prune` helps.

**Comment by vesameskanen** [comment]
The problem is indeed strange. As far as I can see, the actions below should work, but they do not:
- git clone https://github.com/pelias/api
- cd  api
- npm install
- npm ls 

The last command shows a dependency error (missing tape.xxxx) . As if the problem was in npm itself; install and ls do not match. Running npm install second time fixes the error, but the commit hook validation still fails, showing a bunch of extraneous modules.

This happens on Debian Linux, node.js v.5.6.0, npm v.3.6.0

**Comment by dimfeld** [comment]
The commit hook likely fails it's because newer versions of npm install all dependencies, direct and indirect, in the node_modules directory, and the validation script doesn't account for this. It works fine with Node 0.12, which includes an older version of npm that doesn't install indirect dependencies under the root node_modules directory.

**Comment by orangejulius** [comment]
I used to be able to reproduce this on Node 5 with NPM 3, but no longer. We've updated a bunch of our dependencies lately (thank you @greenkeeperio-bot!) and I think that helped. If anyone is still seeing this, please reopen and post details.
