### ISSUE TITLE
layers=(qs or quattroshapes) should forward to layers=whosonfirst

### ISSUE THREAD

**Issue by riordan** [pelias/api#442]
Several of our existing users make calls to quattroshapes. When we disable Quattroshapes, they'll need to be able to still make those calls while getting the same kind of records. We should forward these requests to Who's on First.

**Comment by orangejulius** [comment]
Bleh. As long as we put in a warning and only do it for 60 days or so

**Comment by riordan** [comment]
:+1:

**Comment by orangejulius** [comment]
Also, we could add a warning starting now that QS will go away soon.
