### ISSUE TITLE
Add layers parameter to Autocomplete endpoint

### ISSUE THREAD

**Issue by riordan** [pelias/api#449]
We should add the option to select by layer type in autocomplete, allowing users to select results of specific types (e.g. `venue`, `address`, `neighbourhood`, `locality`, `coarse`, `region`, etc.).

One of the things we discovered during our user testing is that some of our users will filter out autocomplete results so they can get the specific type of results they want. While our current autocomplete approach is designed to improve cache likelihood by permitting only limited configuration (query + optional focus.point position), it's too limiting for many intended autocomplete uses (see @louh's [blog post](https://mapzen.com/blog/find-your-community) asking for just addresses in New York City).

## What it'd look like

`search.mapzen.com/v1/autocomplete?layer=coarse&query=la leng`

When combined with #373, this will allow highly targeted and cache-able autocomplete queries.

## Outstanding Questions:
- [ ] What are the performance / cache likelihood implications of this change?
- [ ] Do we allow the selection of multiple layers at once with this query or just a single layer?
 - [ ] How bad is it to ask a user to make multiple queries to retrieve across multiple layers?

**Comment by louh** [comment]
:+1: Incidentally, the Leaflet plugin now filters autocomplete by the requested layers, if provided (https://github.com/mapzen/leaflet-geocoder/releases/tag/v1.5.0). This might not work well if the autocomplete response contains no features in the requested layers. They will all get filtered out and appear in the UI as "no results found".

The reasoning here is that `layers` as an option for the plugin is expected to "just work" everywhere. So someone might specify multiple layers and expect the same experience from both `/search` and `/autocomplete`. If the plugin had to make 2 consecutive requests (or more) to `/autocomplete` and concatenate the results to provide a seamless experience, I'm worried that the additional requests will slow down the autocomplete experience overall.

**Comment by missinglink** [comment]
I am :+1: on adding this API feature, let's pair this ticket with one to improve the key generation algorithm at the end cache.

The dev work on this is trivial, it's simply a product/caching question.
