### ISSUE TITLE
WOF and backward compatibility

### ISSUE THREAD

**Issue by vesameskanen** [pelias/api#452]
Should the current master branch of the API be backward compatible with an elasticsearch instance initialized using production branches of Pelias? I am getting an error: 

>   error: [middleware-500] Error: `TypeError: Cannot read property 'country_a' of undefined`

when running searches. This is quite a trivial thing, but maybe there is no reason to do the fix.

**Comment by missinglink** [comment]
the current development branch is called `new_wof_model_format` and it contains breaking changes, sorry!

**Comment by missinglink** [comment]
we are just going through our final rounds of testing for that branch and it should go to production shortly.

**Comment by vesameskanen** [comment]
Hi @missinglink - thanks for the quick feedback! This is no problem at all, I just wanted to know if I should share my quick fixes in the middleware, Apparently not worth the effort, as I already thought.
