### ISSUE TITLE
failing to find "chelsea, new york"

### ISSUE THREAD

**Issue by missinglink** [pelias/api#455]
Cannot find NYC neighborhood "Chelsea" using `/autocomplete` *but* can find it using `/search`

- /v1/autocomplete?text=chelsea, new york
- /v1/search?text=chelsea, new york

expected:

```
      "properties": {
        "id": "85810589",
        "gid": "whosonfirst:neighbourhood:85810589",
        "layer": "neighbourhood",
        "source": "whosonfirst",
        "name": "Chelsea",
        "confidence": 0.946,
        "country": "United States",
        "country_id": "85633793",
        "country_a": "USA",
        "region": "New York",
        "region_id": "85688543",
        "region_a": "NY",
        "county": "Kings County",
        "county_id": "102082361",
        "localadmin": "Brooklyn",
        "localadmin_id": "404521211",
        "locality": "New York",
        "locality_id": "85977539",
        "bounding_box": {
          "min_lat": 40.737361,
          "max_lat": 40.757023,
          "min_lon": -74.012359,
          "max_lon": -73.987937
        },
        "label": "Chelsea, Brooklyn, NY, USA"
```

**Comment by missinglink** [comment]
some improvement have been made here:

```javascript
/v1/autocomplete?text=chelsea, new york

1)	Chelsea, London, United Kingdom
 2)	Royal Kensington and Chelsea, Kensington, United Kingdom
 3)	Chelsea, London, United Kingdom
 4)	Chelsea, Manhattan, NY, USA
```

...although the Manhattan result should appear first rather than fourth.

the 'admin boost' is not having enough effect to overcome the `population/popularity` boost of the London results.

this is partially fixed but could do with some more boost tweaks.

**Comment by orangejulius** [comment]
![chelsea](https://cloud.githubusercontent.com/assets/111716/14085520/4c7915c8-f4ee-11e5-9df8-32f23a62942e.png)

This appears fixed with the lastest build on `prod_build`. My guess is it was fixed with @trescube's pull request to fix the county parentage in WOF, as well as https://github.com/pelias/schema/pull/111

**Comment by orangejulius** [comment]
:tada: :checkered_flag: :surfer: we now get this totally right on both [autocomplete](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=chelsea,%20new%20york) and [search](http://pelias.github.io/compare/#/v1/search%3Ftext=chelsea,%20new%20york)
