### ISSUE TITLE
focus.viewport centroid does not account for sphrerical earth

### ISSUE THREAD

**Issue by missinglink** [pelias/api#472]
we currently use an `average lat/lon` algorithm for computing the centroid of the `focus.viewport`, this is probably only accuracy for smaller viewports (~400km).

at larger scales the centroid would be more accurate if we use a spherical model, although this will cause problems when the two diagonal corners are at opposite sides of the earth, as the centroid is either the centre of the earth or one or both? of the poles?

**Comment by dianashk** [comment]
We do not support `focus.viewport`. Is this still relevant? cc @missinglink
