### ISSUE TITLE
input text interpretation

### ISSUE THREAD

**Issue by missinglink** [pelias/api#48]
When entering location strings where the text is delimited by a symbol, eg. `'London, UK'` or `'London, ON'` the context suggester fails to see the difference between the named component and the admin component(s) which are conventionally delimited using a comma.

We need to start looking at some very basic NLP even if it's just something like **only** using the tokens *before* the first comma.

Here's a visual illustration of the problem:
![ss](http://peter.johnson.s3.amazonaws.com/delimeters.gif)

The gifs shows 2 UX issues:

1. Not reproducible: when clicking a successful match you cannot use the string returned to search and find that same place, you **must** remove everything after the first comma.

2. You cannot paste an address string directly in to the input, eg. pasting "Hackney Town Hall, Hackney, Greater London" yields 0 results.

thoughts @hkrishna ?

note, to reproduce the above query bias: https://mapzen.com/pelias#loc=18,51.54503,-0.05639

**Comment by missinglink** [comment]
Since we are now fully converted to `suggest_plus_mget` approach, we could do something fancy with the tokens *after* the comma.

When using `/search`, this could be pretty easy, simply querying against the admin fields with the remaining text and boosting the results accordingly.

Doing it in `/suggest` is another story completely...

I'm planning on allowing the suggester FST to be filtered by alpha3, which could at very least support querying alpha3 values after the comma, still that's not very user-friendly.

In the future we could also have `context suggester` entries for common abbreviations.
ref: https://github.com/pelias/schema/pull/25

**Comment by hkrishna** [comment]
How about we use the context suggested and instead of the category be one
of the datasets, could we have dataset and alpha3? For ex,
```geoname:US```, ```locality:IT```

And in the query you could maybe use wildcard character ```*``` to match on
things??

**Comment by dianashk** [comment]
Should be closed in light of newer issues.

**Comment by missinglink** [comment]
We could close this in favour of:
- https://github.com/pelias/pelias/issues/40

That ticket only covers one of the issues and only partially, plus it doesn't have as clear a description as this.

**Comment by missinglink** [comment]
this issue has been resolved
