### ISSUE TITLE
size bug on search

### ISSUE THREAD

**Issue by missinglink** [pelias/api#51]
I think this is related to the multi suggesters:

http://pelias.mapzen.com/suggest?input=millpond&lat=51.500036&lon=-0.060017&size=1
[ no results ]

http://pelias.mapzen.com/suggest?input=millpond&lat=51.500036&lon=-0.060017&size=10
[ results ]

cc/ @hkrishna

**Comment by missinglink** [comment]
what's the status of this? It looks like the branch containing the fix was never merged to master @hkrishna ?

**Comment by hkrishna** [comment]
This is fixed.  Sorry, I forgot to close this.
