### ISSUE TITLE
API incorrectly warns against using `boundary.radius` parameter in reverse

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#510]
See http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=40&point.lon=-65&boundary.circle.radius=400&sources=wof

If you change the radius to something bigger, results will show up, so this parameter definitely has an effect. And it is listed in our API spec. I think this warning carries over from /search, where it is _not_ supported yet.

**Comment by dianashk** [comment]
Code has been merged and we will close this issue once it rolls up to production. Cheers!
