### ISSUE TITLE
SearchPhaseExecution - Failed to execute phase [query_fetch]

### ISSUE THREAD

**Issue by curiousc0w** [pelias/api#521]
Hi all,

I have a Pelias instance on my VM where I was able to achieve a full OpenAddresses import along with smaller data sets with WOF, Geonames, OSM, etc.. without an import errors or issues. My Elasticsearch health is Green and is 44.3 GB. When I navigate to my api directory and ```npm start``` and try to make a query, I get the following error:

`{"geocoding":{"version":"0.1","attribution":"http://pelias.mapzen.com/v1/attribution","query":{"text":"ottawa, ontario","parsed_text":{"name":"ottawa","regions":["ottawa","ontario"],"admin_parts":"ontario"},"size":10,"private":false,"querySize":20},"errors":[{"status":400,"displayName":"BadRequest","message":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[mfKERpgCSs6AAx1UdlOD9g][pelias][0]: SearchParseException[[pelias][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"bool\":{\"must\":[{\"match\":{\"name.default\":{\"analyzer\":\"peliasOneEdgeGram\",\"boost\":1,\"query\":\"ottawa\"}}}],\"should\":[{\"match\":{\"phrase.default\":{\"analyzer\":\"peliasPhrase\",\"type\":\"phrase\",\"boost\":1,\"slop\":2,\"query\":\"ottawa\"}}},{\"function_score\":{\"query\":{\"match\":{\"phrase.default\":{\"analyzer\":\"peliasPhrase\",\"type\":\"phrase\",\"boost\":1,\"slop\":2,\"query\":\"ottawa\"}}},\"max_boost\":20,\"functions\":[{\"field_value_factor\":{\"modifier\":\"log1p\",\"field\":\"popularity\",\"missing\":1},\"weight\":1}],\"score_mode\":\"first\",\"boost_mode\":\"replace\"}},{\"function_score\":{\"query\":{\"match\":{\"phrase.default\":{\"analyzer\":\"peliasPhrase\",\"type\":\"phrase\",\"boost\":1,\"slop\":2,\"query\":\"ottawa\"}}},\"max_boost\":20,\"functions\":[{\"field_value_factor\":{\"modifier\":\"log1p\",\"field\":\"population\",\"missing\":1},\"weight\":2}],\"score_mode\":\"first\",\"boost_mode\":\"replace\"}},{\"match\":{\"parent.country\":{\"analyzer\":\"peliasAdmin\",\"boost\":4,\"query\":\"ontario\"}}},{\"match\":{\"parent.region\":{\"analyzer\":\"peliasAdmin\",\"boost\":3,\"query\":\"ontario\"}}},{\"match\":{\"parent.region_a\":{\"analyzer\":\"peliasAdmin\",\"boost\":3,\"query\":\"ontario\"}}},{\"match\":{\"parent.county\":{\"analyzer\":\"peliasAdmin\",\"boost\":2,\"query\":\"ontario\"}}},{\"match\":{\"parent.localadmin\":{\"analyzer\":\"peliasAdmin\",\"boost\":1,\"query\":\"ontario\"}}},{\"match\":{\"parent.locality\":{\"analyzer\":\"peliasAdmin\",\"boost\":1,\"query\":\"ontario\"}}},{\"match\":{\"parent.neighbourhood\":{\"analyzer\":\"peliasAdmin\",\"boost\":1,\"query\":\"ontario\"}}}]}}}},\"size\":20,\"track_scores\":true,\"sort\":[\"_score\"]}]]]; nested: QueryParsingException[[pelias] [match] analyzer [peliasOneEdgeGram] not found]; }]"}],"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1461140346199},"type":"FeatureCollection","features":[]}`

The api console doesn't output an error:

```
2016-04-20T08:18:42.572Z - info: [api] Ignoring address parser output, regions only
2016-04-20T08:18:42.574Z - info: [api:controller:search] [req] endpoint=/v1/autocomplete text=ottawa, size=10, private=false
2016-04-20T08:18:42.603Z - info: [api] 127.0.0.1 - - [20/Apr/2016:08:18:42 +0000] "GET /v1/autocomplete?text=ottawa HTTP/1.1" 500 1643
2016-04-20T08:19:06.189Z - info: [api:controller:search] [req] endpoint=/v1/search text=ottawa, ontario, name=ottawa, regions=[ottawa, ontario], admin_parts=ontario, size=10, private=false, querySize=20
2016-04-20T08:19:06.201Z - info: [api] 127.0.0.1 - - [20/Apr/2016:08:19:06 +0000] "GET /v1/search?text=ottawa,%20ontario HTTP/1.1" 500 2525
```

Has anybody ever come across this?

**Comment by curiousc0w** [comment]
Is this an error involving ```peliasOneEdgeGram```?

**Comment by orangejulius** [comment]
Hey @curiousc0w,
What version of [pelias/schema](https://github.com/pelias/schema/) did you run? This looks like it could be caused by running an out of date schema, or no schema at all. This would be our fault as the docs are not very clear about the need to do this, and Elasticsearch is marketed as "schema-less" when what that really means is it will default to a poorly optimized schema if one isn't configured.

If you paste the full output of `curl -XGET 'http://localhost:9200/pelias/_mapping/`, we'll be able to tell you what's wrong.

**Comment by curiousc0w** [comment]
@orangejulius 
Here's the output:

```
[user@localhost ~]$ curl -XGET 'http://localhost:9200/pelias/_mapping/'
{"pelias":{"mappings":{"address":{"properties":{"address_parts":{"properties":{"number":{"type":"string"},"street":{"type":"string"},"zip":{"type":"string"}}},"center_point":{"properties":{"lat":{"type":"double"},"lon":{"type":"double"}}},"layer":{"type":"string"},"name":{"properties":{"default":{"type":"string"}}},"parent":{"type":"object"},"phrase":{"properties":{"default":{"type":"string"}}},"source":{"type":"string"},"source_id":{"type":"string"}}}}}}
```
How do you find the version of the pelias/schema used?

**Comment by orangejulius** [comment]
Ah, that looks like no schema was loaded at all. Again it's our fault for not having the docs that call it out explicitly yet. There's no way to fix this unfortunately except to delete all your data from elasticsearch and re-import it after loading the correct schema. You can do that by...


```bash
cd where-you-keep-your-pelias-code
git clone git@github.com:pelias/schema.git # to check out pelias/schema
cd schema
git checkout production # or whatever branch you've been using elsewhere. production is the most stable
npm install
node scripts/drop_index.js # this will remove all the pelias data from elasticsearch. sorry, there's no other way :(
node scripts/create_index.js # this will set the schema to the correct values. if you run the curl again you'll see quite a bit more output :)
```

Then re-import all your data again.

**Comment by curiousc0w** [comment]
@orangejulius 
So I followed your instructions and re-imported a smaller OpenAddresses dataset of 13 csv files (Ontario, Canada). I was able to preform queries without any issue or error.

The SearchPhaseExecution error occurs when I import the global OpenAddresses dataset (~2600 csv files). For some reason it doesn't like my larger data sets.

**Comment by orangejulius** [comment]
Elasticsearch errors are pretty cryptic. SearchPhaseExecution errors can happen for many reasons, so you'll have to carefully read the whole error message for hints. It's a huge pain I know. If you paste it here we can take a look.

**Comment by curiousc0w** [comment]
@orangejulius 
Did your Mapzen Pelias team set any further Elasticsearch configuration settings which would help the geocoding performance?

**Comment by orangejulius** [comment]
As far as I know, all the configuration settings that matter are encapsulated in pelias/schema

**Comment by orangejulius** [comment]
I think we've solved this one, but if not feel free to re-open and let us know.
