### ISSUE TITLE
parser: detect regions without a trailing comma

### ISSUE THREAD

**Issue by missinglink** [pelias/api#528]
note: this is for /search not /autocomplete

The text parser correctly parses admin areas and adds a `regions` entry when there is a trailing comma but not when the comma is not present.

This results in the query not matching against admin fields.

If possible, tune the text parser to provide `region` information in these cases.

note: the trailing comma

```
/v1/search?text=new york

    "query": {
      "text": "new york",
      "size": 10,
      "private": false,
      "focus.point.lat": 41.05343,
      "focus.point.lon": -73.53873
    },

/v1/search?text=new york,

    "query": {
      "text": "new york,",
      "parsed_text": {
        "name": "new york",
        "regions": [
          "new york"
        ]
      },
      "size": 10,
      "private": false
    },
```

same for paris:

```
/v1/search?text=paris

    "query": {
      "text": "paris",
      "size": 10,
      "private": false
    },

/v1/search?text=paris,

    "query": {
      "text": "paris,",
      "parsed_text": {
        "name": "paris",
        "regions": [
          "paris"
        ]
      },
```

**Comment by dianashk** [comment]
Add as an acceptance test for libpostal integration.

**Comment by orangejulius** [comment]
This is still happening, even though the [correct results](http://pelias.github.io/compare/#/v1/search%3Ftext=paris) are returned, and (I think) always were.
![screenshot from 2017-01-11 15-03-31](https://cloud.githubusercontent.com/assets/111716/21864304/2efe5ea4-d80f-11e6-81b1-f01f4572f64a.png)

@trescube any idea why the parsed_text section is missing in this query?
@missinglink can you confirm that the correct results were returned when you reported this (if you can remember)?

**Comment by dianashk** [comment]
The reason there is no parsed text without the comma is because even though `libpostal` parses it correctly those query types are not currently supported by our *fallback queries*. From there it looks like we have code in the `addressit` text-analyzer to ignore what `addressit` says if the query is not an actual address (as in housenumber+street). The logs look as follows.

```
2017-05-04T20:43:23.058Z - debug: [text-analyzer] libpostal raw: [
  {
    "value": "paris",
    "component": "city"
  }
]
2017-05-04T20:43:23.059Z - debug: [text-analyzer] converted: {
  "city": "paris"
}
2017-05-04T20:43:23.060Z - info: [api] [lang] 'en' via 'header'
2017-05-04T20:43:23.061Z - info: [api] [req] endpoint=/v1/search text=paris, city=paris, size=10, private=false, name=English, iso6391=en, iso6393=eng, defaulted=false, querySize=20
2017-05-04T20:43:23.061Z - info: [api] [query:search] [search_input_type:other]
2017-05-04T20:43:23.061Z - info: [api] [parser:libpostal] query type not supported
2017-05-04T20:43:23.062Z - info: [api] fallback queryText: paris
2017-05-04T20:43:23.063Z - info: [api] Ignoring address parser output, regions only
```

**Comment by dianashk** [comment]
I believe this should get fixed with the `placeholder` integration.

**Comment by dianashk** [comment]
Fixed! 🎉
