### ISSUE TITLE
Elasticsearch startup error: "failed to warm-up global ordinals for [center_point]"

### ISSUE THREAD

**Issue by migurski** [pelias/api#539]
I’m attempting to run ES 1.7.5 on Ubuntu 14.04 with openjdk-7. I had this working on a VBox, but when running on EC2 I see this in the ES logs:

```
[2016-05-11 05:01:42,433][WARN ][index.warmer             ] [Bonita Juarez] [pelias][0] failed to warm-up global ordinals for [center_point]
java.lang.ClassCastException: org.elasticsearch.index.fielddata.plain.GeoPointDoubleArrayIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexFieldData$Global
	at org.elasticsearch.search.SearchService$FieldDataWarmer$3.run(SearchService.java:965)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I am seeing normal stuff at http://127.0.0.1:9200/ but running OA import shows these failures:

```
Elasticsearch ERROR: 2016-05-11T05:05:24Z
  Error: Request error, retrying
  POST http://localhost:9200/_bulk => socket hang up
      at Log.error (/usr/lib/nodejs/pelias-openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/log.js:225:60)
      at checkRespForFailure (/usr/lib/nodejs/pelias-openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/usr/lib/nodejs/pelias-openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/usr/lib/nodejs/pelias-openaddresses/node_modules/pelias-dbclient/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at ClientRequest.EventEmitter.emit (events.js:95:17)
      at Socket.socketOnEnd [as onend] (http.js:1568:9)
      at Socket.g (events.js:180:16)
      at Socket.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)
```

After these errors, the ES process is dead.

**Comment by missinglink** [comment]
I suspect the warning above and the error below are unrelated.

I'm currently working on an full product update to elasticsearch 2.2 and beyond to 5.x, I'll add this ticket to that milestone.

My dev machine is an Ubuntu 14.04 box with Oracle JDK8 and ES@1.7.5

**Comment by missinglink** [comment]
I just confirmed that the importer is working on my local machine:

```bash
$ cat /etc/issue
Ubuntu 14.04.4 LTS \n \l

$ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

$ curl -s localhost:9200 | grep num
    "number" : "1.7.5",
```

```bash
verbose: [dbclient]  paused=false, transient=0, current_length=0, indexed=478908, batch_ok=958, batch_retries=0, failed_records=0, address=478908, persec=3490.8
info: [openaddresses] Total time taken: 156.706s
```

so... firstly, you can ignore the `ClassCastException` warning, it's unrelated and I also get that in my logs, its a red herring.

there is a mismatch between our java versions and distributions, I would recommend `Oracle 1.8.0_73` as that's what the [elasticsearch team recommend you use](https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html), although I also doubt this is the cause of your `socket hang up` error.

lastly you mentioned that it was working fine in VBox and stopped working in EC2? I suspect that the configuration of your network and security rules may be causing the socket errors.

are you running the elasticsearch server on the same machine as the api code, or are they on different machines?

could you please paste your generated [pelias config](https://github.com/pelias/config) here so I can confirm it's all good? the command is:

```
cd your_api_code_dir;
node -e "console.log( require('pelias-config').generate().stringify() );";
```

**Comment by migurski** [comment]
> the error you receive socket hang up makes me think that the import was successful for some time and then at some point stopped working?

I think that’s what I’m seeing, yes.

I am following this process to install ES: https://github.com/openaddresses/pelias-ubuntu-xenial/tree/trusty#install

In both cases (VBox and EC2), it’s running on localhost with unmodified default configuration. For the Pelias importer, I am using this configuration to override one of the defaults: https://github.com/openaddresses/pelias-openaddresses-ubuntu-xenial/blob/master/etc/pelias-config-openaddresses.json

On 14.04 I am using OpenJDK 7, since it does not require a clickthrough license agreement. I will try to replace it with Oracle. Thanks for the scriptable lines above; they’ll save me some hassle.

**Comment by migurski** [comment]
I re-tried this with a fresh EC2 machine using Oracle JDK instead of OpenJDK, and got the same error as above. Confirmed that `/etc/hosts` contains the right stuff; certain this is not a 127.0.0.1 vs. localhost issue.

Generated config looks like this:

```
{
  "esclient": {
    "apiVersion": "1.7",
    "keepAlive": true,
    "requestTimeout": "120000",
    "hosts": [
      {
        "env": "development",
        "protocol": "http",
        "host": "localhost",
        "port": 9200
      }
    ],
    "log": [
      {
        "type": "stdio",
        "level": [
          "error",
          "warning"
        ]
      }
    ]
  },
  "dbclient": {
    "statFrequency": 10000
  },
  "api": {
    "accessLog": "common",
    "host": "http://pelias.mapzen.com/",
    "version": "1.0"
  },
  "logger": {
    "level": "info",
    "timestamp": true,
    "colorize": true
  },
  "acceptance-tests": {
    "endpoints": {
      "local": "http://localhost:3100/v1/",
      "dev": "http://pelias.dev.mapzen.com/v1/",
      "prod": "http://pelias.mapzen.com/v1/",
      "prodbuild": "http://pelias.prodbuild.mapzen.com/v1/",
      "beta": "http://pelias.beta.mapzen.com/"
    }
  },
  "imports": {
    "geonames": {
      "datapath": "./data"
    },
    "quattroshapes": {
      "datapath": "/mnt/pelias/quattroshapes"
    },
    "openstreetmap": {
      "datapath": "/mnt/pelias/openstreetmap",
      "leveldbpath": "/tmp",
      "import": [
        {
          "type": {
            "node": "osmnode",
            "way": "osmway"
          },
          "filename": "planet.osm.pbf"
        }
      ]
    },
    "openaddresses": {
      "datapath": "/mnt/pelias/openaddresses",
      "files": []
    }
  }
}
```

**Comment by migurski** [comment]
I will leave the machine up for a day, and I can give you shell + sudo access if you’d like.

**Comment by missinglink** [comment]
Trouble shooting this offline, it appears the issue is due to insufficient RAM available to the system.

The virtual machine above only had 1GB RAM installed, when the kernel starts running out of memory it starts killing off things with a high [nice](https://en.wikipedia.org/wiki/Nice_(Unix)) (not nice!)

This results in weird and wonderful errors such as the one experienced above.

We would recommend that self-installs use a minimum of 8GB ram and assign 50% for the elasticsearch `JAVA_HEAP` and leave 50% available for the OS file system cache.

**Comment by migurski** [comment]
Just tried this a few times with larger amounts of RAM and bigger imports, and it worked well. Thanks for your help.
