### ISSUE TITLE
Sort response items after confidence scoring

### ISSUE THREAD

**Issue by vesameskanen** [pelias/api#558]
It would be useful to get the found items in confidence-score sorted order.

**Comment by orangejulius** [comment]
This is a good idea. Hopefully as time goes on we can unify the confidence score and the Elasticsearch scoring in some way, so that there aren't conflicting signals. But in the meantime this could help.

**Comment by vesameskanen** [comment]
This is now implemented in https://github.com/pelias/api/pull/560 .
