### ISSUE TITLE
interpret lon:181 as lon:-179

### ISSUE THREAD

**Issue by hkrishna** [pelias/api#56]
https://github.com/pelias/demo/issues/10

**Comment by orangejulius** [comment]
The tests very clearly show lon > 180 should be invalid, is this change still being considered?

**Comment by hkrishna** [comment]
yes. I think this needs to happen at the [sanitizer](https://github.com/pelias/api/blob/master/sanitiser/_geo.js) level and tests be updated accordingly.

**Comment by missinglink** [comment]
![](http://i279.photobucket.com/albums/kk143/faeini1/agscary4.gif)
