### ISSUE TITLE
document how zoom affects API queries and how sorting works

### ISSUE THREAD

**Issue by missinglink** [pelias/api#58]
document how zoom affects API queries and how sorting works

as per conversation yesterday, it was unclear to those not directly involved to understand how it all works.

ref: flowdock conversation starting at `search:/messages/504098`

**Comment by riordan** [comment]
Zoom is deprecated into `extent`.

But yes, someone needs to document the way sorting occurs for each. Will need to be a part of the documentation project.

**Comment by riordan** [comment]
Documentation happening [here](https://github.com/pelias/pelias-doc/blob/master/getting-started/002-search.md)
