### ISSUE TITLE
label generation for common POIs

### ISSUE THREAD

**Issue by missinglink** [pelias/api#582]
in some cases there are 10+ POIs with the same name, in this case it might be best to generate labels differently in order for the user to disambiguate the results.

maybe we could detect this condition and rerun the label generator with a config which forces it to use lower-level admin areas, street names etc.

![post office](http://missinglink.embed.s3.amazonaws.com/post_office.png)

**Comment by orangejulius** [comment]
:+1: 

This looks like a similar situation to https://github.com/pelias/pelias/issues/317

**Comment by missinglink** [comment]
yes, that looks like a dupe
