### ISSUE TITLE
Revisit deduper for correct operation

### ISSUE THREAD

**Issue by trescube** [pelias/api#604]
libpostal integration, by way of introducting 2 new query modules, may end up creating result sets that the deduper may not deal with correctly.  Then again, it may operate as expected.  Either way, as part of the https://github.com/pelias/pelias/issues/152, the deduper should be revisited to ensure correct operation.

**Comment by trescube** [comment]
I noticed that searching for "Doylestown, PA" is overly greedy with deduping.  For reference, Doylestown is the seat of Bucks County, PA, but also happens to be a very small locality in Franklin County, PA according to geonames.  The duduper is filtering out 1 of the 2 in Bucks County but is also getting rid of the one in Franklin County.

**Comment by trescube** [comment]
Searching for just "Doylestown", the deduper filters out 1 of the 2 PA localities but retains the localadmin.  This will be confusing for users.

**Comment by missinglink** [comment]
fixed in #649
