### ISSUE TITLE
Does libpostal need to be installed locally?

### ISSUE THREAD

**Issue by haleystorm** [pelias/api#651]
I'm installing Pelias, following directions [here](https://github.com/pelias/pelias-doc/blob/master/installing.md#installation) and encountered a make error for node-postal when running npm install in pelias/api

```
git clone git@github.com:pelias/api.git
cd api
git checkout production
npm install
```

produces error

```
> node-postal@0.3.0 install /home/ec2-user/api/node_modules/node-postal
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/ec2-user/api/node_modules/node-postal/build'
  CXX(target) Release/obj.target/expand/src/expand.o
../src/expand.cc:1:33: fatal error: libpostal/libpostal.h: No such file or directory
 #include <libpostal/libpostal.h>
                                 ^
compilation terminated.
make: *** [Release/obj.target/expand/src/expand.o] Error 1
make: Leaving directory `/home/ec2-user/api/node_modules/node-postal/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.10.0-327.13.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/api/node_modules/node-postal
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

Installing libpostal locally resolves the error. Noticed a note on [text-analyser](https://github.com/pelias/text-analyzer#configuration) that says "To use the libpostal address parser, libpostal must be installed locally."

Can this error be ignored? Does the api use the libpostal address parser?

**Comment by orangejulius** [comment]
Hey @haleystorm,
Good question. Right now the libpostal node package [is especially set up ](https://github.com/openvenues/node-postal/blob/master/package.json#L34) to ignore this error. I believe it's so that it's easy to use as a dependency without having libpostal installed.

In Pelias, we don't (yet) use libpostal in our master branch or production, but we will be very soon, so you can ignore this error for now.

**Comment by haleystorm** [comment]
Great thanks!
