### ISSUE TITLE
Label generation as a separate postprocessing step?

### ISSUE THREAD

**Issue by vesameskanen** [pelias/api#652]
Would it make sense to create an explicit postprocessing stage where labels are added to the search results? Now the labels are created as a part of json conversion. Deduper and label generation resolutions do not match, so one often gets identical labels from searches.  I believe that client apps might often want to use Pelias generated labels directly without additional logic in the client side.  In such a case, identical labels are a problem. 

A dedicated module for label generation would allow more logic, where duplicate labels could be expanded on need basis, by adding configured extensions such as the address to a venue, a category description etc.

**Comment by missinglink** [comment]
@trescube spent a bunch of time on label generation

**Comment by dianashk** [comment]
This makes a lot of sense to me. We've struggled with how to make duplicate labels for non-duplicate things show up more clearly. This is an excellent suggestion.

**Comment by orangejulius** [comment]
I like this suggestion as well. Right now our labels are purely a function of the data contained in the record, but there are definitely cases where we want to further disambiguate, like https://github.com/pelias/pelias/issues/317. Building labels with knowledge of other records could help us figure out how much data needs to be added to disambiguate.

**Comment by missinglink** [comment]
I am :+1: for this
