### ISSUE TITLE
using neighbourhood in search

### ISSUE THREAD

**Issue by Penderis** [pelias/api#659]
Hi.  I am unable to search by just using neighbourhood names and entire towns mostly outside USA.  Yet using open street maps I can find the search eg: flamwood.  Would just like to ask how i could supplement the data with the same that openstreetmaps uses?

**Comment by orangejulius** [comment]
Hey @Penderis,
Pelias only imports addresses and venues from OSM, not neighbourhoods, cities, etc. For that we have [Who's on First](http://whosonfirst.mapzen.com/) and (for now) [Geonames](http://geonames.org/).

While there has been [some work](https://github.com/pelias/fences-cli) in the past to use OSM for administrative area data, it's not something we're really pursuing any more. OSM's strengths are really at a lower level: it has excellent info for places: addresses, apartments, tourst attractions, restauraunts, etc, and nothing really unique for say, information about countries. And as we have learned with Geonames, it's generally not good to have more than one source of admin data in a single geocoder, so as more of the Geonames data is integrated into Who's on First, we'll probably stop supporting Geonames, and will have just one consistent, complete source of admin data.

If you're using your own instance of Pelias, definitely run the [whosonfirst](https://github.com/pelias/whosonfirst) importer to get that data. If you're using Mapzen Search and can't find a neighbourhood, consider opening an issue with Who's on First (also a Mapzen project) in their [issue tracker](https://github.com/whosonfirst-data/whosonfirst-data). Either way, let us know how it goes!
