### ISSUE TITLE
Remove `country` from non-US `dependency` labels

### ISSUE THREAD

**Issue by trescube** [pelias/api#662]
While #628 has been fixed, other dependencies have non-optimal labels.  For example, [Bermuda](https://whosonfirst.mapzen.com/spelunker/id/85632731/#11/32.3178/-64.7680) is a dependency of the UK.  The label for the Bermuda dependency is currently `Bermuda, United Kingdom` while the label for the locality of [Hog Bay](https://whosonfirst.mapzen.com/spelunker/id/421169989/#12/32.2978/-64.8601) is `Hog Bay, United Kingdom`.  Another example is [Adamstown](https://whosonfirst.mapzen.com/spelunker/id/890440159/#8/-24.502/-127.766) in the [Pitcairn Islands](https://whosonfirst.mapzen.com/spelunker/id/85632587/#8/-24.502/-127.766) which has the label `Adamstown, United Kingdom` which is very confusing.

**Comment by nvkelso** [comment]
Could we use a pattern system (variant of OpenCageData) for this?

**Comment by trescube** [comment]
Yeah, our goal is to get there but it's a big-ish effort to do so now.

**Comment by trescube** [comment]
Superseded by pelias/labels#5
