### ISSUE TITLE
Missing property is not always a difference in deduplication

### ISSUE THREAD

**Issue by vesameskanen** [pelias/api#678]
Currently API deduper considers two documents different, if either one misses information of another one.  This could perhaps be improved so that if the lower confidence document lacks some details, it can be dropped. In other words, why to keep a document which has the same type and is just less informative in every respect?

**Comment by orangejulius** [comment]
This is definitely a good idea. It ties into https://github.com/pelias/api/issues/650 which we'll be working on soon.

**Comment by dianashk** [comment]
This seems to have been taken care of in #650 so closing this issue. Please open a new one with examples if things are still not working as expected. Thanks!
