### ISSUE TITLE
Proposal: debug flag for all endpoints

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#681]
We've talked about this a lot. For performance testing and debugging purposes it would be nice to allow extra information to be sent back in the API responses to facilitate debugging.

Things that would be nice to know include:
- Elasticsearch query time
- Time to query libpostal/addressit
- Total number of documents scored in Elasticsearch
- Elasticsearch scores for results

If anyone can think of more things that might be useful, definitely let us know!

**Comment by dominikkukacka** [comment]
also the ES query produced would be interesting.

**Comment by dianashk** [comment]
closing in favor of pelias/pelias#207
