### ISSUE TITLE
No results when space is missing from input

### ISSUE THREAD

**Issue by trescube** [pelias/api#719]
Pelias gets `Leopoldauer straße 23, 1210, Wien, Austria` but not `Leopoldauerstraße 23, 1210, Wien, Austria` (space missing).

**Comment by orangejulius** [comment]
This is still currently an issue

[/v1/search?text=Leopoldauerstraße 23, 1210, Wien, Austria](http://pelias.github.io/compare/#/v1/search%3Ftext=Leopoldauerstra%C3%9Fe%2023,%201210,%20Wien,%20Austria)
![image](https://user-images.githubusercontent.com/111716/31736255-3fc69f50-b412-11e7-8585-d3666c5893b9.png)

@missinglink I believe some of your analysis work supports things like this, can you link to any similar issues?

**Comment by missinglink** [comment]
Yea... so... the conclusion I came to with the analysis is..

It's generally possible with US addresses to generate a 'canonical representation' of a street name, that is, a single representation from which all synonymous variants can be cleanly mapped to/from.

For German addresses this is unfortunately not possible, there isn't a clear rule about when the name + suffix are compounded and when they are not, and the two forms are used interchangeably. So we will need to index multiple forms of the street name.

Our current schema/model doesn't really support multiple synonymous representations of a street name (the interpolation service however does).

I don't think it's impossible to add this functionality but at the moment it doesn't exist.

**Comment by orangejulius** [comment]
This might be fixed by https://github.com/pelias/model/pull/119, we'll find out soon!

**Comment by orangejulius** [comment]
Looks like this works now! I'm going to assume that pelias/model#119 did indeed fix it.
![Screenshot_2020-03-19_08-13-04](https://user-images.githubusercontent.com/111716/77082594-86d20b00-69b9-11ea-9bb4-a53da286494d.png)
