### ISSUE TITLE
geonames:country /v1/autocomplete result missing label attribute

### ISSUE THREAD

**Issue by bdon** [pelias/api#720]
https://search.mapzen.com/v1/autocomplete?text=phil&api_key=<API KEY>

in the features list this entry does not have a label attribute:

```
{"type":"Feature","geometry":{"type":"Point","coordinates":[122,13]},"properties":{"id":"1694008","gid":"geonames:country:1694008","layer":"country","source":"geonames","source_id":"1694008","name":"Republic of the Philippines","accuracy":"centroid"}}
```
This started to appear around October 24.

**Comment by orangejulius** [comment]
Hey @bdon,
Thanks for the report! We'll look into this, for now here's a screenshot of a [query using our compare tool](http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=geonames&text=phil) for convenience.

![screenshot from 2016-11-14 15-20-31](https://cloud.githubusercontent.com/assets/111716/20281283/e60bc330-aa7d-11e6-89f3-e2edb6c0e361.png)

**Comment by trescube** [comment]
Interestingly, the 2nd result is a geonames record that is missing all of it's parent hierarchy:

```
{
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          122,
          13
        ]
      },
      "properties": {
        "id": "1694008",
        "gid": "geonames:country:1694008",
        "layer": "country",
        "source": "geonames",
        "source_id": "1694008",
        "name": "Republic of the Philippines",
        "accuracy": "centroid"
      }
    }
```

I expect what's happening is that the lon/lat 122/13 from geonames doesn't lie inside the multipolygon for the Philippines.  We could probably modify our wof-pip-service to create a convex hull for all the constituent polygons for countries.

**Comment by bdon** [comment]
@trescube unsure about the implications within Pelias but wouldn't that fail to generalize for exclaves like Alaska or Kaliningrad?

Thanks for tracking this down so fast!

**Comment by trescube** [comment]
Alaska and Kaliningrad appear to both be pretty large land masses where the lat/lon probably exists within the polygons representing the available land.  The problem with the Philippines is that the centroid from geonames falls [outside of the various island polygons](https://whosonfirst.mapzen.com/spelunker/id/85632509/#5/12.954/121.766).  We might just have to special case this for country polygons but we'll have to experiment a bit to be sure.
