### ISSUE TITLE
Deprecated queries removed in ES5

### ISSUE THREAD

**Issue by cag** [pelias/api#762]
I've discovered that while most of the functionality of the API server works just fine on ES5, some of the queries to ES on the API server now have to be rewritten, as they were on a deprecation schedule. The one I've seen so far is the [filtered](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-filtered-query.html) query, which has been deprecated in favor of bool. Just a heads up.

**Comment by orangejulius** [comment]
Good to know. I'm surprised we haven't caught that already since it's already deprecated in 2.3. The good news is we can fix it without breaking 2.3 compatibility, which we should definitely do.
