### ISSUE TITLE
Add metadata to response denoting which analyzer was used

### ISSUE THREAD

**Issue by trescube** [pelias/api#766]
For 2 purposes:

- [ ] better graphana logging support
- [ ] give our users some insight to what Pelias is doing

**Comment by dianashk** [comment]
work has begun as part of the placeholder integration changes.

**Comment by dianashk** [comment]
The new debug flag should help with this.

**Comment by orangejulius** [comment]
I think this has been done for some time now. Not only in the debug output, but the regular `query` section of the response as well.
<img width="617" alt="screen shot 2018-08-02 at 10 53 50 pm" src="https://user-images.githubusercontent.com/111716/43610630-f6c847e0-96a6-11e8-92d6-f3988fcfdb94.png">
