### ISSUE TITLE
error while loading libpostal data

### ISSUE THREAD

**Issue by oliverbienert** [pelias/api#768]
Hello,

on Ubuntu 16.04, 32bit I have set up pelias, installed and compiled libpostal and downloaded and imported whosonfirst and openstreetmap data.
While importing osm data, however, I had some errors (see pelias/whosonfirst/issues/181, my last comment).

When I try to start the api server, the following error occurs:
```
➜  api git:(production) npm start

> pelias-api@0.0.0-semantic-release start /home/oliver/pelias/api
> node index.js

loading libpostal data, this may take a few seconds...
/home/oliver/pelias/api/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /home/oliver/pelias/api/node_modules/node-postal/build/Release/expand.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/home/oliver/pelias/api/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/oliver/pelias/api/node_modules/node-postal/index.js:3:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! pelias-api@0.0.0-semantic-release start: `node index.js`
npm ERR! Exit status 1
```
Is that a subsequent error of an partially failed osm import?
I installed libpostal as in the instructions on there site. All went without errors.

**Comment by oliverbienert** [comment]
`rm -rf node_modules && npm install` fixes the issue.
However, I now have
```
Error loading geodb module, LIBPOSTAL_DATA_DIR=/home/oliver/data/libpostal
   at libpostal_setup_parser (libpostal.c:1086) errno: Cannot allocate memory
```
Well, this is my laptop, just 4GB RAM. Is there something I can do here? I just wanted to test pelias but it seems my machine is not capable of?

**Comment by orangejulius** [comment]
Hey @oliverbienert,
I'm not 100% positive, but I remember hearing that libpostal does not have 32-bit support. You might want to file an issue at https://github.com/openvenues/libpostal to ask and make sure. 4GB of RAM should be enough to run small instances of Pelias, even with libpostal though. If you make the switch to 64 bit, definitely let us know how it goes.

**Comment by oliverbienert** [comment]
Hi @orangejulius,
thank you for answering. I was able to successfully compile libpostal on my 32bit machine and use a few statements on commandline, using the address_parser directly. So I was wondering why it didn't work with pelias.
But as I said, it's just my old laptop, so I don't care.
We have it running on a 64bit debian jessy test instance at the moment.
In a couple of days, we'll set up a new machine for production and I'm gonna definitely come back if anything goes wrong ;-)
