### ISSUE TITLE
Enable configuration of listen address

### ISSUE THREAD

**Issue by ge-fa** [pelias/api#771]
If running behind a reverse proxy / load balancer on a separate machine, there is no need to only allow listening to localhost, thus it would make sense if this could be configurable.

**Comment by orangejulius** [comment]
Definitely. This would be great to have.

**Comment by missinglink** [comment]
easy fix in https://github.com/pelias/api/blob/master/index.js to add `process.env.HOST` with a default value to `localhost`, I believe `app.listen()` takes a second param.
