### ISSUE TITLE
`text_analyzer.parse is not a function` using search

### ISSUE THREAD

**Issue by laxatives** [pelias/api#827]
The example request provided in the docs `http://localhost:3100/v1/search?text=london` returns an error response like

```
{
    "error": "text_analyzer.parse is not a function"
}
```

However the other examples using `autocomplete` and `reverse` function as expected. Am I missing some dependency? Is `libpostal` required? I've tried installing `pelias/text-analyzer`in addition to `schema`, `api`, and `config`, but no luck there. Has anyone else observed this error message?

**Comment by laxatives** [comment]
This was resolved by changing the parser with the config setting

```
 "api": {        "textAnalyzer": "addressit"    }
```

**Comment by trescube** [comment]
Sorry for the late response.  libpostal is a required dependency if `textAnalyzer` is not set or set to `libpostal`.

**Comment by laxatives** [comment]
Yeah that makes sense. The docs are a bit confusing because it clearly indicates libpostal as a recommended, but not required setting, yet the default is to use and require libpostal.

**Comment by trescube** [comment]
Ah, we'll update the documentation, thanks for pointing that out!  You might want to install libpostal, it's a far better address parser than addressit.
