### ISSUE TITLE
Debugging Stability Issues

### ISSUE THREAD

**Issue by laxatives** [pelias/api#848]
Sorry in advance for the vagueness of this issue...

I'm running pelias-api for a long-running task (several weeks) and am having issues with server stability. The task is hitting a single pelias-api endpoint with something like 80 concurrent requests, making close to 100% utilization of 40 cores. This runs well enough, sustaining around 30-50 qps for 12-36 hours (side question -- does this sound right? is it feasible to improve this performance?). But eventually the server poops out and the screen session the task was running in is unreachable. I'd like to run the server and keep logs, but its far too verbose.

So a few questions:

- ~~How can I reduce log verbosity?~~ Great documentation! Its `logger.level` in the config
- What is the best way to run this server in the long term? Is there a better approach than `screen`? Possibly something with some restart behavior?
- How can I improve server reliability?
- How can I improve server throughput?

Pelias-api is backed by two elasticsearch instances running on the same machine on a 4-drive SSD raid with 20 GB heap each. The index is a little under 300GB. `iotop` seems to suggest performance is not disk bound, and R/W is well below 20% utilization.

**Comment by laxatives** [comment]
I've reduced the loglevel to `warn` and see numerous warnings like 
```
2017-04-17T04:50:40.779Z - warn: [api] chaos monkey asks: what happens now?
2017-04-17T04:50:40.885Z - warn: [api] chaos monkey asks: what happens now?
2017-04-17T04:50:41.079Z - warn: [api] chaos monkey asks: what happens now?
2017-04-17T04:50:41.231Z - warn: [api] chaos monkey asks: what happens now?
```

Is this expected?

**Comment by orangejulius** [comment]
Hey @laxatives,
Thanks for writing in. It sounds like you've set things up pretty well overall. Here are some thoughts:

## Running the API server

We use [runit](http://smarden.org/runit/), but there's no real reason to use it in particular. Any service management system would work. [forever](https://www.npmjs.com/package/forever) is an NPM package that handles these things very well.

## Reliability

Our API instances have generally been very reliable and as far as we know don't restart very often. If you happen to catch any error output when it happens pleas forward it on. The chaos monkey warning is normal and is just the result of one developer's frustration at some confusing control flow we will be getting rid of sooner or later :package: 

## Throughput

This is the big one. For most queries, the limiting factor will be the amount of total CPU power available to Elasticsearch. Our production cluster has 6 c4.4xlarge EC2 instances (96 cores) and can do over 300 requests per second for most queries.

What type of queries are you doing? Reverse is the fastest, search is generally the slowest. We are about to finishing rolling out the new [point in polygon service](https://github.com/pelias/pip-service), so if you are doing coarse reverse queries (looking for cities, regions, countries, etc) you will want to look into that. On even a single smaller machine like an `m4.xlarge` (16GB RAM, 4 cores), it can do well over 400 queries per second.
