### ISSUE TITLE
Feedback endpoint

### ISSUE THREAD

**Issue by hkrishna** [pelias/api#87]
Pelias API should have an endpoint where in, a client could give feedback on what the query was and what result item the user selected/used. This information can be helpful in populating our acceptance test cases and generally useful in refining the search quality. 

params:
* **input** Ex: ```123 Main St, New York```
* **resultSelected** Ex: ```123 Main St, Manhattan, NY``` (text/object?)
* **resultIndex** Ex: ```1``` (number)

**Comment by sevko** [comment]
In my opinion, this falls outside the scope of what the API should support, and it seems like something that should be contained in a separate application (like the feedback app).

**Comment by orangejulius** [comment]
Yeah, this is for [pelias/feedback](https://github.com/pelias/feedback)  to do :)
