### ISSUE TITLE
Autocomplete fails on more detailed strings

### ISSUE THREAD

**Issue by laxatives** [pelias/api#871]
For example, the queries below return different results (URL encoded has no match):

`https://search.mapzen.com/v1/autocomplete?api_key=<KEY>&text=2122 W Lone Cactus Dr # 6 Phoenix, Arizona 85027-2650 United States`

`https://search.mapzen.com/v1/autocomplete?api_key=<KEY>&text=2122%20W%20Lone%20Cactus%20Dr%20#%206%20Phoenix,%20Arizona%2085027-2650%20United%20States`

edit: Probably not a URL encoding issue -- the second query, the token is terminated by the `#`, returning `geocoding.query.text: "2122 W Lone Cactus Dr "`

**Comment by orangejulius** [comment]
Hey @laxatives,
Thanks for reporting this. This is definitely not an encoding issue, but limitations of our current address parser for autocomplete. It can't really handle unit numbers and it also usually requires commas to separate parts of an address. Our search endpoint uses a much smarter address parser ([libpostal](https://github.com/openvenues/libpostal)), and it handles things just fine.

Neither address parser handle partial inputs particularly well, which is a key part of any autocomplete endpoint, so we have plans to almost completely rewrite how we do autocomplete in the coming months, although there are no firm dates currently.

## Example queries

### Original query
[/v1/autocomplete?text=2122 W Lone Cactus Dr # 6 Phoenix, Arizona 85027-2650 United States](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=2122%20W%20Lone%20Cactus%20Dr%20%23%206%20Phoenix,%20Arizona%2085027-2650%20United%20States)
![screenshot from 2017-04-28 11-17-30](https://cloud.githubusercontent.com/assets/111716/25535214/4c5bfa58-2c04-11e7-842a-3df9c4b7759c.png)

### Remove unit number, add comma
[/v1/autocomplete?text=2122 W Lone Cactus Dr, Phoenix, Arizona 85027-2650 United States](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=2122%20W%20Lone%20Cactus%20Dr,%20Phoenix,%20Arizona%2085027-2650%20United%20States)
![screenshot from 2017-04-28 11-20-30](https://cloud.githubusercontent.com/assets/111716/25535347/b4b9ffdc-2c04-11e7-9983-92f51bf3705b.png)


### Use search endpoint 
[/v1/search?text=2122 W Lone Cactus Dr # 6 Phoenix, Arizona 85027-2650 United States](http://pelias.github.io/compare/#/v1/search%3Ftext=2122%20W%20Lone%20Cactus%20Dr%20%23%206%20Phoenix,%20Arizona%2085027-2650%20United%20States)
![screenshot from 2017-04-28 11-20-58](https://cloud.githubusercontent.com/assets/111716/25535374/c702e21c-2c04-11e7-842c-54c5f330be68.png)
