### ISSUE TITLE
pretty-format results with a `pretty` parameter

### ISSUE THREAD

**Issue by sevko** [pelias/api#88]
It'd be great if the API could optionally pretty-format JSON via a parameter like `pretty`, so that users would be able to see this when `curl`ing it:

```javascript
{
    "bbox": [
        -73.993641,
        40.721969,
        -73.993641,
        40.721969
    ],
    "date": 1427901010432,
    "features": [
        {
            "geometry": {
                "coordinates": [
                    -73.993641,
                    40.721969
                ],
                "type": "Point"
            },
            "properties": {
                "admin0": "United States",
                "admin1": "New York",
                "admin2": "New York",
                "alpha3": "USA",
                "id": "2ed31dafbbb9419da585e24a29550ce5",
                "layer": "openaddresses",
                "local_admin": "Manhattan",
                "locality": "New York",
                "name": "220 Bowery",
                "neighborhood": "Downtown",
                "text": "220 Bowery, Manhattan, New York",
                "type": "openaddresses"
            },
            "type": "Feature"
        }
    ],
    "type": "FeatureCollection"
}
```

rather than:

```javascript
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"id":"2ed31dafbbb9419da585e24a29550ce5","type":"openaddresses","layer":"openaddresses","name":"220 Bowery","alpha3":"USA","admin0":"United St
ates","admin1":"New York","admin2":"New York","local_admin":"Manhattan","locality":"New York","neighborhood":"Downtown","text":"220 Bowery, Manhattan, New York"},"geometry":{"type":"Point","coordinates":[-73.99364
1,40.721969]}}],"bbox":[-73.993641,40.721969,-73.993641,40.721969],"date":1427901003524}
```

without having to pipe it through something like `python -m json.tool`. It'd make command-line examples cleaner.

**Comment by missinglink** [comment]
This is presentation logic which should really be handled by the client, there may be a minor performance hit to `JSON.stringify` the data, which we should avoid where possible.

If you want to add this to the API then please turn it off by default and enable it with a `?pretty=true` flag or similar, as per the Elasticsearch API.

**Comment by sevko** [comment]
Right, I forgot to mention that this should definitely be opt-in (elasticsearch was what gave me the idea).

**Comment by sevko** [comment]
After some more thought, this seems unnecessary and a little unnatural (frankly, I always thought the elasticsearch option was strange). I'll close this request unless there are any objections.

**Comment by missinglink** [comment]
closing this issue, I personally use this https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en which rocks my world daily
