### ISSUE TITLE
es_rejected_execution_exception

### ISSUE THREAD

**Issue by laxatives** [pelias/api#881]
Is there a max concurrency or rate attached to Pelias/Elasticsearch? Many requests are failing with the following error:

```
"errors": [

    "[es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@2dd48332 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@c56ed59[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1049867400]] (and) [es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@5257ab2b on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@c56ed59[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1049867400]] (and) [es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@36ea1ddd on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@c56ed59[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1049867400]] (and) [es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@2bb40d1b on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@c56ed59[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1049867400]] (and) [es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.TransportService$4@6d71b221 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@235ec013[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1122157677]] (and) [es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.TransportService$4@1b7f1516 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@235ec013[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1122157677]] (and) [es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.TransportService$4@468cd7bd on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@235ec013[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1122157677]] (and) [es_rejected_execution_exception] rejected execution of org.elasticsearch.transport.TransportService$4@1b0a53e0 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@235ec013[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1122157677]]"

],
```

**Comment by orangejulius** [comment]
Hey @laxatives,
There aren't any hardcoded rates, and the performance you'll see will depend on your hardware and how much data you have loaded. If I  remember correctly, that error does mean Elasticsearch is _way_ overloaded.

In our experience, once Elasticsearch is overloaded even a little, it starts to perform much worse very quickly (rather than just maxing out as you send more and more traffic towards it), and eventually fails completely with messages like this.

Can you give us some idea of your hardware and what level of concurrency you were querying Pelias with? We can give you some idea of what performance levels to expect then.

**Comment by laxatives** [comment]
Ah, I see, the performance is mostly bottlenecked in elasticsearch. I've added ~64 GB of free RAM for cache and this issue seems to be resolved.

**Comment by missinglink** [comment]
@laxatives you can use [this API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-thread-pool.html) to poll elasticsearch.

we import documents using the 'bulk' thread pool, if elasticsearch is receiving more requests to import data than it can currently handle, it will add those requests to the corresponding 'thread pool' (ie. import buffer), the API I linked above lets you interrogate how full each of those pools is.

once the pool becomes full, elasticsearch starts rejecting further import requests until the pool has freed up some space, these are the `EsThreadPoolExecutor` messages you are seeing above.

the max pool size is configurable, although it's eventually going to fill up anyway, increasing the CPU throughput or available RAM as you have done is the only real solution.

hope that explains a bit more about what's going on.
