### ISSUE TITLE
Remove coarse reverse boundary.circle.radius warning

### ISSUE THREAD

**Issue by trescube** [pelias/api#915]
Currently all reverse requests that are either explicitly coarse or end up falling back to coarse return a warning of `boundary.circle.radius is not applicable for coarse reverse`.  Due to how the sanitizers work, `boundary.circle.radius` is set to a default if not supplied so by the time the coarse reverse controller runs, it doesn't know that value was explicitly supplied by the user or is a default.  Figure out a way to only add the warning `boundary.circle.radius` was explicitly passed by the user.

**Comment by tigerlily-he** [comment]
Examples: 
- [Middle of the Grand Canyon](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lon=-113.778493&point.lat=36.383607) `/reverse?point.lon=-113.778493&point.lat=36.383607` 
- [Coarse Reverse](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lon=-73.902799&point.lat=40.710166&layers=coarse) `/v1/reverse?point.lon=-73.902799&point.lat=40.710166&layers=coarse`
