### ISSUE TITLE
Reverse should be able to return geonames venues (for now)

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#930]
As of a few months ago we have [amazingly improved coarse reverse geocoding](https://github.com/pelias/api/pull/810) using WOF polygons. A little while after that, we [started throwing errors](https://github.com/pelias/api/pull/904/files) if `sources=geonames` or any variant was specified in reverse. While it's true that for _coarse_ reverse anything except `sources=wof` would not make sense, I believe we can still return geonames venues from regular reverse.

If that's so we should probably update the geonames error message. Right now a query such as [/v1/reverse?layers=venue&sources=geonames&point.lat=47.417&point.lon=10.75](http://pelias.github.io/compare/#/v1/reverse%3Flayers=venue&sources=geonames&point.lat=47.417&point.lon=10.75) always returns an error.
![image](https://user-images.githubusercontent.com/111716/28040658-7c705c92-6594-11e7-8323-6c4a60acec7d.png)

It also might make sense to _add_ error messages for coarse reverse queries with openaddresses or openstreetmap sources specified. Thoughts?

**Comment by Abbe98** [comment]
Recently we had to patch this at biocaching.com. We used Mapzen Search to assign items in our dataset with the nearest GeoNames location for being compatible with another dataset built on top of GeoNames.

We would like to move back to Mapzen Search, and I'm having a similar requirement for personal project where a similar solution is required.

**Comment by missinglink** [comment]
Hi @Abbe98 we are currently discussing a fix for this.

Our long-term vision is to completely remove support for geonames in the mapzen hosted service, we are not going to do this until we are sure that we have the same records available via another data source.

Work is ongoing to import more of geonames in to the whosonfirst project and some day that work will be complete. As part of that import, the geonames ID will be associated so you will still be able to get that ID.

The issue listed here is actually a bug, so we will fix this and let you know.

Additionally we can provide you with a docker container which contains all of geonames if that is useful for you.

Sorry for the inconvenience.
