### ISSUE TITLE
Postgis Support

### ISSUE THREAD

**Issue by saviour123** [pelias/api#937]
Is there a way I connect Postgis data to the pelias api?

**Comment by missinglink** [comment]
hi @saviour123, the search engine is backed by `elasticsearch` (an inverted-index, not a database) and so using a relational database as an alternative backend wouldn't work without a huge refactor.

could you please explain a bit more about what exactly you are trying to achieve and how you expect Postgis to help?

**Comment by saviour123** [comment]
I have has pois sitting in some postgis database, and thinking if there is a way as a datasource.

**Comment by missinglink** [comment]
agh, I see what you mean.

currently there is no importer written for postgres sorry. the easiest solution would be to format-shift the data into a format that we currently support (such as openaddresses CSV) and then use that importer.

we have plans to develop a common file format in the future, unfortunately, this is not ready yet.

**Comment by wucangeo** [comment]
[zombodb](https://github.com/zombodb/zombodb) may be a solution, making Postgres and Elasticsearch work together.
