### ISSUE TITLE
[operations] Domain Root

### ISSUE THREAD

**Issue by missinglink** [pelias/api#94]
Currently when you hit the domain root `http://pelias.mapzen.com/` it serves a plain white HTML page, this is the same behaviour for 404 error pages.

Recently we have been adding the root URL to documentation, notably here: https://github.com/pelias/pelias#im-a-developer-can-i-get-access-to-the-api

Couple questions:
1. Should all endpoints return `application/json`?
2. What should be served at the domain root for the pelias service?
3. What should be served in case of 404 errors; what encoding?

**Comment by missinglink** [comment]
As discussed, let's just let `GET /` pass through for now to the app layer and leave the error pages as-is

**Comment by heffergm** [comment]
curl pelias.mapzen.com/

```json
{
"name": "pelias-api",
  "version": {
    "number": "0.0.0"
  }
}
```
