### ISSUE TITLE
Postalcode Search Issues

### ISSUE THREAD

**Issue by rabidllama** [pelias/api#973]
When searching for postalcode and country (a postalcode should be unique to a country) results are not as expected:

1) For normal searching, providing the country results in an addressit search with multiple records being returned from outside of the country.
2) In structured searching, providing another field along with a postalcode results in the postalcode information being completely ignored 

In both cases, if there is a matching postalcode within the country provided, only that record should be returned.

**Comment by dianashk** [comment]
Hey @rabidllama, we believe this is fixed in production now. Please have a look and let us know if this issue can be closed. Cheers!
